### ISSUE TITLE
Get latest products

### ISSUE THREAD

**Issue by tuankha1994** [tikivn/open-api-docs#104]
Currently get latest products api is missing created_from_date and created_to_date in the request parameters. You can add them as optional parameters?

**Comment by ducanhnguyen19** [comment]
Thank you for your supporting , we will consider add `created_from_date` and `created_to_date` to get latest product api in the near future.
Currently you can browse products by page and limit parameter in the meantime
Thank you in advance

**Comment by vietcaominh** [comment]
Hi @tuankha1994 We have released this function. Go here for more details https://open.tiki.vn/#get-latest-products
Thank you!!
