### ISSUE TITLE
You don't have permission / Your token isn't active now

### ISSUE THREAD

**Issue by ndquocphong** [tikivn/open-api-docs#109]
Theo hướng dẫn mình đã đăng kí một tài khoản ở trang https://sandbox-sellercenter.tiki.vn/, để lấy token (Tham số kết nối). Nhưng đã hơn 2 ngày, mình vẫn găp lỗi khi truy cập API. 
```
{
    "errors": [
        "You don't have permission / Your token isn't active now"
    ]
}
```
Thêm một vấn đề là mình đã gửi message tới Tiki Supporter để hỏi về thông tin inventory_type và supplier trên môi trường sandbox, nhưng chưa thấy phản hồi. 

Mong các dev TIKI giúp đỡ, cảm ơn 👍

**Comment by ducanhnguyen19** [comment]
can you give me your email , I will give you a test token

**Comment by ndquocphong** [comment]
@ducanhnguyen19  yep, my email is ndquocphong@gmail.com, thank you. But how about inventory_type and supplier, I need them to create product.

**Comment by ducanhnguyen19** [comment]
I sent token , supplier test to your email , you can choose inventory_type in the list here : https://open.tiki.vn/#inventory-type
