### ISSUE TITLE
Problem return null with value "Shipping" API Get list orders .

### ISSUE THREAD

**Issue by thienbaoanhvn** [tikivn/open-api-docs#111]
Hi Tiki ,
please help us check API Get list orders , API suddenly return null value shipping  . 
Thanks .
![Capture](https://user-images.githubusercontent.com/60771894/75411074-94631a80-5950-11ea-828c-395b9e575f1d.PNG)

**Comment by ducanhnguyen19** [comment]
sorry for this inconvenient , based on the protection of customers' personal information, we are forced to hide shipping information if the seller does not directly deliver products.

You can see the detail here : https://open.tiki.vn/#shipping
Thank you

**Comment by thienbaoanhvn** [comment]
Thank for your answer  , but your team should consider why we create API , without information API will be useless . I know that any shopping mall will have different rule , but until now I connect API with another ex : Amazon , Lazada , Shopee , Sendo ... they really open , we can easy get all information , why they do that ? I think they really want to open friendly platform and convenient for customer also for Seller .  
Before Metro market they are the big one in VN but they limited the're customer , one day Aeon ,Lotte they come  they open Market  really convenient and freedom . You're smart for guess the result  what go in on .
I think Tiki really insight , hope that you deeply think about that .

**Comment by ducanhnguyen19** [comment]
Thanks for your suggestions, TIKI wants to create an open platform to welcome all sellers, but the system scale too quickly will bring security holes. Bad sellers may steal your sales information and your customers one day. We would love to listen your idea and will discuss further on this issue

**Comment by tuhucon** [comment]
@thienbaoanhvn 
which informations in shipping field do you want ?

**Comment by thienbaoanhvn** [comment]
Thank you for listening , we need all of them .
![Capture](https://user-images.githubusercontent.com/60771894/75420382-86ba8e80-596a-11ea-8ed0-f85825ffdc39.PNG)

**Comment by thienbaoanhvn** [comment]
I think Amazon and Alibaba they are really big company but they still open information for us, that mean they really careful with they're decision. if you worry about security tell me you will confident solve it, that a good responsibility with us .

**Comment by thienbaoanhvn** [comment]
I think you know personal seller or small company they won't need API because they have no system , with us you're API really helpfull and save time for us , if 1 day we have more than 1000 order we have no time for manually copy data from Tiki system to our system . Big sellers they will think same with us .

**Comment by tuhucon** [comment]
@thienbaoanhvn 
shipping information is returned in tiki-delivery, cross-border orders because seller need these informations to delivery products to user.

Due to privacy policy, we can not return shipping information for other orders,
but how do you think if we return user_id in these orders (hope it will help you to identify unique user) ?

**Comment by thienbaoanhvn** [comment]
yes , please give us , user_id unique and customer name , thanks .

**Comment by hoank92** [comment]
> Sorry in sellercenter.tiki.vn we can see . limited information
> ![Capture](https://user-images.githubusercontent.com/60771894/75748195-66ffdd80-5d51-11ea-844a-9c5ab4cd6dd3.PNG) Why you din't return that value in API for us ?

what is your order_code? 
let me check it

**Comment by thienbaoanhvn** [comment]
Hi Tiki .
I'll summary my issue , We're use API Get list orders , but value shipping return is null , @tuhucon  reply because privacy policy but I wonder why in sellercenter.tiki.vn Tiki show us shipping . can you return that shipping info in API ?

**Comment by tuhucon** [comment]
Your concern is correct, we will return name, address like sellercenter in our api

**Comment by bluekid1101** [comment]
In my opinion, the open_api system of some common e-commerce sites is provides a solution for small seller and also big brands for managing their sales, building the erp system, and cross e-commerce platform management and other purposes. Due to the policy of system, some info need to be hided. But your team can create a validation system like lazada has done. The validation process can ensure that your seller system is secure enough for tiki to unmask the data for seller in use for their purpose.

**Comment by thienbaoanhvn** [comment]
Thank you .
