### ISSUE TITLE
Cần phân biệt đơn Hàng lưu kho tại Tiki và hàng ở cửa hàng

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#112]
![IMG_1368](https://user-images.githubusercontent.com/45413747/75420409-92a65080-596a-11ea-94c0-02a7db3bf6c1.JPG)
Hiện tại doanh nghiệp đang không muốn lấy đơn TIKI LƯU KHO vì khi lấy về thì khi đồng bộ tồn sẽ sai lệch tồn kho tại cửa hàng. Mong Tiki kiểm tra lại và có thể xử lý theo 1 trong 2 phương án:
 1. Không trả về đơn TIKI LƯU KHO
 2. Trả thêm field để phân biệt đơn TIKI LƯU KHO và TỒN TẠI CỬA HÀNG

**Comment by tuhucon** [comment]
we will create a backlog for this story.
Thanks :)

**Comment by hoai-dam** [comment]
Hi @Hungpx, 

Each order has many order item. 
Each order item has `inventory_type` either of value `backorder` or `instock`. You can distinguish these orders by distinguishing their `item.inventory_type`.

If an order has all items of type `instock` - TIKI LƯU KHO
If an order has at least 1 item of type `backorder` - TỒN TẠI CỬA HÀNG - And you can use this item to calculate the inventory changes for the store

Thanks,
