### ISSUE TITLE
Lỗi "Seller ko cho phép đồng bộ sản phẩm"

### ISSUE THREAD

**Issue by kabuky** [tikivn/open-api-docs#113]
Hi Tiki Dev,

Bên mình là cross border seller, mình dùng API để update sku quantity thì hệ thống báo lỗi sau:
{
  integration_status: 1
msg: "Seller ko cho phép đồng bộ sản phẩm"
product_is_sync: 0
}
Nhờ Tiki dev check giùm.

**Comment by ducanhnguyen19** [comment]
![image](https://user-images.githubusercontent.com/51348919/75503030-1dd52400-5a07-11ea-84c3-b7ff97738070.png)
please confirm your `Tự động cập nhật SP` is activated 
you can check the detail here : https://open.tiki.vn/#authentication

**Comment by kabuky** [comment]
![image](https://user-images.githubusercontent.com/1215595/75549105-d59b1d80-5a69-11ea-8a4a-e9a356bdfa66.png)

Apparently our account has permission issue to activate it.
