### ISSUE TITLE
![image](https://user-images.githubusercontent.com/1215595/75549105-d59b1d80-5a69-11ea-8a4a-e9a356bdfa66.png)

### ISSUE THREAD

**Issue by kabuky** [tikivn/open-api-docs#116]
![image](https://user-images.githubusercontent.com/1215595/75549105-d59b1d80-5a69-11ea-8a4a-e9a356bdfa66.png)

Apparently our account has permission issue to activate it.

_Originally posted by @kabuky in https://github.com/tikivn/open-api-docs/issues/113#issuecomment-592494848_

**Comment by ducanhnguyen19** [comment]
issues base on permission of seller please contact to your supporter . In this case : she is thao.vo@tiki.vn
