### ISSUE TITLE
permission issues please contact to your supporter ( Người phụ trách ) to get help

### ISSUE THREAD

**Issue by kabuky** [tikivn/open-api-docs#117]
Hi Tiki Dev,

After permission is set in seller center, I encounter this error "Internal API went wrong, please try again later" when trying to update sku with price & quantity.

And also the product API does not return the quantity. Please help to return this field as it is important and we need it to synchronize with our stocks count.

------------------------------------------------------------------------------------------
permission issues please contact to your supporter ( Người phụ trách ) to get help

_Originally posted by @ducanhnguyen19 in https://github.com/tikivn/open-api-docs/issues/116#issuecomment-593278764_

**Comment by ducanhnguyen19** [comment]
Hi,
Can you check your request again from the docs here : https://open.tiki.vn/#update-product-information
I just check the API still work normally

**Comment by kabuky** [comment]
Just tried again and able to update price & quantity now. However, getProduct API still does not return stock quantity value.

**Comment by ducanhnguyen19** [comment]
thank for your support , we added this job into our to do list , we will release it in the next phase , thank you

**Comment by ducanhnguyen19** [comment]
@kabuky we just add inventory information into get product detail API , you can try this : https://open.tiki.vn/#get-a-product

Thank you for your supporting

**Comment by kabuky** [comment]
@ducanhnguyen19 Thank you for your support. Appreciate that! Received inventory information safe and sound. Another request is that for Orders API, are you able to return the seller's revenue for each orders (after tax, commission and other fees deduction). At the moment, I only receive total_price_after_discount which does not factor in all the above fees.

**Comment by ducanhnguyen19** [comment]
can you create new issue for this ? we will consider and add it into to do list
I close this issue due to its completion
