### ISSUE TITLE
Get all categories by lang 

### ISSUE THREAD

**Issue by bluekid1101** [tikivn/open-api-docs#120]
Hi tiki dev team,
I have tried to use API get categories but get the results:
+ lang = en/default -> return 1712 lines json result
+ lang = vi -> return 113761 lines json result
So I wonder that your api classifies the categories by language category name or is there any problem happened? Cause there are too much categories return but some of those look like the sku name rather than the category name 
Tks !!!

**Comment by ducanhnguyen19** [comment]
sorry for the misunderstood , category language stand for where the product come from
* lang = en/default -> your product will be listed in `international product` here : https://tiki.vn/hang-quoc-te for cross border seller 
* lang = vi -> your product will be listed as `local product` for Vietnamese seller 
I will be update this note to the document 
Thank you for your support
