### ISSUE TITLE
API update price, quantity, active

### ISSUE THREAD

**Issue by bluekid1101** [tikivn/open-api-docs#121]
I have a misunderstanding when using the API update price, quantity, active. Following the guideline on openAPI: 
![image](https://user-images.githubusercontent.com/34758547/75857193-540c0c80-5e28-11ea-8892-d6e486e05540.png)

what is the specific "sku" field in this document? I have tries my ways on postman but always return as below:
![image](https://user-images.githubusercontent.com/34758547/75857736-41460780-5e29-11ea-9af0-d3f7b106d726.png)

Tks for your support!

**Comment by ducanhnguyen19** [comment]
the correct method is POST , not GET
thank you
