### ISSUE TITLE
Which permissions are allowed to use Update market price / images API?

### ISSUE THREAD

**Issue by bluekid1101** [tikivn/open-api-docs#122]
Hi team, 
I made a test on Update market price / images API. But there might be something wrong in the API documentation when it doesn't describe the param needed to update. 
However, I try to pass a body param with product_id, market_price to edit. The response is shown as below:
![image](https://user-images.githubusercontent.com/34758547/75872041-131ff200-5e40-11ea-8994-795bc3c141bd.png)

So please help me to use this API properly!
Thanks for your support!

**Comment by ducanhnguyen19** [comment]
we have example in the right column here : https://open.tiki.vn/#update-product-information
```
{
    "product_id": {product_id},
    "market_price": {new_market_price}
}
```
