### ISSUE TITLE
Get all products filtered by category_id returned non-owner product!!

### ISSUE THREAD

**Issue by bluekid1101** [tikivn/open-api-docs#129]
Hi team,
There is a big issue that get products api filter by category_id returned the products which are not belong to seller. The first below shown without filtering and the second with filtering.
![image](https://user-images.githubusercontent.com/34758547/76046397-673aeb80-5f92-11ea-8d4e-3efff80e3c95.png)
-
![image](https://user-images.githubusercontent.com/34758547/76046505-a79a6980-5f92-11ea-85b6-63bf7b44448c.png)

**Comment by bluekid1101** [comment]
Note that only happened when use non-primary category_id, the primary is seem to work properly

**Comment by ducanhnguyen19** [comment]
ok , thank you for your report , we are fixing

**Comment by ducanhnguyen19** [comment]
@bluekid1101 thank for your supporting , the bug is fixed , can you help us last check in your side ?
