### ISSUE TITLE
Tiki đang trả về đơn không phải của nhà bán?

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#136]
![image](https://user-images.githubusercontent.com/45413747/76479492-8deb9d00-643e-11ea-8387-4669098212da.png)
Doanh nghiệp bán đơn này không phải của họ, phiền team check lại xem đơn này là như thế nào ạ?

**Comment by ducanhnguyen19** [comment]
sorry for this inconvenience , we are hot fixing this bug :((

**Comment by hoank92** [comment]
> phải

We have checked, but it is your orders? @Hungpx

**Comment by Hungpx** [comment]
> > phải
> 
> We have checked, but it is your orders?, You can give us more information
> @Hungpx

Nhà bán hàng báo lại là đơn này họ không tìm thấy trên TIKI, và cũng không bán đơn hàng đó ạ. Team cần thêm thông tin gì ạ?

**Comment by hoank92** [comment]
@Hungpx You provide me seller information, thank you!

**Comment by Hungpx** [comment]
> @Hungpx You provide me seller information, thank you!

Seller: DOF.zone, Client Key: acb614dd-720c-4227-a454-075d696bad73

**Comment by ducanhnguyen19** [comment]
please don't provide api-key in public area @Hungpx

**Comment by Hungpx** [comment]
seller: DOF.zone

**Comment by hoank92** [comment]
We checked, but the order was from DOF.zone, there was no mistake. Please tell the seller to check back.
Thank!
