### ISSUE TITLE
Any plan for webhooks support?

### ISSUE THREAD

**Issue by nathantruong2405** [tikivn/open-api-docs#137]
Hi Tiki dev team, I really appreciate your effort in this well-documented apis. Do you have any plan for webhooks support? E.g: events for Order Created, Product Request Updated, ...

**Comment by ducanhnguyen19** [comment]
thank you for your feedback , because this feature affect to some other internal team , so we had a plan to do it but maybe it will cost some time . We will tell you once we can do webhook support :D

**Comment by vietcaominh** [comment]
Hi @nathantruong2405 We have released the first version of webhook support here https://open.tiki.vn/#webhook. You go there for more details

**Comment by nathantruong2405** [comment]
Many thanks for your update @vietcaominh @ducanhnguyen19 <3
