### ISSUE TITLE
Trường hợp lỗi không thể in nhãn đơn hàng API print order labels

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#139]
{"errors":["you don't have permission print order"]}
Tài khoản của doanh nghiệp in đơn hàng hiện tại đang bị báo lỗi này? Team check lại giúp với ạ.

**Comment by vietcaominh** [comment]
Hi @Hungpx. The print order labels API only available for orders have fulfillment type are seller_delivery and cross_border. Let us know more if your order doesn't fall into those types and still want to get the order label.

**Comment by Hungpx** [comment]
Hi @Hungpx. The print order labels API only available for orders have fulfillment type are seller_delivery and cross_border
===================================================>
cái này team có thể giải thích rõ hơn được không ạ? tức là đơn hàng ở trạng thái nào thì có thể in nhãn đơn hàng ạ? Em chưa hiểu ý này là gì? Các đơn lấy về thường ở trạng thái **seller_confirmed** và trạng thái này thì không in đơn được?

**Comment by ducanhnguyen19** [comment]
you can refer here for more detail : 
- https://open.tiki.vn/#inventory-type
- https://open.tiki.vn/#print-order-label
This API is used when your order are seller delivery or cross_border, it is used to print order label for shipping. This contains shipping information only so if your order does not fall into these two type you can simply ignore this endpoint

inventory_type is different from order status my friend, so it doesn't matter to `seller_confirmed` or `queuing` or any other status
