### ISSUE TITLE
@hoank92  Active giúp mình id:22551 tài khoản sandbox , mình muốn tích hợp api tiki vào hệ thống bên mình. Thanks

### ISSUE THREAD

**Issue by kenpi04** [tikivn/open-api-docs#142]
@hoank92  Active giúp mình id:22551 tài khoản sandbox , mình muốn tích hợp api tiki vào hệ thống bên mình. Thanks

_Originally posted by @kenpi04 in https://github.com/tikivn/open-api-docs/issues/90#issuecomment-600970591_

**Comment by vietcaominh** [comment]
Solved in https://github.com/tikivn/open-api-docs/issues/90#issuecomment-600972043.
Thanks
