### ISSUE TITLE
Active tài khoản sandbox

### ISSUE THREAD

**Issue by cuongvoduy** [tikivn/open-api-docs#145]
Mình đăng kí tài khoản sandbox nhưng khi truy vấn api lại báo chưa được active ạ
ID người dùng 22511
Mã gian hàng S00022511
Vẫn còn trạng thái chờ xác nhận

**Comment by vietcaominh** [comment]
Hi @cuongvoduy . We have activated your account on sandbox. You can try to access it now. Let us know if you have any problem

**Comment by cuongvoduy** [comment]
Thanks for your reply!

**Comment by vietcaominh** [comment]
Thanks. I will close it for now. If you have further request pls let us know
