### ISSUE TITLE
Đơn hàng không thấy tải về từ api

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#146]
![image_2020_03_20T05_30_12_816Z](https://user-images.githubusercontent.com/45413747/77140591-aac24900-6aac-11ea-9e92-3a451c422ee9.png)
Đơn này Seller tải về thì không thấy có ở api, team check giúp em với ạ?

**Comment by vietcaominh** [comment]
Hi @Hungpx. Let us check your order. Please wait for us.

**Comment by hoank92** [comment]
We have returned it via: https://api.tiki.vn/integration/v1/orders?status=all
@Hungpx, currently your order status is _ready_to_ship_

**Comment by vietcaominh** [comment]
Hi @Hungpx can you confirm the API still working for you. If it's ok I will close it.

**Comment by Hungpx** [comment]
> Hi @Hungpx can you confirm the API still working for you. If it's ok I will close it.

==================================================>
 ok rồi ạ. Cảm ơn Team

**Comment by vietcaominh** [comment]
Thank you! I will close it now.
