### ISSUE TITLE
sandbox-sellercenter Can't see the order

### ISSUE THREAD

**Issue by plken** [tikivn/open-api-docs#147]
1、sandbox-sellercenter.tiki.vn
  API：https://api-sandbox.tiki.vn/integration/v1/orders
  API I can get the order, but the seller center can't find the order

2、Why does the order_code of the same order change
   API：https://api-sandbox.tiki.vn/integration/v1/orders
   order_code sometimes this:327965376-skBkQ3,sometimes another:327965376-HHRBH2

**Comment by hoank92** [comment]
> 1、sandbox-sellercenter.tiki.vn
> API：https://api-sandbox.tiki.vn/integration/v1/orders
> API I can get the order, but the seller center can't find the order
> 
> 2、Why does the order_code of the same order change
> API：https://api-sandbox.tiki.vn/integration/v1/orders
> order_code sometimes this:327965376-skBkQ3,sometimes another:327965376-HHRBH2
please read document first https://open.tiki.vn/#test-orders,
in sandbox environment we mock orders for you test follow
