### ISSUE TITLE
Active tài khoản sandbox

### ISSUE THREAD

**Issue by trongnhann** [tikivn/open-api-docs#148]
Mình đăng kí tài khoản sandbox nhưng khi truy vấn api lại báo chưa được active ạ.
ID người dùng: 22488
Mã gian hàng: S00022488
Vẫn còn trạng thái chờ xác nhận.
Mong sớm nhận được sự phản hồi từ các bạn ạ. Xin chân thành cảm ơn!

**Comment by hoank92** [comment]
Duplicate of #145

**Comment by hoank92** [comment]
Duplicate of #68
