### ISSUE TITLE
Can I have the Order Status Flow

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#149]
I have read the doc with all tiki order status but i don't know the flow of order status corresponding with 3 business types of tiki (FBT, SD & ODF). 
For examples:
+ which status only appears in FBT, or SD, ODF.
+ the order (flow) of status in ODF
Somethings likes:  https://open.shopee.com/documents?module=63&type=2&id=54

![image](https://user-images.githubusercontent.com/33923655/77657725-46215580-6fa8-11ea-8047-7ddfcf7e1e84.png)

**Comment by tuhucon** [comment]
yes, sure.
