### ISSUE TITLE
Is there any threshold or request limit of calling tiki api ?

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#150]
And how to increase the limit to reach our demands

**Comment by vietcaominh** [comment]
Hi @hungsmcc . Currently, the request limit is 100 requests/s.
You can share with us more details reason **if** your demands exceed that number!

**Comment by hungsmcc** [comment]
Is 100 requests/s limit applied for a shop or an IP address?

**Comment by vietcaominh** [comment]
Hi @hungsmcc 100 request/s apply for shop (seller)
