### ISSUE TITLE
"fulfillment_type" value in order details api is empty sometimes. Which value does it actually have in these cases.

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#152]

**Comment by vietcaominh** [comment]
hi @hungsmcc . Sorry for your inconvenience.
Can you share which us the order code and environment of the orders you see that happened?

**Comment by hungsmcc** [comment]
order_code: "249649909"
env: "PROD"

**Comment by vietcaominh** [comment]
Hi @hungsmcc. We saw the fulfillment_type is empty here. Let us check with the team and get back to you soon here

**Comment by vietcaominh** [comment]
hi @hungsmcc . We have fixed the error. It should never return empty now. Thanks

**Comment by hungsmcc** [comment]
thanks so much for your support
