### ISSUE TITLE
[Datamart] API confirm order items on Sandbox Env - Reject order problem

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#153]
I want to cancel an order as the api doc said:
> So if you want to reject all of item in this order, just send an empty item_ids list

However, the api's response is:
{"errors":["item_ids is required"]}

My request:
`
POST /integration/v1/orders/confirmItems HTTP/1.1
Host: api-sandbox.tiki.vn
Content-Type: application/json
Tiki-Api: 55f438d1-3438-409e-b5a4-9d16e764c5b8

{"delivery_commitment_time":"","item_ids":[],"order_code":"327965376-6huPMG","warehouse_id":0}
`

**Comment by vietcaominh** [comment]
Hi @hungsmcc . Thank you for report that bug. We're aware of that, we will fixing it in the next release. We will update you when the fix gets deployed on product.

**Comment by vietcaominh** [comment]
hi @hungsmcc . This is got fixed on both sandbox and production environments. You can try again now, please let us know if you have problems?

**Comment by hungsmcc** [comment]
many thanks, it worked on the sandbox. I don't have chance to cancel an order on prod for now
