### ISSUE TITLE
Check tình huống đồng bộ tồn và cập nhật sản phẩm theo sku + Thêm cột Exel thanh toán đơn hàng

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#157]
- Hiện tại bên mình đang hỗ trợ api đồng bộ tồn và update sản phẩm nhưng lại theo original_sku, tuy nhiên thì đây là mã sản phẩm người dùng tự định nghĩa, và thường thì họ không tạo mã này => không đồng bộ được, muốn đồng bộ thì phải update original_sku. Mong team check lại.
- File Excel thanh toán tiền cho Seller, mong team trả thêm 1 cột ID sản phẩm để bên mình dễ dàng check hơn, thay cho việc dùng cột SKU để check sản phẩm.
Thanks Team!

**Comment by tuhucon** [comment]
- Sắp tới bên mình sẽ thêm API cho việc update sản phẩm theo product_id

- File excel thanh toán tiền cho Seller là bạn lấy qua API nào thế nhỷ ?

1.

**Comment by Hungpx** [comment]
> * Sắp tới bên mình sẽ thêm API cho việc update sản phẩm theo product_id
> * File excel thanh toán tiền cho Seller là bạn lấy qua API nào thế nhỷ ?

File Excel thanh toán bên mình đang lấy file trực tiếp từ phần mềm bên mình chứ ko qua API ạ. Tức là Seller sẽ lấy file Excel Tiki thanh toán cho doanh nghiệp theo sản phẩm, sau đó sẽ import lên hệ thống bên mình và hệ thống bên mình sẽ xử lý việc đối soát tiền của Seller.  Mong team trả thêm 1 cột ID sản phẩm trong file Excel đó cho bên mình dễ check ạ

**Comment by tuhucon** [comment]
Cái file excel này được lấy từ màn hình nào nhỷ, bạn nhờ seller chụp cho mình cái ảnh màn hình đươc ko.

**Comment by Hungpx** [comment]
![1](https://user-images.githubusercontent.com/45413747/79180693-c8c56400-7e34-11ea-94a5-eecd9a96f6e4.jpg)

ảnh file mẫu đây ạ

**Comment by Hungpx** [comment]
phiền team check cho vấn đề này với ạ?

**Comment by vietcaominh** [comment]
@tuhucon please help check
