### ISSUE TITLE
Check trạng thái đơn Tiki đã lấy hàng

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#161]
Api get orders Tiki, Team thêm giúp mình 1 trường đánh dấu đơn Tiki đã lấy hàng để mình check trường hợp này được không ạ?

**Comment by vietcaominh** [comment]
hi @Hungpx , Please post your relevant information and your question clearly! Pls don't send us your chat conversation, the image quality is low and we don't have the context of your conversation. That makes it hard for us to understand your problem. Thanks

**Comment by Hungpx** [comment]
Tức là trường hợp Đơn bị hủy(trạng thái cancel) nhưng là sau khi Tiki đã lấy hàng và bàn giao cho khách, thì Tiki có thể trả về ngày giao hàng hoặc trả về trạng thái Tiki đã lấy hàng hay chưa được không ạ?

**Comment by vietcaominh** [comment]
Hi @Hungpx 
So your question is when an order gets canceled (various reasons) you want to know whether Tiki has got the order from the seller or not? I am assuming that you're talking about backorder orders?
Is that correct to you?

**Comment by vietcaominh** [comment]
Hi @Hungpx are you still working on this, if you're not anymore we will close it?

**Comment by Hungpx** [comment]
> Hi @Hungpx are you still working on this, if you're not anymore we will close it?

Vâng, ok ạ

**Comment by vietcaominh** [comment]
Hi @Hungpx . So you not need that information anymore?
