### ISSUE TITLE
Làm sao lấy được mã phiếu gửi vậy Ad?

### ISSUE THREAD

**Issue by chuongld** [tikivn/open-api-docs#162]
Trong phiếu in dán trên kiện hàng chỉ có mã vạch của mã phiếu gửi. Trong khi thông tin lấy về từ API đơn hàng không có mã này?

**Comment by vietcaominh** [comment]
Hi @chuongld 
Do you want to get place order code in order details endpoint?
Please tell us more about your use cases that needed that information?

**Comment by chuongld** [comment]
Hi @vietcaominh 
Không phải mã đơn hàng, Nó là mã barcode khi in dạng : HN4/BOP/20/04/530637

**Comment by vietcaominh** [comment]
hi @chuongld Yes, this barcode is what I was referred. Please tell us your use cases that need the barcode in Get order list or Get order details endpoints? So we can consider support it?

**Comment by chuongld** [comment]
Shop khi đóng hàng chuyển đi, cần mã theo dõi, giống như mã vận đơn. Hiện phiếu in ra chỉ có cái mã đó là được in mã vạch. Mã đơn hàng không có mã vạch. SHOP sẽ dùng luôn mã đó để theo dõi đơn hàng trước khi chuyển cho tiki

**Comment by vietcaominh** [comment]
Hi @chuongld . Let us check on that and get back to you

**Comment by vietcaominh** [comment]
Hi @chuongld . We are understanding you want to track order's status via PO barcode (ex HN4/BOP/20/04/530637) because when seller packing the orders the order code doesn't display in **barcode format**. So you want to support your sellers to tracking orders via barcode only, not plaintext like order code?

**Comment by vietcaominh** [comment]
Hi @chuongld ? Are you still getting a problem with this?

**Comment by chuongld** [comment]
> Hi @chuongld ? Are you still getting a problem with this?

Yes

**Comment by vietcaominh** [comment]
hi @chuongld Chu
Ok, we're working on the get PO label in this sprint. It is likely to release on this week. Please stay tuned!

**Comment by vietcaominh** [comment]
hi @chuongld we just release API to get PO label. Please check it here
https://open.tiki.vn/#api-get-order-po-label

**Comment by chuongld** [comment]
ok, thanks
