### ISSUE TITLE
Team Tiki check lại giúp mình field NGÀY GIAO HÀNG

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#168]
![image_2020_04_20T10_38_07_297Z](https://user-images.githubusercontent.com/45413747/79820851-75649000-83b7-11ea-9e39-5af93e0e9a9a.png)
Api mình lấy về hiện tại (**delivery_confirmed_at**) đang là ngày 13/4, trong khi Seller báo ngày giao hàng chính xác là 10/4. Team check lại cho mình với ạ

**Comment by Hungpx** [comment]
.

**Comment by vietcaominh** [comment]
Hi @Hungpx . We confirmed the delivery success date is 10/4. Let us check on that for you and get back you soon on this.
CC @tuhucon

**Comment by hoai-dam** [comment]
Hello @Hungpx ,

We released the fix for this issue, could you please check if successful delivery date is correct now?

Thanks,
