### ISSUE TITLE
Getting 403 Forbidden in the API response

### ISSUE THREAD

**Issue by NehaTahalani** [tikivn/open-api-docs#169]
Hi Team,
We are getting 403 in the API response, Can you please check?
Sharing below the curl request:
curl --location --request GET 'https://api-sandbox-sellercenter.tiki.vn/integration/multichannel/regions' \
--header 'tiki-api: 87b6797f-1153-4e95-8a78-b915cec9f8ad' \
--header 'content-type: application/json'

**Comment by vietcaominh** [comment]
Hi @NehaTahalani 
Have you just started the integration with Tiki? if yes we suggest you to work with our new version of open API, the docs are here https://open.tiki.vn
The old version is not under maintenance, so many bugs could happen

**Comment by Swapnilgadewar** [comment]
@vietcaominh, We already integrated using following API's, now wanted to integrate the FBT and Crossborder module, can you please confirm we can still refer to the below for these integration?

https://sellercenter-api-docs.tiki.vn/#overview

**Comment by vietcaominh** [comment]
Hi @Swapnilgadewar . This old version is not under maintenance. If some bug occur it will get fix really really slow. I think it's the best you switch to use our new version, it's currently developing and you can get support really fast. 
I think it does not take much time to switch cause the functionality basically the same.
Hope to hear from you!

**Comment by Swapnilgadewar** [comment]
Thank you @vietcaominh 
We will refer to the newer version of the document for further development.
