### ISSUE TITLE
Cần thêm dữ liệu api order's response

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#170]
![image_2020_04_20T10_38_07_297Z](https://user-images.githubusercontent.com/45413747/79933981-a4443a00-847b-11ea-85f6-e1d3f0414485.png)
- Hiện tại phần chiết khấu sản phẩm khi get orders đang lấy giảm giá theo cột bên trái, Tiki có thể trả vể thêm dữ liệu ở cột PHÍ TRẢ TIKI được không ạ? vì đây mới là phần mà seller quan tâm, bao gồm: Chiết khấu, phí cố định, phí lấy hàng

**Comment by vietcaominh** [comment]
@tuhucon please help check!

**Comment by tuhucon** [comment]
we will create a backlog for this issuse.

**Comment by xenlong** [comment]
Hi, in V2 Tiki API, please add back fee types (percent_per_item_sales_value, payment_processing_fee, handling_fee, shipping_fee, shipping_fee) instead of total_seller_fees only.

**Comment by tuhucon** [comment]
@xenlong please read https://open.tiki.vn/#order-api-v2

**Comment by hoai-dam** [comment]
We're closing this issues due to no more interaction.
