### ISSUE TITLE
Cần thêm trường đánh dấu đơn đã được trả lại

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#171]
![z1844423606635_4e9ae31c8a300ffc1b0f2c31b83e5573](https://user-images.githubusercontent.com/45413747/79950539-69ed9380-84a1-11ea-864a-033aea084eac.jpg)
Đơn này Seller báo đã chuyển hoàn và gửi trả lại rồi, nhưng api trả về vẫn là trạng thái THÀNH CÔNG. Team check trả thêm trạng thái ĐÃ CHUYỂN HOÀN với ạ

**Comment by Hungpx** [comment]
.

**Comment by vietcaominh** [comment]
Hi @Hungpx . Let us check on that.

**Comment by vietcaominh** [comment]
@ducanhnguyen19

**Comment by hoai-dam** [comment]
Duplicate of #197
