### ISSUE TITLE
Update giá, số lượng qua productId lỗi

### ISSUE THREAD

**Issue by chuongld** [tikivn/open-api-docs#179]
POST
https://api.tiki.vn/integration/v1/products/ID sản phẩm
request
{
  "product_id": ID sản phẩm,
  "price": 57000,
  "quantity": 3,
  "active": 1
}
trả về
{
"errors": [
  "Request method 'POST' not supported"
],
}

**Comment by vietcaominh** [comment]
Hi @chuongld, the endpoint you referred does not exist.
 If you want to update product price, quantity, you should use this one.
POST https://api.tiki.vn/integration/{version}/requests/updateProductInfo
Link to refer https://open.tiki.vn/#update-market-price-images

**Comment by nguyenphuthuybk** [comment]
nếu là php bạn thử code sau 
<?php

      $curl = curl_init();
      curl_setopt_array($curl, array(
      CURLOPT_URL => "https://api.tiki.vn/integration/v1/products/updateSku",
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_ENCODING => "",
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 0,
      CURLOPT_FOLLOWLOCATION => true,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => "POST",
      CURLOPT_POSTFIELDS => json_encode($data),
      //CURLOPT_POSTFIELDS =>'{"product_id": 34641614,"price": 411000,"quantity": 15,"active": 1}',
      CURLOPT_HTTPHEADER => array(
        "tiki-api: your_api",
        "Content-Type: application/json"
      ),
    ));

    $response = curl_exec($curl);
    curl_close($curl);

     echo "<pre>";
     print_r(json_decode($response, true));
     echo "</pre>";
?>

**Comment by chuongld** [comment]
Mình test thử qua tool cũng không được?
Với lại mình muốn update qua product_id mà. sao trong đoạn mã vẫn thấy là "updateSku"

**Comment by nguyenphuthuybk** [comment]
Nên dùng postman.com để test ! url phải là https://api.tiki.vn/integration/v1/products/updateSku không phải là  https://api.tiki.vn/integration/v1/products/ID  
Đoạn https://api.tiki.vn/integration/v1/products/ID là get lấy về dữ liệu ko nhận POST

**Comment by chuongld** [comment]
ok, cảm ơn bạn

**Comment by vietcaominh** [comment]
hi @chuongld is the problem get resolved for you? If yes, I will close this ticket
