### ISSUE TITLE
[Datamart] Need an API providing Consignment notes ("phiếu gửi hàng" in vietnamese) for ODF seller

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#185]
![photo_2020-05-08_16-09-34](https://user-images.githubusercontent.com/33923655/81391117-c1992980-9146-11ea-9f12-bc0c484383a6.jpg)
![phieu gui hang tiki](https://user-images.githubusercontent.com/33923655/81391125-c52cb080-9146-11ea-9b5a-a93c11230fc6.jpg)

Thanks team so much

**Comment by tuhucon** [comment]
we will create a api for it in this sprint

**Comment by thinhhn** [comment]
We also need api for ODF printing. Please try to complete it

**Comment by vietcaominh** [comment]
hi @thinhhn thinh
Yes, we're working on them in this sprint. Please stay tuned

**Comment by vietcaominh** [comment]
Hi @hungsmcc and @thinhhn we have released API to get PO label. Please check it here https://open.tiki.vn/#api-get-order-po-label

**Comment by hungsmcc** [comment]
oh thanks so mụch

**Comment by thinhhn** [comment]
@vietcaominh So fun. Thanks for you support.
