### ISSUE TITLE
Interface transfer parameters of the problem

### ISSUE THREAD

**Issue by chengbirght** [tikivn/open-api-docs#189]
Hello, I obtained the access_token, but I did n’t understand what should be written in the header parameter when requesting the interface?

**Comment by vietcaominh** [comment]
@hoai-dam  please assist @chengbirght

**Comment by vietcaominh** [comment]
hi @chengbirght you're using API key or using Oauth2 access token?

**Comment by chengbirght** [comment]
Hi,My problem has been solved, thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Steven"<notifications@github.com&gt;; 
发送时间: 2020年5月25日(星期一) 上午10:34
收件人: "tikivn/open-api-docs"<open-api-docs@noreply.github.com&gt;; 
抄送: "亲 耐 の、硪"<513416101@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [tikivn/open-api-docs] Interface transfer parameters of the problem (#189)





 
hi @chengbirght you're using API key or using Oauth2 access token?

**Comment by vietcaominh** [comment]
Thanks, so I will close it then!
