### ISSUE TITLE
Order's response is not display on Seller Center.

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#190]
ID: 936073906. This order's response not display on Seller Center.Please check for me. Thanks!
Can you not response that orders?

**Comment by vietcaominh** [comment]
hi @Hungpx what is the query URL you are using that still got this order?

**Comment by Hungpx** [comment]
> hi @Hungpx what is the query URL you are using that still got this order?
================================================>
This Url: https://api.tiki.vn/integration/v1/orders

**Comment by vietcaominh** [comment]
hi @Hungpx . The problem because open API not filter orders haven't reached the queueing state but SC does. We're fixing the problem in this sprint. We will let you know in 2 weeks.

**Comment by hoai-dam** [comment]
Hi @Hungpx,

We understand the issue you reported.

As our policy for not displaying "mediate" orders in our order processing flow, then there are some orders returned from Open API are invisible on Seller Center. In our newest release of API for Order Listing, those mediate orders are not returned any more. 

Thanks,
Hoai Dam
