### ISSUE TITLE
[Datamart] Can not create ODF Product

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#200]
Env: production api
Shop name: Datamart

Request: 
`/integration/v1/requests`
```
{
  "attributes": {
    "brand": "OEM",
    "brand_origin": "Việt Nam",
    "bulky": "0",
    "device_brand": "Apple",
    "device_compatibility": "Iphone 5",
    "is_warranty_applied": 0,
    "is_warranty_forever": 0,
    "origin": "Việt Nam",
    "product_top_features": "Ốp silicon vali hình ảnh siêu xinh dành cho dòng máy iphone 5 \nChất silicon dày dặn ôm máy , bảo vệ máy cực tốt \nChống bám vân tay - Chống xước",
    "require_expiry_date": "0"
  },
  "category_id": 28574,
  "description": "Ốp silicon vali hình ảnh siêu xinh dành cho dòng máy iphone 5 \nChất silicon dày dặn ôm máy , bảo vệ máy cực tốt \nChống bám vân tay - Chống xước",
  "image": "https://cdn.tgdd.vn/Products/Images/60/87587/op-lung-iphone-5-5s-nhua-hinh-thu-osmia-dau-lau-xa-org-2.jpg",
  "images": [
    "https://cdn.tgdd.vn/Products/Images/60/87587/op-lung-iphone-5-5s-nhua-hinh-thu-osmia-dau-lau-xa-org-3.jpg",
    "https://cdn.tgdd.vn/Products/Images/60/87587/op-lung-iphone-5-5s-nhua-hinh-thu-osmia-dau-lau-xa-org-4.jpg",
    "https://cdn.tgdd.vn/Products/Images/60/87587/op-lung-iphone-5-5s-nhua-hinh-thu-osmia-dau-lau-xa-org-6.jpg"
  ],
  "market_price": 80000,
  "name": "Ốp lưng dành cho Iphone 5, Iphone 5S",
  "option_attributes": [],
  "variants": [
    {
      "inventory_type": "backorder",
      "market_price": 80000,
      "price": 70000,
      "quantity": 1,
      "sku": "caseip5",
      "supplier": 14446
    }
  ]
}
```

Response:
`{"track_id":"68e303c8a6fe4206bc29250dd5f2d0a7","state":"rejected","reason":"Chưa đăng kí hình thức vận hành này."}`

**Comment by vietcaominh** [comment]
@ducanhnguyen19 Please help check!

**Comment by ducanhnguyen19** [comment]
when you create any product , you have to register `inventory_type` with TIKI at first

**Comment by trongnhann** [comment]
bro @ducanhnguyen19, i checked in sellercenter: 
![image](https://user-images.githubusercontent.com/44260462/84340785-adc06780-abcb-11ea-9c3b-00a2a9714775.png)

Then I strive to create with "drop_ship", TIKI send response: 
 `{"errors":["variants inventory_type error => Seller haven't registered inventory_type = drop_ship ,please choose 1 over here : [instock, backorder]"]}`
and when I sent create product request with "backorder", I received 
`{"track_id":"94da2e151db4460fa4a82df341aa7409","state":"rejected","reason":"Chưa đăng kí hình thức vận hành này."}`

**Comment by ducanhnguyen19** [comment]
okay , we find another bug about this inventory_type , we are fixing it , we will tell your once it ready , thank you for reporting

**Comment by ducanhnguyen19** [comment]
the bug is fixed , you can try again @trongnhann

**Comment by trongnhann** [comment]
it worked perfectly, tks @ducanhnguyen19
