### ISSUE TITLE
Không test trên môi trường sandbox được

### ISSUE THREAD

**Issue by shippodeveloper** [tikivn/open-api-docs#201]
Hi Tiki,

Tôi đăng kí account seller sandbox theo hướng dẫn này: https://open.tiki.vn/#api-key
Tuy nhiên khi đăng nhập thì gặp lỗi này:
<img width="958" alt="Screen Shot 2020-05-26 at 10 36 22" src="https://user-images.githubusercontent.com/39092481/82858032-ec53f200-9f3c-11ea-836f-4a914e3e2561.png">

Làm sao để tôi có thể test tích hợp api với tiki ?

**Comment by vietcaominh** [comment]
@shippodeveloper could you send me your login credentials to this email: viet.cao@tiki.vn

**Comment by vietcaominh** [comment]
Thanks
