### ISSUE TITLE
[Datamart] API getting products & orders return randomly "time format incorrect" false errors

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#205]
ENV: PROD
API: "/integration/v1/products" & "/integration/v1/orders"
REQUEST: 
```
GET /integration/v1/products?created_from_date=2020-05-15+08%3A47%3A13&created_to_date=2020-05-29+09%3A57%3A13&limit=50&page=13 HTTP/1.1
Host: api.tiki.vn
Authorization: Bearer ...xyz...
Content-Type: application/json
```

RESPONSE:
```
Downloader - DUMP RESPONSE  
HTTP/2.0 400 Bad Request
Connection: close
Alt-Svc: h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Type: application/json;charset=UTF-8
Date: Fri, 29 May 2020 02:57:42 GMT
Via: kong/1.4.3, 1.1 google
X-Correlation-Id: a0980fad-c51a-4ba2-bf77-354e058e973a
X-Kong-Proxy-Latency: 0
X-Kong-Upstream-Latency: 3

{"errors":["time format incorrect: 2020-05-15 08:47:13 => yyyy-MM-dd HH:mm:ss"]}

```

REQUEST: 
```
GET /integration/v1/orders?created_from_date=2020-05-15+08%3A45%3A08&created_to_date=2020-05-29+09%3A55%3A14&limit=20&page=33&status=all HTTP/1.1
Host: api.tiki.vn
Authorization: Bearer ...xyz...
Content-Type: application/json

```

RESPONSE:

```
HTTP/2.0 400 Bad Request
Connection: close
Alt-Svc: h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Type: application/json;charset=UTF-8
Date: Fri, 29 May 2020 02:57:31 GMT
Via: kong/1.4.3, 1.1 google
X-Correlation-Id: 70660884-c5fb-42f6-ad1b-d37d29e93598
X-Kong-Proxy-Latency: 1
X-Kong-Upstream-Latency: 8

{"errors":["time format incorrect: 2020-05-15 08:45:08 => yyyy-MM-dd HH:mm:ss"]}
```

However, when I call them again after few hours with same params, the response is normal with fully data.
`{"data":[{"product_id":54839798,"sku":"6390673859345","name":"Loa Bluetooth Đa Năng Yayusi S2 kiêm đồng hồ , đo nhiệt độ, có khe cắm thẻ nhớ và USB - Xám","master_id":11885739,"master_sku":"4717374882632","super_id":11885732,"super_sku":"8193361177442","active":0,"original_sku":"dc2101.XAM","type":"simple","entity_type":"seller_simple","price":370000,"market_price":550000,"created_at":"2020-05-15 16:18:27","updated_at":"2020-05-18 16:19:30","thumbnail":"https://salt.tikicdn.com/cache/280x280/ts/product/9d/16/5a/e7f2650ef60c8e0551af73f2631cba05.jpg","categories":[{"id":1805,"name":"Loa nghe nhạc","url_key":"loa-nghe-nhac","is_primary":false},{"id":1815,"name":"Thiết Bị Số - Phụ Kiện Số","url_key":"thiet-bi-kts-phu-kien-so","is_primary":false},{"id":2324,"name":"Loa Bluetooth","url_key":"loa-bluetooth","is_primary":true},{"id":8215,"name":"Thiết bị âm thanh và phụ kiện","url_key":"thiet-bi-am-thanh-va-phu-kien","is_primary":false},{"id":32604,"name":"LOA05","url_key":"loa05","is_primary":false}]},{"product_id":54839796,"sku":"8775778614392","name":"Chuột Dây Game Thủ Cao Cấp Có Đèn Led - Đen","master_id":16209109,"master_sku":"6390868643827","super_id":16209106,"super_sku":"4180575499266","active":1,"original_sku":"DC2220.DEN","type":"simple","entity_type":"seller_simple","price":98999,"market_price":200000,"created_at":"2020-05-15 16:18:26","updated_at":"2020-05-27 15:11:43","thumbnail":"https://salt.tikicdn.com/cache/280x280/ts/product/36/e9/6b/d9eebb7568cb054e6c9aa5232746a257.jpg","categories":[{"id":1815,"name":"Thiết Bị Số - Phụ Kiện Số","url_key":"thiet-bi-kts-phu-kien-so","is_primary":false},{"id":3428,"name":"Chuột Chơi Game","url_key":"chuot-choi-game","is_primary":true},{"id":28670,"name":"Phụ kiện máy tính và Laptop","url_key":"phu-kien-may-tinh-va-laptop","is_primary":false},{"id":28692,"name":"Phụ Kiện Phím Chuột Chơi Game","url_key":"phu-kien-phim-chuot-choi-game","is_primary":false},{"id":35056,"name":"chuot ban phim 3p xem tat ca","url_key":"chuot-ban-phim-3p-xem-tat-ca","is_primary":false},{"id":45870,"name":"EA Seller","url_key":"ea-seller","is_primary":false}]},{"product_id":54839795,"sku":"1327728881209","name": ...`

**Comment by vietcaominh** [comment]
@ducanhnguyen19 please help with this question!
