### ISSUE TITLE
Product inventory issues

### ISSUE THREAD

**Issue by chengbirght** [tikivn/open-api-docs#206]
Hi
From which interface is the inventory of your products obtained, or from which interface is the inventory of the products synchronized?
thanks

**Comment by vietcaominh** [comment]
hi @chengbirght , I'm not really understanding your problem. Can you describe more details

**Comment by chengbirght** [comment]
I mean I got product information, but I don’t understand your sku mechanism, is it a product one sku, or a product corresponding to multiple sku?
I look forward to your reply as soon as possible, thank you

**Comment by vietcaominh** [comment]
hi @chengbirght . For product details. One SKU will assign to one product. There will be one SKU like this
`"sku": "4014999161303"`
Other SKU field like master_sku, super_sku I think you don't have to care about them

**Comment by chengbirght** [comment]
ok，thank you

**Comment by vietcaominh** [comment]
Thanks, if you got clear with it will close the ticket then!
