### ISSUE TITLE
[Datamart] API getting order return wrong "total_price_after_discount"

### ISSUE THREAD

**Issue by trongnhann** [tikivn/open-api-docs#207]
**ENV**: PROD
**API**: "/integration/v1/orders/791252252"
**REQUEST**:
``GET /integration/v1/orders/791252252 HTTP/1.1
Host: api.tiki.vn
Authorization: Bearer xxxxxxx
Content-Type: application/json
``

**RESPONSE**: 
In this response: **"total_price_before_discount": 332489** and **"total_price_after_discount": 332489** while "item" only has one element and it's **"price": 69000, "qty": 1 and "fee_total": 15690**. So, Did something wrong?
```{
  "order_code": "791252252",
  "coupon_code": null,
  "status": "seller_confirmed",
  "total_price_before_discount": 332489,
  "total_price_after_discount": 332489,
  "created_at": "2020-06-03 07:47:47",
  "updated_at": "2020-06-03 07:47:47",
  "purchased_at": "2020-06-03 07:48:37",
  "fulfillment_type": "tiki_delivery",
  "note": "",
  "deliveryConfirmed": "",
  "delivery_confirmed_at": "",
  "is_rma": 0,
  "tax": {
    "code": null,
    "name": null,
    "address": null
  },
  "discount": {
    "discount_amount": 0,
    "discount_coupon": 0,
    "discount_tiki_point": 0
  },
  "shipping": {
    "name": "xxxxx",
    "street": "xxxxx",
    "ward": "xxxxx",
    "city": "xxxxx",
    "region": "xxxxx",
    "country": "xxxxx",
    "phone": "",
    "email": "",
    "estimate_description": "Dự kiến giao hàng vào Thứ hai, 08/06/2020",
    "shipping_fee": 0
  },
  "items": [
    {
      "id": 148944798,
      "product_id": 8076874,
      "product_name": "Dụng cụ chống cận thị cho bé tiện dụng HLBB0092",
      "sku": "4444480398428",
      "original_sku": "DCCAN",
      "qty": 1,
      "price": 69000,
      "confirmation_status": "seller_confirmed",
      "confirmed_at": "2020-06-03 08:21:03",
      "must_confirmed_before_at": "2020-06-03 12:00:00",
      "warehouse_code": "hn4",
      "inventory_type": "backorder",
      "serial_number": [],
      "imei": [],
      "discount": {
        "discount_amount": 0,
        "discount_coupon": 0,
        "discount_tiki_point": 0
      },
      "fees": [
        {
          "fee_type_id": 1,
          "name": "Chiết khấu",
          "key": "percent_per_item_sales_value",
          "fee_total_amount": 690
        },
        {
          "fee_type_id": 2,
          "name": "Phí thanh toán",
          "key": "payment_processing_fee",
          "fee_total_amount": 0
        },
        {
          "fee_type_id": 23,
          "name": "Phí cố định",
          "key": "base_fee",
          "fee_total_amount": 10000
        },
        {
          "fee_type_id": 24,
          "name": "Phí lấy hàng",
          "key": "pickup_fee",
          "fee_total_amount": 5000
        }
      ],
      "fee_total": 15690,
      "seller_id": 6387
    }
  ],
  "payment": {
    "payment_method": "cybersource",
    "updated_at": "2020-06-03 07:47:47",
    "description": "Thanh toán bằng thẻ quốc Tế Visa, Master, JCB"
  },
  "handling_fee": 0,
  "collectable_total_price": 0
}```

**Comment by vietcaominh** [comment]
@hoai-dam please update it when it get resolved when updating to new listing API

**Comment by trongnhann** [comment]
bro @hoai-dam,  what happened to this case? how i can fix it?

**Comment by hoai-dam** [comment]
Hello @trongnhann , thank you for the issue. 

Yes, it's wrongly computed, we are fixing the issue!

FYI.

**Comment by trongnhann** [comment]
> Hello @trongnhann , thank you for the issue.
> 
> Yes, it's wrongly computed, we are fixing the issue!
> 
> FYI.

I just checked, and it's still wrong

**Comment by trongnhann** [comment]
Hello @hoai-dam, 
Have you got any news?
I am still stuck in there !!! :))

**Comment by socrec** [comment]
@hoai-dam hi guys, just checking, do we have an ETA for this? We're facing this issue and our client is asking for an ETA
Thanks for your time

**Comment by hoatv214** [comment]
Hi @hoai-dam , it is nearly 2 months now. Any updates?

**Comment by hoai-dam** [comment]
Hello @socrec @trongnhann @hoatv214 ,
We have just released [Order API V2](https://open.tiki.vn/#order-api-v2) that fix this `total_price_after_discount` problem. We have focused on rebuilding the invoice (for customer) and statement (for seller) parts of the order.

`total_price_before_discount` is now `[Order Invoice](https://open.tiki.vn/#order-invoice).subtotal`
`total_price_after_discount` is now `[Order Invoice](https://open.tiki.vn/#order-invoice).grand_total`

**Comment by socrec** [comment]
@hoai-dam really appreciate it, fantastic job!
But one question though, how about `total_price_after_discount` value in [Order API V1](https://open.tiki.vn/#api-get-order-details) ? Has it been corrected yet?

**Comment by hoai-dam** [comment]
@socrec We stopped working on Order API V1 to focus on V2, then `total_price_after_discount` is not fixed in V1. If you already have seller orders in your system then please switch to V2 ;)

**Comment by socrec** [comment]
@hoai-dam thanks a lot 👍
