### ISSUE TITLE
Update product sku information error

### ISSUE THREAD

**Issue by chengbirght** [tikivn/open-api-docs#209]
https://api.tiki.vn/integration/v1/products/updateSku
Update the inventory through this interface and return:
{
     "errors": [
         "Can't read http message, please check your request"
     ]
}

**Comment by ducanhnguyen19** [comment]
please recheck your request body , maybe some of your fields is wrong format

**Comment by chengbirght** [comment]
header:
Authorization: Bearer GpOOfskxkSLqg-2Mt4vPCqHyZlG-a_UkrGsl-2ZtRqo.f0yx_jNV4SBf1Nm7orQqQgHvqhf7dvlDic1HQ4w9EKc
Authorization-Provider: ICP-HYDRA

body:
product_id: 54779116
quantity: 3

**Comment by chengbirght** [comment]
{"errors":["Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported"]}

**Comment by ducanhnguyen19** [comment]
we only accept data in JSON format dude, we do not use form in request, please correct it and send again :D
