### ISSUE TITLE
Could not resolve: products (Domain name not found)

### ISSUE THREAD

**Issue by chengbirght** [tikivn/open-api-docs#210]
The products I got through the interface https://api.tiki.vn/integration/v1/products, changed the inventory, and update the inventory through the interface https://api.tiki.vn/integration/v1/products/updateSku reported an error

error:Could not resolve: products (Domain name not found)

**Comment by ducanhnguyen19** [comment]
can you give me full curl ? the system is working normally , please check your request carefully

**Comment by chengbirght** [comment]
{"product_id":"54779076","original_sku":"4901008307855","quantity":"3"}
method: post

**Comment by chengbirght** [comment]
hello，Does this post request header file also need to be made in the form of json?

**Comment by ducanhnguyen19** [comment]
sorry for inconvenient , your request body have to in json format

**Comment by ducanhnguyen19** [comment]
Content-Type : application/json
try to put it into your request header

**Comment by chengbirght** [comment]
I have solved it, thanks
