### ISSUE TITLE
Product request rejected due to product media is empty

### ISSUE THREAD

**Issue by kabuky** [tikivn/open-api-docs#211]
Hi Tiki,

I am creating a new product request with both fields image and images populated with data.

Upon new product request created, it is immediately rejected due to product media empty.

[{\"track_id\":\"d97f9f6c68764ac58559ed8c47f73e80\",\"state\":\"rejected\",\"reason\":\"product media is empty\"},{\"track_id\":\"f5b5cce6e1e64be69a5c19598a66810e\",\"state\":\"rejected\",\"reason\":\"product media is empty\"},{\"track_id\":\"b73f6c945c434559a2afd4fdefb226a6\",\"state\":\"rejected\",\"reason\":\"product media is empty\"}]

Please help to check. Thank you

**Comment by vietcaominh** [comment]
Hi @kabuky , Sorry for the late reply. @ducanhnguyen19 please help check it

**Comment by ducanhnguyen19** [comment]
invalid size | 324x500 , tiki accept only image size from 500x500 px , please resize your image at first

**Comment by ducanhnguyen19** [comment]
we will reformat response to help seller easier to understand

**Comment by ducanhnguyen19** [comment]
> I got another error when trying to create a product - reason: "Không có quyền đăng bán các sản phẩm vận chuyển từ nước ngoài."
> 
> FYI, I am a cross-border seller

about this error, please contact to TIKI supporter to help you register new inventory type
