### ISSUE TITLE
Login using Tiki APi

### ISSUE THREAD

**Issue by julianoo32** [tikivn/open-api-docs#212]
I have read TIKI open api documentation but i haven't seen API for login as a user or its relevant example. I hope i can get reply soon. Thanks

**Comment by vietcaominh** [comment]
Hi @julianoo32 . We will create an account for you
@hoai-dam please help with that

**Comment by hoai-dam** [comment]
Hello @julianoo32 , I'm very sorry for replying lately.

Could you please provide use your email then we can start getting more information about your request?

Thanks for your concern on our Open API.
