### ISSUE TITLE
Login API issue 

### ISSUE THREAD

**Issue by gitvishwajitk** [tikivn/open-api-docs#214]
1. I have read TIKI open api documentation but i haven't seen API for login as a user or its relevant 
    example. 
2. Where i Get Client id / credentials ?  

I hope i can get reply soon 
Thanks

**Comment by vietcaominh** [comment]
hi @gitvishwajitk . We will help you create account.
@hoai-dam please help this

**Comment by longlevan9x** [comment]
Hi @vietcaominh. 
I have the same problem. You can help me create account.
Thanks

**Comment by gitvishwajitk** [comment]
@hoai-dam please provide update on this

**Comment by hoai-dam** [comment]
Hello @gitvishwajitk and @longlevan9x , I'm very sorry for replying lately.

Could you please provide use your email then we can start getting more information about your request?

Thanks for your concern on our Open API.

**Comment by longlevan9x** [comment]
@hoai-dam 
My email: longlevan@vccorp.vn
Thanks.

**Comment by gitvishwajitk** [comment]
@longlevan9x     email : integrations@anchanto.com
