### ISSUE TITLE
[Crossborder]

### ISSUE THREAD

**Issue by chrkyrong** [tikivn/open-api-docs#218]
I have post parameter 'tiki-api', but why access to https://api.tiki.vn/integration/v1/orders , returns this error
example.
{
    "errors": [
        "sorry, create mock order endpoint only available on sandbox"
    ]
}

**Comment by vietcaominh** [comment]
Hi @chrkyrong , The created mock order endpoint only avaiable on Sandbox for support testing integration. You should use the Sandbox base URL
POST: https://api-sandbox.tiki.vn/integration/v1/orders
