### ISSUE TITLE
/warehouses/tiki json response format

### ISSUE THREAD

**Issue by paragasu** [tikivn/open-api-docs#220]
I come across another issue with the /warehouses/tiki API call.
I got the following response with the result is returned under error array and
not the expected json format as documented in this doc https://open.tiki.vn/#get-tiki-warehouses.

Is this result is the same as in the production server?

```
{
	error: [{
		"name": "Hà Nội",
		"code": "hn"
	}, {
		"name": "Sài Gòn",
		"code": "sgn"
	}, {
		"name": "Cần Thơ",
		"code": "ct"
	}, {
		"name": "Đà Nẵng",
		"code": "dn"
	}, {
		"name": "Hải Phòng",
		"code": "hp"
	}, {
		"name": "Tân Sơn",
		"code": "ts"
	}, {
		"name": "Nha Trang",
		"code": "nt"
	}, {
		"name": "Vĩnh Lộc Mới",
		"code": "vln"
	}, {
		"name": "Buffer SGN",
		"code": "bfsgn"
	}, {
		"name": "Sai Gon 3",
		"code": "sgn3"
	}, {
		"name": "Hà Nội 4",
		"code": "hn4"
	}, {
		"name": "Ha Noi 5",
		"code": "hn5"
	}]
}
```

**Comment by vietcaominh** [comment]
@paragasu  hm that's weird. Can you send me the full curl you got this error to email viet.cao@tiki.vn

**Comment by paragasu** [comment]
I call this api endpoint `https://api-sandbox.tiki.vn/integration/v1/warehouses/tiki`

**Comment by vietcaominh** [comment]
hi @paragasu I know you're calling this endpoint. But I tested I got the same format as docs without result in errors array. So I think something weird around here.
That why can you send me the full curl to my email : viet.cao@tiki.vn
Something like below:
curl --location --request GET 'https://api-sandbox.tiki.vn/integration/v1/warehouses/tiki' \
--header 'tiki-api: xxxxxxx'

**Comment by paragasu** [comment]
hi @vietcaominh found the solutions, it has conflict with our typing

**Comment by vietcaominh** [comment]
Thanks
