### ISSUE TITLE
Product fetch 

### ISSUE THREAD

**Issue by gitvishwajitk** [tikivn/open-api-docs#221]
1. While fetch products How i identify the product is simple product or its configurable product ?
2. Can you please provide me description of following product fields 
           master_id
           master_sku
           super_id
           super_sku
           original_sku
           type
           entity_type
           version

**Comment by ducanhnguyen19** [comment]
In will reply you inline :D sorry for this inconvenient 

> While fetch products How i identify the product is simple product or its configurable product ?
when you get product detail you can see it's `option_attribute` if product have it so it is configurable product otherwise it is simple product
Note that : all of product you see is seller simple ( product with its option_attributes ) 
ex : iPhone Gold 64GB instead of iPhone

> Can you please provide me description of following product fields
Example : 
I have 1 super product : iPhone with 2 option_attribute is storage and color 
- super_id : product id of super product ( TIKI maganed it ) - iPhone
- super_sku : sku of super product ( TIKI managed it ) - iPhone
- master_id : product id of master product ( TIKI managed it ) - iPhone Gold 64GB
- master_sku : sku of master product ( TIKI managed it ) - iPhone Gold 64GB
- original_sku : sku from seller source ( seller managed it in seller product )
- type & entity type : type of product ( in this API it always is simple & seller_simple )
- version is belong to product request, not in product . It is the number update count of this product request 
Tell me if you still have any question @gitvishwajitk  thank you

**Comment by gitvishwajitk** [comment]
@ducanhnguyen19  Thanks for the reply .

Can you please provide  sample  response of configurable product ?

**Comment by ducanhnguyen19** [comment]
`{
"product_id": 23112234,
"sku": "2341234xxx",
"name": "Khẩu Trang Y Tế Xanh/Xám/Đen 4 Lớp Cao Cấp Hướng Dương (50C)",
"master_id": 2345345,
"master_sku": "xxx",
"super_id": 23452342,
"super_sku": "xxx",
"active": 0,
"original_sku": "456",
"type": "simple",
"entity_type": "seller_simple",
"price": 140000,
"market_price": 150000,
"created_at": "2020-05-18 14:00:21",
"updated_at": "2020-06-11 14:42:47",
"thumbnail": "https://salt.tikicdn.com/ts/product/0e/89/1f/09abcb394731c7418622f7234d870a1d.jpg",
"option_attributes": [
"Màu"
],
"attributes": {
"huong_dan_bao_quan": "<p>Bảo quản:</p>\n<p>- Bảo quản nôi khô ráo, thoáng mát.</p>\n<p>- Hạn sử dụng 3 năm kể từ ngày sản xuất</p>\n<p>- Ngày sản xuất in trên bao bì từng sản phẩm</p>",
"product_height": "10",
"brand_country": {
"id": 31786,
"value": "Việt Nam"
},
"small_image": "product/0e/89/1f/09abcb394731c7418622f7234d870a1d.jpg",
"thanh_phan": "<p>Thành phần:</p>\n<p>- Thanh nẹp mũi, 3 lớp vải không dệt, 1 lớp vải lọc kháng khuẩn 99%</p>",
"warranty_time_unit": {
"id": 592157,
"value": "Tháng"
},
"origin": {
"id": 778977,
"value": "viet nam"
},
"description": "<p>Thông tin sản phẩm:</p>\n<p>Khẩu trang y tế hướng dương là dòng khẩu trang cao cấp có 4 lớp, hộp có 50c.</p>\n<p>Thành phần:</p>\n<p>- Thanh nẹp mũi, 3 lớp vải không dệt, 1 lớp vải lọc kháng khuẩn 99%</p>\n<p>Công dụng:</p>\n<p>- Ngăn ngừa vi khuẩn, bệnh dịch lây lan qua đường hô hấp.</p>\n<p>- Lọc sạch bụi, khói xe, chống năng</p>\n<p>Bảo quản:</p>\n<p>- Bảo quản nôi khô ráo, thoáng mát.</p>\n<p>- Hạn sử dụng 3 năm kể từ ngày sản xuất</p>\n<p>- Ngày sản xuất in trên bao bì từng sản phẩm</p>\n<p>#khautrangyte #khautrangytexam #khautrang3lop #khautrangcaocap #khautranghuongduong #khautrangytehanoi #freeship #freeshiphanoi #khautrangyteden</p>",
"use_new_layout_lifestyle": 1,
"giftwrap": 1,
"huong_dan_su_dung": "<p>Công dụng:</p>\n<p>- Ngăn ngừa vi khuẩn, bệnh dịch lây lan qua đường hô hấp.</p>\n<p>- Lọc sạch bụi, khói xe, chống năng</p>",
"option1_label": "Màu",
"supplier": {
"id": 14446,
"value": "Marketplace"
},
"brand": {
"exclusive_seller_id": 0,
"id": 177831,
"is_document_required": 0,
"listdata_id": 177831,
"status": 1,
"thumbnail": "brand/0d/86/13/ebe1e0c197d6608afce12240ebe5ce4e.jpg",
"url_key": "thuong-hieu/huong-duong.html",
"value": "Hướng Dương"
},
"url_path": "khau-trang-y-te-xanh-xam-den-4-lop-cao-cap-huong-duong-50c-p54740498.html",
"image": "product/0e/89/1f/09abcb394731c7418622f7234d870a1d.jpg",
"thumbnail": "product/0e/89/1f/09abcb394731c7418622f7234d870a1d.jpg",
"support_cod": 1,
"visibility": 4,
"product_width": "15",
"rma_status": 1,
"url_key": "khau-trang-y-te-xanh-xam-den-4-lop-cao-cap-huong-duong-50c-p54740498",
"po_type": {
"id": 111350,
"value": "marketplace"
},
"is_free_gift": {
"id": 31828,
"value": "Không"
},
"unit": {
"id": 31564,
"value": "Hộp"
},
"name": "Khẩu Trang Y Tế Xanh/Xám/Đen 4 Lớp Cao Cấp Hướng Dương (50C)",
"product_weight_kg": "1",
"product_length": "20",
"quy_cach_dong_goi": "<p>1 hộp 50c</p>",
"product_top_features": "Thông tin sản phẩm:\nKhẩu trang y tế hướng dương là dòng khẩu trang cao cấp có 4 lớp, hộp có 50c.\nThành phần:\nThanh nẹp mũi, 3 lớp vải không dệt, 1 lớp vải lọc kháng khuẩn 99%\nCông dụng:\nNgăn ngừa vi khuẩn, bệnh dịch lây lan qua đường hô hấp.\nLọc sạch bụi, khói xe, chống năng\nBảo quản:\nBảo quản nôi khô ráo, thoáng mát.\nHạn sử dụng 3 năm kể từ ngày sản xuất\nNgày sản xuất in trên bao bì từng sản phẩm\nkhautrangyte #khautrangytexam #khautrang3lop #khautrangcaocap #khautranghuongduong #khautrangytehanoi #freeship #freeshiphanoi #khautrangyteden",
"status": 1
},
"images": [
{
"url": "https://salt.tikicdn.com/ts/product/0e/89/1f/09abcb394731c7418622f7234d870a1d.jpg",
"path": "product/0e/89/1f/09abcb394731c7418622f7234d870a1d.jpg",
"position": 0
}
],
"categories": [
{
"id": 1520,
"name": "Làm Đẹp - Sức Khỏe",
"url_key": "lam-dep-suc-khoe",
"is_primary": false
},
{
"id": 1594,
"name": "Chăm sóc cá nhân",
"url_key": "cham-soc-ca-nhan",
"is_primary": false
},
{
"id": 8176,
"name": "Sản phẩm chăm sóc cá nhân",
"url_key": "san-pham-cham-soc-ca-nhan",
"is_primary": false
},
{
"id": 8305,
"name": "Khẩu trang y tế",
"url_key": "khau-trang-y-te",
"is_primary": true
}
],
"inventory": {
"inventory_type": "backorder",
"fulfillment_type": "tiki_delivery",
"quantity": 500
}
}`

**Comment by ducanhnguyen19** [comment]
![image](https://user-images.githubusercontent.com/51348919/84625510-9a840380-af0d-11ea-9687-167acd4232d5.png)

> when you get product detail you can see it's option_attribute if product have it so it is configurable product otherwise it is simple product

**Comment by gitvishwajitk** [comment]
@ducanhnguyen19  Thanks for the reply .
so in product details if we get the option_Attributes then that product is configurable product . 

Now suppose we have one product i-phone & that product have variations(color, size etc) so as per tiki theory this is configurable product.   
So my question is where we get this variation details using product api??

**Comment by ducanhnguyen19** [comment]
![image](https://user-images.githubusercontent.com/51348919/84635002-ceb2f080-af1c-11ea-949b-5f4d2d8ee655.png)
in attrattribute we got `option1` & `option2` to display option attribute value , you can refer here

**Comment by gitvishwajitk** [comment]
sorry, but i have still some queries .
So this fields are comes with product details api ? 
can you please share full response of configurable product with an example ?
it will help to understand easily . 
Thanks & regards

**Comment by ducanhnguyen19** [comment]
you should create your own product to understand easily :D all info in product detail 
sku is indentity by TIKI generated
original sku is sku from your system , or any key you want to save this product

**Comment by gitvishwajitk** [comment]
oh... 👍  Thank you for your quick support.

**Comment by gitvishwajitk** [comment]
@ducanhnguyen19  I have created one product on tiki . can you please approve this product . 
![Screenshot 2020-06-17 at 6 16 16 PM](https://user-images.githubusercontent.com/54353122/84903220-73733080-b0cb-11ea-954a-dc86d2695e99.png)
