### ISSUE TITLE
Need clientID and secret for intergrate TIKI

### ISSUE THREAD

**Issue by hoangminh281** [tikivn/open-api-docs#222]
Hi team,

I want to integrate TIKI platform in my project, could you pls provide me client ID and secret for testing OAuth 2? Also, I created a request for a new product on the sandbox in the seller shop with email "minh.tran@mediastep.com". Can you accept my product request pls? My email is as above.

Thanks,

**Comment by vietcaominh** [comment]
hi @hoangminh281 . Please wait for us to create an account for you to use Oauth2.
So you used the api-key to create product request? I didn't see any product request belong to your account on Sandbox? Are you sure you create product request successfully

**Comment by hoangminh281** [comment]
hi @vietcaominh 

I used sandbox seller center to create a new product request and the ID of request is 1184853530629343017.

Thanks

**Comment by vietcaominh** [comment]
I see @hoangminh281 
You must use open API to create product request to get auto approve by our script. If you use Seller Center, it's not gonna auto approve

**Comment by thanhthinh95** [comment]
Hi @vietcaominh 
I am integrating Tiki into my system and am having problems getting client_id and client_sercet on the sandbox environment.
My registered email is "thinhdinhthanh@vccorp.vn"
Please help me and let me know what to do to get a valid client_id and client_sercet
