### ISSUE TITLE
Product is rejected by "is_warranty_applied"

### ISSUE THREAD

**Issue by hainguyen92** [tikivn/open-api-docs#224]
Hi, dev Tiki
Help me check for this case.
I created a product successfully on the sandbox environment with JSON below:
```
{
  "category_id": 21458,
  "name": "Hai test multiple variation",
  "description": "Hai test multiple variation Hai test multiple variation Hai test multiple variation Hai test multiple variation Hai test multiple variation",
  "market_price": 1,
  "image": "https://d8qbqtt58lzda.cloudfront.net/1522206494654.jpg",
  "images": [
    "https://dm4fv4ltmsvz0.cloudfront.net/1528792333718.jpg",
    "https://dm4fv4ltmsvz0.cloudfront.net/1589871855389.jpg"
  ],
  "attributes": {
    "brand": "Sony",
    "bulky": "0",
    "brand_origin": "Vietnam",
    "product_top_features": "Top",
    "included_accessories": "No",
    "vat": "0",
    "require_expiry_date": 0
  },
  "option_attributes": [
    "Color",
    "Storages"
  ],
  "variants": [
    {
      "sku": "cube-01",
      "market_price": 115000,
      "price": 110000,
      "quantity": 98,
      "option1": "Black",
      "option2": "64GB",
      "inventory_type": "instock",
      "image": "https://dm4fv4ltmsvz0.cloudfront.net/1589871856174.jpg",
      "images": [
        "https://dm4fv4ltmsvz0.cloudfront.net/1589871857255.jpg",
        "https://dm4fv4ltmsvz0.cloudfront.net/1589871858053.jpg"
      ]
    },
    {
      "sku": "cube-02",
      "market_price": 95000,
      "price": 93000,
      "quantity": 98,
      "option1": "White",
      "option2": "64GB",
      "inventory_type": "instock",
      "image": "https://dm4fv4ltmsvz0.cloudfront.net/1589871860420.jpg",
      "images": [
        "https://dm4fv4ltmsvz0.cloudfront.net/1589871862056.jpg",
        "https://dm4fv4ltmsvz0.cloudfront.net/1589871867769.jpg"
      ]
    }
  ]
}
```
But when I checked product status on tracking API. It's rejected by this message
```
{
    "track_id": "c2e88d353a644c0cb42501ea123b4eba",
    "state": "rejected",
    "reason": "is_warranty_applied: Thuộc tính yêu cầu không tồn tại"
}
```

And then I appended those attributes into JSON and create new requests for creating product. 
```
"is_warranty_applied": 0,
"is_warranty_forever": 0
```

But it's still rejected by the same message above.
Thanks

**Comment by vietcaominh** [comment]
@anhnguyen26 please help check it

**Comment by ducanhnguyen19** [comment]
sorry category & attribute in sandbox environment is messed up
you should try to create in production environment, don't be scared , your product won't be display directly
or you can try in "category_id": 47 in sandbox environment , we will create a new guide to test creating product in sandbox later , thank you :D

**Comment by hainguyen92** [comment]
@ducanhnguyen19 
Thanks for your support.
I will try on the production environment later. In the sandbox environment, I tried to create a product with category_id: 47. It's working and status change to "awaiting_approve"

```
{
    "track_id": "ac45760e607a420482a03ce73496f555",
    "state": "awaiting_approve",
    "reason": "",
    "request_id": "1186269505522206522"
}
```

My question is when the status will change to "approved". I need it approved to appear in the result of getting the latest product API (https://api-sandbox.tiki.vn/integration/v1/products). 
And can you approve it manually?

Thanks

**Comment by vietcaominh** [comment]
Hi @hainguyen92 
Normally in Sandbox we have a script to auto approved your product requests. But there is an internal problem with your product request payload, we're checking. Please stay tuned.

**Comment by hainguyen92** [comment]
Hi @vietcaominh 
Let me know when you found the solution.
Thanks

**Comment by vietcaominh** [comment]
hi @hainguyen92 the problem has been resolved.
Your product request have been approved. No you can continue to create more products, they will get auto aprrove on Sandbox.

**Comment by hainguyen92** [comment]
Hi @vietcaominh 
My product is approved and auto script approval is working.
I have another question about the product.
I created a product with a **configurable type**. But API gets the latest product (https://api-sandbox.tiki.vn/integration/v1/products) it separates product by variant (**simple type**). And variants have the same **super_id**.
Does your system have API get the super product detail by super_id? Because if return like the latest product API, my system needs to combine all variants to a super product.

**Comment by vietcaominh** [comment]
@ducanhnguyen19 please help with the question above.

**Comment by ducanhnguyen19** [comment]
Do you want to filter products by super_id/master_id to help you combine product easier ? 
super product is belong to TIKI content team so seller can't query it

**Comment by hainguyen92** [comment]
Hi @ducanhnguyen19 
Yes. Can you show me how to filter products by super_id/master_id?
Thanks

**Comment by ducanhnguyen19** [comment]
we will add this function to backlog , we will tell you once it finished , please wait for us :D

**Comment by hainguyen92** [comment]
Hi @ducanhnguyen19 
My account seller has already enabled all inventory types.
![image](https://user-images.githubusercontent.com/19581710/85092634-4e3e0980-b214-11ea-9643-65f3fe041028.png)
But I can't create a product with "inventory_type": "backorder".
This is the response from API
```
{
    "track_id": "66a442adb37244a8b764e028219b54db",
    "state": "rejected",
    "reason": "Chưa đăng kí hình thức vận hành này."
}
```
Help me check it.
Thanks

**Comment by ducanhnguyen19** [comment]
"inventory_type": "backorder" now is only available in production environment , you can test there, sorry about this inconvenient

**Comment by hainguyen92** [comment]
Hi @ducanhnguyen19 
Ok thanks. I will check it on production
