### ISSUE TITLE
A question about delivery

### ISSUE THREAD

**Issue by chengbirght** [tikivn/open-api-docs#226]
Hi，
Is there only an interface with updated status when shipping? How do logistics information reach tiki?

**Comment by vietcaominh** [comment]
Hi @chengbirght  There is an endpoint for you to update delivery status if the orders are delivery by you here https://open.tiki.vn/#api-update-delivery-status
That is where the logistics information from your end update to Tiki?
Is that solve your question?

**Comment by chengbirght** [comment]
I've seen that. Thank you
