### ISSUE TITLE
Help me about tiki developer account or something else

### ISSUE THREAD

**Issue by tnohtition** [tikivn/open-api-docs#227]
Hi tiki team,
I am working under a seller in your system, with the email thelifekit@onpoint.vn, could you give me the way/developer account/Client id something else to integrate with your API?

**Comment by vietcaominh** [comment]
@hoai-dam please help!

**Comment by hoai-dam** [comment]
hi @tnohtition,
I sent you an email on this issue could you please take a look at your inbox?
