### ISSUE TITLE
 The order list interface

### ISSUE THREAD

**Issue by chengbirght** [tikivn/open-api-docs#228]
For the order list interface, I requested data. The total number is only 3, but the total returned is 10

**Comment by chengbirght** [comment]
Hello，Ask the order interface, how many states does that status field have?
Now I get so many states, such as (ready_to_ship, queueing ,seller_ confirmed, seller_ canceled, complete , successful_ delivery).

I'm not sure if these are also status

(transferring_to_foreign_warehouses: Orders transferring to your foreign warehouses
has_come_to_foreign_warehouses: Orders has come to your foreign warehouses
rotating_to_vietnam: Orders rotating to vietnam
customs_clearance: Customs clearance processing
customs_clearance_complete: Customs clearance complete
item_arrived_in_vietnam: Orders arrived in vietnam
ready_for_delivery: Orders ready for delivery
on_delivery: Orders on delivery
successful_delivery: Orders successful delivery)

Thank you for your reply as soon as possible

**Comment by vietcaominh** [comment]
Hi @chengbirght 
The total on paging is 3 but you got 10 orders details?? Can you post the response payload you got here?

**Comment by vietcaominh** [comment]
They are also delivery status but only have for cross border but seller delivery mode.
It's a special mode of TIKI if you are not cross border and using seller delivery, you don't have to care about them.

**Comment by chengbirght** [comment]
This is the returned JSON package，Only three pieces of data are returned, but the total is 10

{
    "data":[
        {
            "order_code":"913166718",
            "coupon_code":null,
            "status":"seller_confirmed",
            "total_price_before_discount":345000,
            "total_price_after_discount":345000,
            "created_at":"2020-06-08 23:47:48",
            "updated_at":"2020-06-09 08:25:21",
            "purchased_at":"2020-06-08 23:48:17",
            "fulfillment_type":"cross_border",
            "note":"",
            "deliveryConfirmed":null,
            "delivery_confirmed_at":null,
            "is_rma":0,
            "tax":{
                "code":null,
                "name":null,
                "address":null
            },
            "discount":{
                "discount_amount":0,
                "discount_coupon":0,
                "discount_tiki_point":0
            },
            "shipping":{
                "name":"Vũ Anh Thư",
                "street":"Tòa nhà Empire Tower, 26-28 Hàm Nghi",
                "ward":"Phường Bến Nghé",
                "city":"Quận 1",
                "region":"Hồ Chí Minh",
                "country":"Việt Nam",
                "phone":"0988203730",
                "email":"",
                "estimate_description":"Dự kiến giao hàng vào Thứ Năm, 25/06/2020",
                "shipping_fee":0
            },
            "items":[
                {
                    "id":149605287,
                    "product_id":55171899,
                    "product_name":"Kose Clear Turn Moist Charge Mask 50pcs",
                    "sku":"9405219253321",
                    "original_sku":"4971710382884",
                    "qty":1,
                    "price":345000,
                    "confirmation_status":"seller_confirmed",
                    "confirmed_at":"2020-06-09 08:25:21",
                    "must_confirmed_before_at":"2020-06-09 12:00:00",
                    "warehouse_code":"hn4",
                    "inventory_type":"backorder",
                    "serial_number":[

                    ],
                    "imei":[

                    ],
                    "discount":{
                        "discount_amount":0,
                        "discount_coupon":0,
                        "discount_tiki_point":0
                    },
                    "fees":[
                        {
                            "fee_type_id":1,
                            "name":"Chiết khấu",
                            "key":"percent_per_item_sales_value",
                            "fee_total_amount":27600
                        },
                        {
                            "fee_type_id":2,
                            "name":"Phí thanh toán",
                            "key":"payment_processing_fee",
                            "fee_total_amount":6900
                        },
                        {
                            "fee_type_id":26,
                            "name":"Phí nhà thầu",
                            "key":"ict_tax_fee",
                            "fee_total_amount":2934
                        },
                        {
                            "fee_type_id":100000,
                            "name":null,
                            "key":null,
                            "fee_total_amount":20000
                        }
                    ],
                    "fee_total":-57434,
                    "seller_id":99095
                }
            ],
            "payment":{
                "payment_method":"cybersource",
                "updated_at":null,
                "description":"Thanh toán bằng thẻ quốc tế Visa, Master, JCB"
            },
            "handling_fee":0,
            "collectable_total_price":0
        },
        {
            "order_code":"770064388",
            "coupon_code":null,
            "status":"seller_confirmed",
            "total_price_before_discount":411000,
            "total_price_after_discount":411000,
            "created_at":"2020-06-07 19:44:10",
            "updated_at":"2020-06-08 10:38:38",
            "purchased_at":"2020-06-07 20:01:13",
            "fulfillment_type":"cross_border",
            "note":"",
            "deliveryConfirmed":null,
            "delivery_confirmed_at":null,
            "is_rma":0,
            "tax":{
                "code":null,
                "name":null,
                "address":null
            },
            "discount":{
                "discount_amount":0,
                "discount_coupon":0,
                "discount_tiki_point":0
            },
            "shipping":{
                "name":"Dương An",
                "street":"Sumikura, 18h Cộng Hòa, Phường 4, Tân Bình, Hồ Chí Minh",
                "ward":"Phường 04",
                "city":"Quận Tân Bình",
                "region":"Hồ Chí Minh",
                "country":"Việt Nam",
                "phone":"0933456632",
                "email":"",
                "estimate_description":"Dự kiến giao hàng vào Thứ Năm, 25/06/2020",
                "shipping_fee":0
            },
            "items":[
                {
                    "id":149459144,
                    "product_id":53448837,
                    "product_name":"Phấn tươi AGE 20's Essence Cover Pact - Bảng hồng #21 (14g x 2 lõi )",
                    "sku":"3746167606507",
                    "original_sku":"8801046306499",
                    "qty":1,
                    "price":411000,
                    "confirmation_status":"seller_confirmed",
                    "confirmed_at":"2020-06-08 10:38:38",
                    "must_confirmed_before_at":"2020-06-08 12:00:00",
                    "warehouse_code":"hn4",
                    "inventory_type":"backorder",
                    "serial_number":[

                    ],
                    "imei":[

                    ],
                    "discount":{
                        "discount_amount":0,
                        "discount_coupon":0,
                        "discount_tiki_point":0
                    },
                    "fees":[
                        {
                            "fee_type_id":1,
                            "name":"Chiết khấu",
                            "key":"percent_per_item_sales_value",
                            "fee_total_amount":32880
                        },
                        {
                            "fee_type_id":2,
                            "name":"Phí thanh toán",
                            "key":"payment_processing_fee",
                            "fee_total_amount":8220
                        },
                        {
                            "fee_type_id":26,
                            "name":"Phí nhà thầu",
                            "key":"ict_tax_fee",
                            "fee_total_amount":3534
                        },
                        {
                            "fee_type_id":100000,
                            "name":null,
                            "key":null,
                            "fee_total_amount":20000
                        }
                    ],
                    "fee_total":-64634,
                    "seller_id":99095
                }
            ],
            "payment":{
                "payment_method":"cybersource",
                "updated_at":null,
                "description":"Thanh toán bằng thẻ quốc tế Visa, Master, JCB"
            },
            "handling_fee":0,
            "collectable_total_price":0
        },
        {
            "order_code":"500229056",
            "coupon_code":null,
            "status":"ready_to_ship",
            "total_price_before_discount":582000,
            "total_price_after_discount":582000,
            "created_at":"2020-06-01 17:12:17",
            "updated_at":"2020-06-13 10:23:48",
            "purchased_at":"2020-06-01 17:13:50",
            "fulfillment_type":"cross_border",
            "note":"",
            "deliveryConfirmed":null,
            "delivery_confirmed_at":null,
            "is_rma":0,
            "tax":{
                "code":null,
                "name":null,
                "address":null
            },
            "discount":{
                "discount_amount":0,
                "discount_coupon":0,
                "discount_tiki_point":0
            },
            "shipping":{
                "name":"Đặng Thị Thúy Nhàn",
                "street":"134 Lê Duẫn",
                "ward":"Phường Mỹ Phú",
                "city":"Thành phố Cao Lãnh",
                "region":"Đồng Tháp",
                "country":"Việt Nam",
                "phone":"0963880446",
                "email":"",
                "estimate_description":"Dự kiến giao hàng vào Thứ Năm, 18/06/2020",
                "shipping_fee":0
            },
            "items":[
                {
                    "id":148780424,
                    "product_id":54635327,
                    "product_name":"Phấn Tươi AGE 20'S Essence Cover Pact Tone 21 Phiên Bản Giới Hạn 3 trong 1",
                    "sku":"5832345796011",
                    "original_sku":"8801046331163",
                    "qty":1,
                    "price":582000,
                    "confirmation_status":"confirmed",
                    "confirmed_at":"2020-06-02 10:00:06",
                    "must_confirmed_before_at":"2020-06-02 12:00:00",
                    "warehouse_code":"hn4",
                    "inventory_type":"backorder",
                    "serial_number":[

                    ],
                    "imei":[

                    ],
                    "discount":{
                        "discount_amount":0,
                        "discount_coupon":0,
                        "discount_tiki_point":0
                    },
                    "fees":[
                        {
                            "fee_type_id":1,
                            "name":"Chiết khấu",
                            "key":"percent_per_item_sales_value",
                            "fee_total_amount":46560
                        },
                        {
                            "fee_type_id":2,
                            "name":"Phí thanh toán",
                            "key":"payment_processing_fee",
                            "fee_total_amount":11640
                        },
                        {
                            "fee_type_id":26,
                            "name":"Phí nhà thầu",
                            "key":"ict_tax_fee",
                            "fee_total_amount":5088
                        },
                        {
                            "fee_type_id":100000,
                            "name":null,
                            "key":null,
                            "fee_total_amount":20000
                        }
                    ],
                    "fee_total":-83288,
                    "seller_id":99095
                }
            ],
            "payment":{
                "payment_method":"momo",
                "updated_at":null,
                "description":"Thanh toán bằng ví MoMo"
            },
            "handling_fee":0,
            "collectable_total_price":0
        }
    ],
    "paging":{
        "total":10,
        "per_page":20,
        "current_page":1,
        "last_page":1,
        "from":1,
        "to":10
    }
}

**Comment by chengbirght** [comment]
This is the returned JSON package，Only three pieces of data are returned, but the total is 10

{
    "data":[
        {
            "order_code":"913166718",
            "coupon_code":null,
            "status":"seller_confirmed",
            "total_price_before_discount":345000,
            "total_price_after_discount":345000,
            "created_at":"2020-06-08 23:47:48",
            "updated_at":"2020-06-09 08:25:21",
            "purchased_at":"2020-06-08 23:48:17",
            "fulfillment_type":"cross_border",
            "note":"",
            "deliveryConfirmed":null,
            "delivery_confirmed_at":null,
            "is_rma":0,
            "tax":{
                "code":null,
                "name":null,
                "address":null
            },
            "discount":{
                "discount_amount":0,
                "discount_coupon":0,
                "discount_tiki_point":0
            },
            "shipping":{
                "name":"Vũ Anh Thư",
                "street":"Tòa nhà Empire Tower, 26-28 Hàm Nghi",
                "ward":"Phường Bến Nghé",
                "city":"Quận 1",
                "region":"Hồ Chí Minh",
                "country":"Việt Nam",
                "phone":"0988203730",
                "email":"",
                "estimate_description":"Dự kiến giao hàng vào Thứ Năm, 25/06/2020",
                "shipping_fee":0
            },
            "items":[
                {
                    "id":149605287,
                    "product_id":55171899,
                    "product_name":"Kose Clear Turn Moist Charge Mask 50pcs",
                    "sku":"9405219253321",
                    "original_sku":"4971710382884",
                    "qty":1,
                    "price":345000,
                    "confirmation_status":"seller_confirmed",
                    "confirmed_at":"2020-06-09 08:25:21",
                    "must_confirmed_before_at":"2020-06-09 12:00:00",
                    "warehouse_code":"hn4",
                    "inventory_type":"backorder",
                    "serial_number":[

                    ],
                    "imei":[

                    ],
                    "discount":{
                        "discount_amount":0,
                        "discount_coupon":0,
                        "discount_tiki_point":0
                    },
                    "fees":[
                        {
                            "fee_type_id":1,
                            "name":"Chiết khấu",
                            "key":"percent_per_item_sales_value",
                            "fee_total_amount":27600
                        },
                        {
                            "fee_type_id":2,
                            "name":"Phí thanh toán",
                            "key":"payment_processing_fee",
                            "fee_total_amount":6900
                        },
                        {
                            "fee_type_id":26,
                            "name":"Phí nhà thầu",
                            "key":"ict_tax_fee",
                            "fee_total_amount":2934
                        },
                        {
                            "fee_type_id":100000,
                            "name":null,
                            "key":null,
                            "fee_total_amount":20000
                        }
                    ],
                    "fee_total":-57434,
                    "seller_id":99095
                }
            ],
            "payment":{
                "payment_method":"cybersource",
                "updated_at":null,
                "description":"Thanh toán bằng thẻ quốc tế Visa, Master, JCB"
            },
            "handling_fee":0,
            "collectable_total_price":0
        },
        {
            "order_code":"770064388",
            "coupon_code":null,
            "status":"seller_confirmed",
            "total_price_before_discount":411000,
            "total_price_after_discount":411000,
            "created_at":"2020-06-07 19:44:10",
            "updated_at":"2020-06-08 10:38:38",
            "purchased_at":"2020-06-07 20:01:13",
            "fulfillment_type":"cross_border",
            "note":"",
            "deliveryConfirmed":null,
            "delivery_confirmed_at":null,
            "is_rma":0,
            "tax":{
                "code":null,
                "name":null,
                "address":null
            },
            "discount":{
                "discount_amount":0,
                "discount_coupon":0,
                "discount_tiki_point":0
            },
            "shipping":{
                "name":"Dương An",
                "street":"Sumikura, 18h Cộng Hòa, Phường 4, Tân Bình, Hồ Chí Minh",
                "ward":"Phường 04",
                "city":"Quận Tân Bình",
                "region":"Hồ Chí Minh",
                "country":"Việt Nam",
                "phone":"0933456632",
                "email":"",
                "estimate_description":"Dự kiến giao hàng vào Thứ Năm, 25/06/2020",
                "shipping_fee":0
            },
            "items":[
                {
                    "id":149459144,
                    "product_id":53448837,
                    "product_name":"Phấn tươi AGE 20's Essence Cover Pact - Bảng hồng #21 (14g x 2 lõi )",
                    "sku":"3746167606507",
                    "original_sku":"8801046306499",
                    "qty":1,
                    "price":411000,
                    "confirmation_status":"seller_confirmed",
                    "confirmed_at":"2020-06-08 10:38:38",
                    "must_confirmed_before_at":"2020-06-08 12:00:00",
                    "warehouse_code":"hn4",
                    "inventory_type":"backorder",
                    "serial_number":[

                    ],
                    "imei":[

                    ],
                    "discount":{
                        "discount_amount":0,
                        "discount_coupon":0,
                        "discount_tiki_point":0
                    },
                    "fees":[
                        {
                            "fee_type_id":1,
                            "name":"Chiết khấu",
                            "key":"percent_per_item_sales_value",
                            "fee_total_amount":32880
                        },
                        {
                            "fee_type_id":2,
                            "name":"Phí thanh toán",
                            "key":"payment_processing_fee",
                            "fee_total_amount":8220
                        },
                        {
                            "fee_type_id":26,
                            "name":"Phí nhà thầu",
                            "key":"ict_tax_fee",
                            "fee_total_amount":3534
                        },
                        {
                            "fee_type_id":100000,
                            "name":null,
                            "key":null,
                            "fee_total_amount":20000
                        }
                    ],
                    "fee_total":-64634,
                    "seller_id":99095
                }
            ],
            "payment":{
                "payment_method":"cybersource",
                "updated_at":null,
                "description":"Thanh toán bằng thẻ quốc tế Visa, Master, JCB"
            },
            "handling_fee":0,
            "collectable_total_price":0
        },
        {
            "order_code":"500229056",
            "coupon_code":null,
            "status":"ready_to_ship",
            "total_price_before_discount":582000,
            "total_price_after_discount":582000,
            "created_at":"2020-06-01 17:12:17",
            "updated_at":"2020-06-13 10:23:48",
            "purchased_at":"2020-06-01 17:13:50",
            "fulfillment_type":"cross_border",
            "note":"",
            "deliveryConfirmed":null,
            "delivery_confirmed_at":null,
            "is_rma":0,
            "tax":{
                "code":null,
                "name":null,
                "address":null
            },
            "discount":{
                "discount_amount":0,
                "discount_coupon":0,
                "discount_tiki_point":0
            },
            "shipping":{
                "name":"Đặng Thị Thúy Nhàn",
                "street":"134 Lê Duẫn",
                "ward":"Phường Mỹ Phú",
                "city":"Thành phố Cao Lãnh",
                "region":"Đồng Tháp",
                "country":"Việt Nam",
                "phone":"0963880446",
                "email":"",
                "estimate_description":"Dự kiến giao hàng vào Thứ Năm, 18/06/2020",
                "shipping_fee":0
            },
            "items":[
                {
                    "id":148780424,
                    "product_id":54635327,
                    "product_name":"Phấn Tươi AGE 20'S Essence Cover Pact Tone 21 Phiên Bản Giới Hạn 3 trong 1",
                    "sku":"5832345796011",
                    "original_sku":"8801046331163",
                    "qty":1,
                    "price":582000,
                    "confirmation_status":"confirmed",
                    "confirmed_at":"2020-06-02 10:00:06",
                    "must_confirmed_before_at":"2020-06-02 12:00:00",
                    "warehouse_code":"hn4",
                    "inventory_type":"backorder",
                    "serial_number":[

                    ],
                    "imei":[

                    ],
                    "discount":{
                        "discount_amount":0,
                        "discount_coupon":0,
                        "discount_tiki_point":0
                    },
                    "fees":[
                        {
                            "fee_type_id":1,
                            "name":"Chiết khấu",
                            "key":"percent_per_item_sales_value",
                            "fee_total_amount":46560
                        },
                        {
                            "fee_type_id":2,
                            "name":"Phí thanh toán",
                            "key":"payment_processing_fee",
                            "fee_total_amount":11640
                        },
                        {
                            "fee_type_id":26,
                            "name":"Phí nhà thầu",
                            "key":"ict_tax_fee",
                            "fee_total_amount":5088
                        },
                        {
                            "fee_type_id":100000,
                            "name":null,
                            "key":null,
                            "fee_total_amount":20000
                        }
                    ],
                    "fee_total":-83288,
                    "seller_id":99095
                }
            ],
            "payment":{
                "payment_method":"momo",
                "updated_at":null,
                "description":"Thanh toán bằng ví MoMo"
            },
            "handling_fee":0,
            "collectable_total_price":0
        }
    ],
    "paging":{
        "total":10,
        "per_page":20,
        "current_page":1,
        "last_page":1,
        "from":1,
        "to":10
    }
}

**Comment by vietcaominh** [comment]
With cross_border orders, there are two cases:
With normally case you don't have to update status, it will handle by Tiki. You can ignore this endpoint.
With using self delivery mode. You need to update above all the status bellow. This type is special and new case in Tiki. Please contract us on Github issue if you are cross_border seller but using self delivery mode to get support.
With seller_delivery orders. You only need to update status successful_delivery.

https://open.tiki.vn/#api-update-delivery-status
There is a note about that status here

**Comment by chengbirght** [comment]
My order is not self delivered, but it is (ready_to_ship ) this state, and (handover_to_partner) this status, because I didn't see it in the order list interface, so I was confused

**Comment by chengbirght** [comment]
This is the returned JSON package，Only three pieces of data are returned, but the total is 10.

{
    "data":[
        {
            "order_code":"913166718",
            "coupon_code":null,
            "status":"seller_confirmed",
            "total_price_before_discount":345000,
            "total_price_after_discount":345000,
            "created_at":"2020-06-08 23:47:48",
            "updated_at":"2020-06-09 08:25:21",
            "purchased_at":"2020-06-08 23:48:17",
            "fulfillment_type":"cross_border",
            "note":"",
            "deliveryConfirmed":null,
            "delivery_confirmed_at":null,
            "is_rma":0,
            "tax":{
                "code":null,
                "name":null,
                "address":null
            },
            "discount":{
                "discount_amount":0,
                "discount_coupon":0,
                "discount_tiki_point":0
            },
            
        },
        {
            "order_code":"770064388",
            "coupon_code":null,
            "status":"seller_confirmed",
            "total_price_before_discount":411000,
            "total_price_after_discount":411000,
            "created_at":"2020-06-07 19:44:10",
            "updated_at":"2020-06-08 10:38:38",
            "purchased_at":"2020-06-07 20:01:13",
            "fulfillment_type":"cross_border",
            "note":"",
            "deliveryConfirmed":null,
            "delivery_confirmed_at":null,
            "is_rma":0,
            "tax":{
                "code":null,
                "name":null,
                "address":null
            },
            "discount":{
                "discount_amount":0,
                "discount_coupon":0,
                "discount_tiki_point":0
            },
            
        },
        {
            "order_code":"500229056",
            "coupon_code":null,
            "status":"ready_to_ship",
            "total_price_before_discount":582000,
            "total_price_after_discount":582000,
            "created_at":"2020-06-01 17:12:17",
            "updated_at":"2020-06-13 10:23:48",
            "purchased_at":"2020-06-01 17:13:50",
            "fulfillment_type":"cross_border",
            "note":"",
            "deliveryConfirmed":null,
            "delivery_confirmed_at":null,
            "is_rma":0,
            "tax":{
                "code":null,
                "name":null,
                "address":null
            },
            "discount":{
                "discount_amount":0,
                "discount_coupon":0,
                "discount_tiki_point":0
            },
        
        }
    ],
    "paging":{
        "total":10,
        "per_page":20,
        "current_page":1,
        "last_page":1,
        "from":1,
        "to":10
    }
}

**Comment by vietcaominh** [comment]
> My order is not self delivered, but it is (ready_to_ship ) this state, and (handover_to_partner) this status, because I didn't see it in the order list interface, so I was confused

Oh sorry misunderstood your problem. You want to know the possible status your orders might have, right?
If your orders are cross border and not self-delivery. You can look at the diagram here to see possible status your order will have.
https://open.tiki.vn/#order-status

**Comment by hoai-dam** [comment]
Hello @chengbirght ,

We're very sorry for the inconvenience.

This is an error in our order processing flow to wrongly count orders  in each page. But no order is missing due to this. All Tiki-accepted orders are visible in the API response. We will try to work on this as soon as possible.

For now when you query orders at order listing endpoint, please use the `last_page` value to scan for all pages of orders that satisfy your filter.

FYI.

**Comment by chengbirght** [comment]
> > 我的订单不是自行发送的，而是（ready_to_ship）此状态和（handover_to_partner）此状态，因为我没有在订单列表界面中看到它，所以我很困惑
> 
> 哦，很抱歉误解了您的问题。您想知道订单的可能状态，对吗？
> 如果您的订单是跨境而不是自提。您可以在此处查看该图，以查看您的订单可能具有的状态。
> https://open.tiki.vn/#order-status

Okay, understand, thank you

**Comment by chengbirght** [comment]
> 你好@chengbirght，
> 
> 不便之处，敬请原谅。
> 
> 这是我们的订单处理流程中的错误，错误地计算了每个页面中的订单。但是，因此不会丢失任何订单。Tiki接受的所有订单均在API响应中可见。我们将尝试尽快进行处理。
> 
> 现在，当您在订单列表端点查询订单时，请使用该`last_page`值扫描满足您过滤条件的订单的所有页面。
> 
> 仅供参考。

Okay，thank you
