### ISSUE TITLE
OAuth2 API issue

### ISSUE THREAD

**Issue by thanhthinh95** [tikivn/open-api-docs#229]
Hi team!

I am having trouble getting the OAuth2.
Please help me fix this problem!

- Sandbox environment:
**Method**: GET
**Url**: https://api-sandbox.tiki.vn/integration/sc/oauth2/auth
**Params**: https://s.zamba.vn/?9cd05f4909448531#VvG6mobEG17XLBUNetZjVE8GXA/Ol9lb1WIGeLT9HrQ=
**Response**: https://s.zamba.vn/?5ae5fd1cf6dd55a5#YIyV+IEsvW9DOxyoj1xLI+/4Uhh3whVEMizFWOURwK0=

- Production environment:
**Method**: GET
**Url**: https://api.tiki.vn/integration/sc/oauth2/auth
**Params**: https://s.zamba.vn/?9cd05f4909448531#VvG6mobEG17XLBUNetZjVE8GXA/Ol9lb1WIGeLT9HrQ=
**Response**: https://s.zamba.vn/?c14838c8037dd175#aRDOR4zNvMv2S11fHVF1RI/7rgoNhKuViexb2AKXMsI=

**Comment by vietcaominh** [comment]
@hoai-dam ho
please help!
