### ISSUE TITLE
Order-detail API doesn't support pick-up warehouse

### ISSUE THREAD

**Issue by an6661** [tikivn/open-api-docs#230]
Hello Tiki Developer Team,

The Order-Detail API supports only Tiki warehouse but seller's pick-up warehouse. 

Can you support us by adding a field for seller's pick-up warehouse? This helps us map correctly the pick-up warehouses on Tiki to their actual warehouses.

Thank you.

**Comment by tuhucon** [comment]
@vietcaominh

**Comment by vietcaominh** [comment]
hi @an6661 , Yes right now the order details only have Tiki warehouse for order's items. So you want to have the seller's pickup warehouse for backorder items also? If that case we have to check more to know we can support it or not?

**Comment by an6661** [comment]
Yes, I think that would be needful. Based on the seller's actual business, seller may manage more than 1 warehouse. Tiki's partner application wouldn't acknowledge the handling-warehouse to assign, which makes the seller confused on managing orders.

**Comment by hoai-dam** [comment]
Hello @an6661 , right now we do not support **seller's pick-up warehouse**. When a seller wants to confirm their orders, we have 1 API to get all seller's warehouses, then they will select one of their warehouses as the input for the confirmation.

**Comment by an6661** [comment]
Yes. We did use that warehouse API to get warehouses, but we are currently not using the Order-Confirm API. So, the Sellers do not know which seller's warehouse are going to handle the orders. So, we need that **seller's pick-up warehouse** field. Is there any possible way Tiki supports that field on Order-detail API?

**Comment by vietcaominh** [comment]
Why you not using order confirm API. What you get order details for @an6661 ?

**Comment by an6661** [comment]
We use the details such as products, price, etc... Currently, we are not using the Order Confirm API. We planned using that API later.

**Comment by vietcaominh** [comment]
Hi @an6661 
Sorry, we missed your message!
Rightnow the order details API cannot support return seller pick up warehouse, So we're thinking of providing new API to return that by order code. If you really needed that information, please let us know here to push it faster
By the meantime, let me create a backlog for it

**Comment by hoai-dam** [comment]
Hello @an6661 
Take a look at this new API https://open.tiki.vn/#seller-inventory-api-v2 for getting list of pickup warehouses for confirmation.
Thank you for your information, we keep improving APIs and docs from your feedbacks.
