### ISSUE TITLE
Product Quantity Update Issue

### ISSUE THREAD

**Issue by kabuky** [tikivn/open-api-docs#231]
Hi Tiki,

I have a product A with a stock quantity of 7. Customer 1 places an order with 2 stocks. Customer 2 places another other with 3 stocks. I take 5 stocks in the warehouse to pack for these 2 orders and left with 2 in stock. I update Tiki product with 2 stocks available but the product page shows product is out of stock. Apparently I have to update stock quantity with 7 and Tiki will less 5 stocks in the 2 orders. However, the product API does not return how many stocks are currently reserved for active orders. Please advise how to update the correct stock quantity in this scenario.

Thanks

**Comment by tuhucon** [comment]
@ducanhnguyen19

**Comment by ducanhnguyen19** [comment]
please check your min sale quantity ( minimum quantity allow to purchase an order ) 
maybe its < your quantity so it display out of stock
If you don't mind please give us your seller name , product id and order code to debug easier

**Comment by kabuky** [comment]
Take this product as an example. Currently I have 3 confirmed orders for this product. I have packed and handed over to the courier and now left with 2 stocks in my warehouse. If I update stock quantity to 2, it becomes out of stock on Tiki. Apparently min sale quantity is not returned in the API call. 
<img width="1259" alt="Screenshot 2020-06-22 at 4 51 58 PM" src="https://user-images.githubusercontent.com/1215595/85268191-c7ee2580-b4a8-11ea-8770-59c0bc097b3b.png">

**Comment by ducanhnguyen19** [comment]
I checked your order history :
- you DO NOT need to update quantity if your product sold in TIKI , TIKI will reduce your quantity automatically
- if customer place an order , so your product quantity will be held, in your case you have 3 order / 3 product still not delivery , so your quantity can't be lower than 3 -> it will display as out of stock

=> we will return more information about quantity , number quantity is held in the future , thank you

**Comment by kabuky** [comment]
Well noted. Thank you for your support
