### ISSUE TITLE
I wanted to confirm my order, but it was cancelled

### ISSUE THREAD

**Issue by plken** [tikivn/open-api-docs#233]
questions : I wanted to confirm my order, but it was cancelled，Is my parameter wrong？

API：https://api.tiki.vn/integration/v1/orders/confirmItems

request:
{
  "order_code": "369909269",
  "warehouse_id": 146144,
  "item_ids": [150631323],
  "delivery_commitment_time": "2020-07-23 23:59:59",
  "tracking_number": "369909269"
}

response:
{
    "code": 200,
    "data": []
}

**Comment by vietcaominh** [comment]
hi @plken 
The order gets cancelled because the "item_ids": [150631323] is wrong
There is no item have this id on your order so the system thought you pass empty item_ids, that means to cancel the order.
Please use there "item_ids": [151101781] because it's the only item on your order

**Comment by vietcaominh** [comment]
We have reset the status of orders. You can try to confirm it now.
