### ISSUE TITLE
 Access token issue 

### ISSUE THREAD

**Issue by gitvishwajitk** [tikivn/open-api-docs#234]
Hi team , 

Facing error for generate access token via post man.   attached screenshot please check 
 
![Screenshot 2020-06-24 at 11 17 27 AM](https://user-images.githubusercontent.com/54353122/85505941-0dc3fe80-b60d-11ea-8aa6-546b54340a66.png)

**Comment by hoai-dam** [comment]
Hello @gitvishwajitk ,

We will check this now.
