### ISSUE TITLE
Fetch Configurable Product 

### ISSUE THREAD

**Issue by gitvishwajitk** [tikivn/open-api-docs#238]
Hi Team ,

I am facing some problem for fetch configurable product. Can you please help ? 

1. I have created one product with two variants 
    ```{
    "category_id": 47,
    "name": "Book Test",
    "description": "this is description is not a  not a description",
    "market_price": 100,
    "attributes": {
        "publication_date": null,
        "author": null,
        "brand": "MAC",
        "isbn13": null,
        "product_weight_kg": null,
        "product_imei": null,
        "bulky": 0,
        "require_expiry_datend": 0,
        "delivery_attributes" : 0,
        "rma_status": 0,
        "number_of_page": null,
        "product_length": null,
        "cost": null,
        "product_volume_metric": null,
        "unit": null,
        "edition": null,
        "dropship": null,
        "product_serial": null,
        "video": null,
        "listing_quality_score": null,
        "bao_sach_kho": null,
        "publisher_vn": null,
        "old_id": null,
        "cover" : null,
        "support_p24h_delivery": 1,
        "product_height": null,
        "dimensions": null,
        "isbn": null,
        "manufacturer": null,
        "product_top_features": null,
        "weight": null,
        "supplier": null,
        "product_width": null,
        "vat": 5,
        "require_expiry_date": 0
    },
    "image": "https://images-na.ssl-images-amazon.com/images/I/715uwlmCWsL.jpg",
    "images": [
        "https://images-na.ssl-images-amazon.com/images/I/6110JInm%2BBL.jpg"
    ],
     "option_attributes" : [
     	"color",
     	"size"
     ],
     "variants" : [
         {
                       "sku" : "TestBook1",
                       "price" : 90, 
                  "quantity" : 100,
                   "option1" : "Red",
                   "option2" : "xl",
            "inventory_type" : "instock",
                  "supplier" : null,
                     "image" : "https://images-na.ssl-images-amazon.com/images/I/715uwlmCWsLBY.jpg"
        },
        {
                       "sku" : "TestBook2",
                       "price" : 90, 
                  "quantity" : 100,
                   "option1" : "White",
                   "option2" : "xl",
            "inventory_type" : "instock",
                  "supplier" : null,
                     "image" : "https://images-na.ssl-images-amazon.com/images/I/715uwlmCWsLBY.jpg"
        }]}

 Then in the response of above created product i am receiving two product ids for that variations . 
 *with this two product how we different this product under same master skus ? (One master skus have two child )
 *Also there is missing two fields inventory_type & quantity 
 *Is there any way to get information of Master sku?

**Comment by vietcaominh** [comment]
@ducanhnguyen19 please help with this question?

**Comment by ducanhnguyen19** [comment]
- master sku is belong to TIKI , so you do not need to get its information
- inventory_type & quantity is visible in get product detail API 
- we will support filter product by master_id later, so you can fetch all product by its master_id

**Comment by gitvishwajitk** [comment]
Here is the product details response ... 

{
    "product_id": 2171329,
    "sku": "8565526589443",
    "name": "Book Test",
    "master_id": 2171328,
    "master_sku": "2719666034455",
    "super_id": 2171325,
    "super_sku": "8259248700032",
    "active": 0,
    "original_sku": "TestBook2",
    "type": "simple",
    "entity_type": "seller_simple",
    "price": 90,
    "market_price": 100,
    "created_at": "2020-06-26 01:46:21",
    "updated_at": "2020-06-26 01:46:22",
    "thumbnail": "https://uat.tikicdn.com/ts/null",
    "option_attributes": [
        "color",
        "size"
    ],
    "attributes": {
        "seller": {
            "store_id": 468,
            "listdata_id": 632329,
            "name": "Siêu Thị Nến",
            "vat_limit_supported": 0,
            "logo": "http://uat.tikicdn.com/ts/seller/dd/0d/90/54790cbb3740bc0d9cf02e39b41f45d0.png",
            "id": 1346,
            "slug": "dksh",
            "is_all_vat_supported": 0,
            "status": 1
        },
        "option1_label": "color",
        "visibility": 4,
        "support_p24h_delivery": 1,
        "name": "Book Test",
        "vat": {
            "id": 1461705,
            "value": "5"
        },
        "description": "<html>\n <head></head>\n <body>\n  this is description is not a not a description\n </body>\n</html>",
        "option1": "White",
        "option2": "xl",
        "option2_label": "size",
        "po_type": {
            "id": 111134,
            "value": "marketplace"
        }
    },
    "images": [
        {
            "url": "https://uat.tikicdn.com/ts/product/d6/d6/36/374b5d0af51b7e7b6b8cdbdd561746b8.jpg",
            "path": "product/d6/d6/36/374b5d0af51b7e7b6b8cdbdd561746b8.jpg",
            "position": 0
        },
        {
            "url": "https://uat.tikicdn.com/ts/product/fa/18/d1/37c2c52b87731f71c3c867dbe97ed2a6.jpg",
            "path": "product/fa/18/d1/37c2c52b87731f71c3c867dbe97ed2a6.jpg",
            "position": 1
        }
    ],
    "categories": [
        {
            "id": 2,
            "name": "Root yyy",
            "url_key": "default-category",
            "is_primary": false
        },
        {
            "id": 4,
            "name": "Economics",
            "url_key": "economics",
            "is_primary": false
        },
        {
            "id": 47,
            "name": "Accounting - Finance",
            "url_key": "accounting-finance",
            "is_primary": true
        },
        {
            "id": 320,
            "name": "English Books",
            "url_key": "sach-tieng-anh",
            "is_primary": false
        },
        {
            "id": 8322,
            "name": "Nhà Sách Tiki.vn",
            "url_key": "nha-sach-tiki",
            "is_primary": false
        }
    ]
}

**Comment by gitvishwajitk** [comment]
Any update on this ?

**Comment by ducanhnguyen19** [comment]
sorry about late but we have a lot of backlog already :( 
can you tell me why you need filter product by its master/super_id ? maybe we have other way to do it

**Comment by gitvishwajitk** [comment]
Hi @ducanhnguyen19 Actually i am looking for another query update .
 In order details api i am not inventory_type & quantity is visible in get product detail API.
I have provided the order details response . 
Please provide solution over this .. 
Thanks & Regards 
Vishwajit Kolekar

**Comment by gitvishwajitk** [comment]
@ducanhnguyen19 Any update on above issue ?

**Comment by ducanhnguyen19** [comment]
I don't really understand your question but I'm wondering why you need to see inventory_type & quantity of product in order detail 
- you do not need to update quantity of product when order delivery successfully , TIKI will reduce it by 1 automatically 
- in order detail if you want to see product detail you can merge them by yourself , TIKI open api is for all seller so we can't customize it too deep , sorry about that

**Comment by gitvishwajitk** [comment]
@ducanhnguyen19 Can you please see my first question ?
1. I never mentioned that i need inventory_type & quantity of product in order detail .
2. I have clearly mentioned that When i try to Hit "Product detail"  api then i m not receiving  inventory_type & quantity of product in response .

**Comment by gitvishwajitk** [comment]
![Screenshot 2020-07-10 at 10 20 24 AM](https://user-images.githubusercontent.com/54353122/87117752-fa649480-c296-11ea-94b4-e352734f0d2c.png)

FYI. 
I have clearly mentioned that  `Also there is missing two fields inventory_type & quantity`

**Comment by ducanhnguyen19** [comment]
ah sorry about missing context, sandbox environment have some incident so it can't reveal inventory_type & quantity
- you can try again with other product 
- try again after active product via end point /updateSku 
if they are still missing @vietcaominh will support you to check error why can't active product

**Comment by gitvishwajitk** [comment]
@ducanhnguyen19  Facing same issue . 
https://api-sandbox.tiki.vn/integration/v1/products/2171329
