### ISSUE TITLE
How to get my account detail of sandbox env ?

### ISSUE THREAD

**Issue by orangepchome** [tikivn/open-api-docs#239]
I have api key, but no account detail (email and password). Could you provide our account detail (email and password) of Sandbox env?
Please contact me by this email orange.cheng@staff.pchome.co.th

**Comment by vietcaominh** [comment]
hi @orangepchome o
How you get api key without email and password? Are you a seller or a kind of platform for sellers?
Are you on telegram Pchome x Tiki API with us?

**Comment by orangepchome** [comment]
Yes, I am on telegram Pchome x Tiki API with you.

**Comment by vietcaominh** [comment]
oh ok @orangepchome . Please send us your api key on telegram or send it to viet.cao@tiki.vn as it's credentials. We will get back or account details
