### ISSUE TITLE
New product approved but product page is not found

### ISSUE THREAD

**Issue by kabuky** [tikivn/open-api-docs#242]
Hi Tiki,

I am creating new product using API, the product is approved but when I check in the seller center its image link is broken and the product page is not found. Could you help to check what could have gone wrong?

<img width="746" alt="Screenshot 2020-07-02 at 9 42 41 AM" src="https://user-images.githubusercontent.com/1215595/86307096-7aac4980-bc48-11ea-9357-5cfcc25190fd.png">

<img width="1459" alt="Screenshot 2020-07-02 at 9 44 34 AM" src="https://user-images.githubusercontent.com/1215595/86307179-b2b38c80-bc48-11ea-865d-683a7504365d.png">

**Comment by kabuky** [comment]
Hello Tiki,

Any update on this issue? @ducanhnguyen19 

Thanks

**Comment by ducanhnguyen19** [comment]
we are fixing it ,we will response as soon as possible

**Comment by ducanhnguyen19** [comment]
its oke now , thank you for waiting
