### ISSUE TITLE
happen with 64.000SKU and affter update not change

### ISSUE THREAD

**Issue by nguyenphuthuybk** [tikivn/open-api-docs#243]
I have 2 question 
1. I have 64.000 SKU how can i download all in to my data local ? when max total is 10.000 ?
2. affter update product anything not change ?

**Comment by vietcaominh** [comment]
hi @nguyenphuthuybk 
- you want to retrieve all you SKU via open API?
- can you specify which payload and url you update product but it didn't change?

**Comment by nguyenphuthuybk** [comment]
1. yes, all SKU with information 
2. System resturn approved but didn't change

**Comment by vietcaominh** [comment]
Hi @nguyenphuthuybk 
1. why you need to do that?
2. Can you provide endpoint and payload of your request that got the problem?

**Comment by nguyenphuthuybk** [comment]
1. I have 64.400 sku , how can i download all it in to my data
2. How can i provide endpoint?

Vào 10:46, T.5, 9 Th7, 2020 vietcaominh <notifications@github.com> đã viết:

**Comment by ducanhnguyen19** [comment]
@nguyenphuthuybk you can filter by created_from_date
