### ISSUE TITLE
Order processing issue 

### ISSUE THREAD

**Issue by gitvishwajitk** [tikivn/open-api-docs#244]
Hi team 

[
![2bbd5e670ec20761466ee75be0dca909](https://user-images.githubusercontent.com/54353122/86537431-a8291980-bf0c-11ea-99c4-5bb76f28df9a.png)
](url)

1. Referring to the this flow diagram, we see in case of Tiki delivery, Dropship and Crossborder, seller can deliver either using 'Tiki Shipper' or 'Ship by logistic partner'.

How this can be identify?

Also, ship by logistic partner means Seller's 3rd party carrier that are not integrated with Tiki?

2. For order conform there is one required attribute i.e. "delivery commitment time" . Where i get this value in order API ?
Or we need to set manually ? Or Is it okay to use the 2 days as a standard delivery committed time for all the sellers? Will there be any impact for the seller if that value provided by default.

**Comment by tuhucon** [comment]
@hoai-dam hoai

**Comment by hoai-dam** [comment]
Hello @gitvishwajitk ,

We understand your confusion. Right now **delivery commitment time** is only needed to **confirm orders** with fulfillment type:
* Cross Border
* Seller Delivery 

Other fulfillment types does not require this parameter. We will update the document ASAP.

Thank you,

**Comment by gitvishwajitk** [comment]
@hoai-dam  Yes your right.
As per document it is right that **delivery commitment time**  is needed  & my question is 
```
Q. Where i get this value in order API ?
Or we need to set manually ? Or Is it okay to use the 2 days as a standard delivery committed time for all the sellers? Will there be any impact for the seller if that value provided by default.
```

**Comment by Swapnilgadewar** [comment]
Hello @hoai-dam, Following up on the concern on behalf of @gitvishwajitk .

Also, can you please help on the #1 asked in the initial thread.

**Comment by hoai-dam** [comment]
Hello @Swapnilgadewar @gitvishwajitk ,

You need to choose **delivery commitment time** manually. And make sure that:
* You will have delivered the product item to customer before this commitment time
* The commitment time cannot be in the past

FYI,

**Comment by gitvishwajitk** [comment]
@hoai-dam  Noted for **delivery commitment time** . 

Can you please help on this 
`Referring to the this flow diagram, we see in case of Tiki delivery, Dropship and Crossborder, seller can deliver either using
 ' Tiki Shipper' or _'Ship by logistic partner'_.
How this can be identify?
Also, ship by logistic partner means Seller's 3rd party carrier that are not integrated with Tiki?`

**Comment by Swapnilgadewar** [comment]
Hello @hoai-dam ,

Following up on the order related query?

**Comment by hoai-dam** [comment]
@gitvishwajitk 
Whatever the shipping partner, from this point you don't need to care about which partner. Because the in these fulfillment types, delivery is done by Tiki and Tiki's partner, not `Seller's 3rd party carrier that are not integrated with Tiki?` ;)

FYI.
