### ISSUE TITLE
I want to complain about a business ID that has been registered by someone else. I can contact any phone number or email.

### ISSUE THREAD

**Issue by longlevan9x** [tikivn/open-api-docs#246]
Hi All!
I want to complain about a business ID that has been registered by someone else. I can contact any phone number or email.
Thanks!

**Comment by vietcaominh** [comment]
hi @longlevan9x 
You can contact here for problems related to your seller account https://hocvien.tiki.vn/lien-he/

**Comment by longlevan9x** [comment]
Yes. I have contacted you already.

**Comment by vietcaominh** [comment]
ok thanks. Let me close this one
