### ISSUE TITLE
Em cần sử dụng TIKI API OPEN PLATFORM

### ISSUE THREAD

**Issue by vuanh1957** [tikivn/open-api-docs#247]
Em xin chào mọi người ạ !
Em đang gặp vấn đề với API update giá sản phẩm!

{
		url:'https://api.tiki.vn/integration/v1/requests/updateProductInfo',
		method:'POST',
		headers:{
			'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72',
			'tiki-api':'3cee0475-9f0b-xxxx-xxx-xxxxxx'
		},
		rejectUnauthorized:false,
		body:JSON.stringify({
			"product_id": "p54406742",
			"market_price": 227000,
		})
};

Khi em update thì nhận được response là : StatusCodeError: 500 - "{\"errors\":[\"Some unexpected error occurred, please try again later\"]}"

Kính mong Anh/Chị giúp đỡ em 
Email của em là : vuanh1957@icloud.com
Em xin chân thành cảm ơn Anh/Chị rẩt nhiều ạ

**Comment by ducanhnguyen19** [comment]
hello @vuanh1957 TIKI product_id alway is integer, please check it again carefully before you want to update
p54406742 -> 54406742
Thank you

**Comment by vuanh1957** [comment]
@ducanhnguyen19 
Em chào anh ạ ! em đã chỉnh lại thành integer nhưng mà nó vẫn báo lỗi StatusCodeError: 500 - "{"errors":["Some unexpected error occurred, please try again later"]}"
Kính mong anh có thể cho em xin thông tin liên lạc để em tiện trao đổi qua email hoặc số điện thoại được không ạ ?
Em xin chân thành cảm ơn mọi người rất nhiều ạ !

**Comment by ducanhnguyen19** [comment]
please get product_id from your /products endpoint for sure it is your product
or you can test it at first via /products/{product_id}
we got some unexpected error with market price but we will solve it in this morning
please try again later , sorry about this inconvenient

**Comment by vuanh1957** [comment]
@ducanhnguyen19 
let options = {
		url:'https://api.tiki.vn/integration/v1/requests/updateProductInfo',
		method:'POST',
		headers:{
			'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72',
			'tiki-api':'3cee0475-9f0b-4873-91ec-xxxxxxxxx'
		},
		rejectUnauthorized:false,
		body:JSON.stringify({
			"product_id": 33386514,
			"market_price": 278000,
		})
	};


em request đúng như này mà vẫn bị báo lỗi status 500 ạ ,anh có thể teamview giúp đỡ em qua postman được không ạ ?
Em xin chân thành cảm ơn ạ

**Comment by vuanh1957** [comment]
@ducanhnguyen19 
teamview của em là : 
ID : 1 454 891 608
pass : 4h5ra1

**Comment by ducanhnguyen19** [comment]
curl --location --request POST 'https://api.tiki.vn/integration/v1/requests/updateProductInfo' \
--header 'tiki-api: 3cee0475-9f0b-4873-xxxx-xxxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
    "product_id": 33386514,
    "market_price": 278000
}'

**Comment by ducanhnguyen19** [comment]
I got response like that 
```
{
    "errors": [
        "you do not have permission to update this product"
    ]
}
```
you do not have permission because the master product not created by you

**Comment by vuanh1957** [comment]
Anh có thể cho em email em có thể gửi mã tiki-api anh kiểm tra giúp em được không ạ ?
Em request nó cũng báo là "you do not have permission to update this product" ạ

**Comment by ducanhnguyen19** [comment]
`you do not have permission because the master product not created by you`
Seller can update market price only when  seller is owner of this product master (  created this product ) 
your tiki-api is not the problem , please contact TIKI content team to get help

**Comment by vuanh1957** [comment]
@ducanhnguyen19 

Em hiểu vấn đề rồi ạ .
Em cảm ơn Anh rất nhiều ạ !
Chúc Anh luôn luôn thành công và may mắn trong cuộc sống ạ !


THANKS AND BEST REGARD !
