### ISSUE TITLE
Cập nhật giá sản phẩm báo state: 'queuing' 

### ISSUE THREAD

**Issue by vuanh1957** [tikivn/open-api-docs#248]
@ducanhnguyen19 
Em chào Mọi người ạ !
Em có thử request thay đổi giá sản phẩm nhưng khi em vào link sản phẩm thì chưa thấy thay đổi giá ?
Hệ thống response lại kết quả là : {"track_id":"b68f1d9c07c3481e84798d1b419ba46f","state":"queuing"}

Nội dung request của em là 

let options = {
		url:'https://api.tiki.vn/integration/v1/requests/updateProductInfo',
		method:'POST',
		headers:{
			'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72',
			'tiki-api':'1fbfd8aa-2ac0-4306-xxxx-xxxxxx',
			'content-type':'application/json'

		},
		rejectUnauthorized:false,
		body:JSON.stringify({
			"product_id": 51288497,
			"market_price": 66000
		})
	};

**Comment by vuanh1957** [comment]
@ducanhnguyen19 
Anh giúp em với ạ

**Comment by ducanhnguyen19** [comment]
please read our docs carefully at first 
update market price will create a request to content team, 
you can track it via /tracking API

**Comment by vuanh1957** [comment]
@ducanhnguyen19 
em muốn sử dụng api để thay đổi ngay lập tức giá sản phẩm: https://tiki.vn/mui-khoan-be-tong-dau-gai-10x160mm-sds-makita-b-54190-p51288496.html?spid=51288497

vậy có api nào không ạ? em sử dụng api /updateProductInfo đều ở trạng thái queing ạ 
Giờ em chỉ muốn thay đổi giá của sản phẩm ngay lập tức,tức là khi em request đến api thì được approve luôn
Vậy có api nào hỗ trợ không ạ?
Em xin chân thành cảm ơn ạ

**Comment by ducanhnguyen19** [comment]
https://open.tiki.vn/#tiki-product-structure
https://open.tiki.vn/#update-product-information
please read it carefully 
if you want to update price -> it will be update intermediately
if you want to update market_price -> you have to waiting for content team review your request

**Comment by vuanh1957** [comment]
@ducanhnguyen19 
Em có thay đổi trường request là "price" nhưng vẫn bị "update_product_awaiting_approve" ạ
Anh  kiểm tra giúp em với ạ 
let options = {
		url:'https://api.tiki.vn/integration/v1/requests/updateProductInfo',
		method:'POST',
		headers:{
			'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72',
			'tiki-api':'1fbfd8aa-2ac0-4306-81b9-xxxxxxxxx',
			'content-type':'application/json'

		},
		rejectUnauthorized:false,
		body:JSON.stringify({
			"product_id": 51288497,
			"price": 66000
		})
	};

**Comment by vuanh1957** [comment]
@ducanhnguyen19 
Em làm được rồi Anh trai ơi !
Em cảm  ơn anh rất nhiều ạ !
Em bị nhầm url request 1 chút ,hihi
Thanks Anh nha

**Comment by ducanhnguyen19** [comment]
you are welcome, next time if you don't mind please post issue in English because TIKI is supporting seller from other country also
Thank you a lot
