### ISSUE TITLE
Register OAuth2 TIKI

### ISSUE THREAD

**Issue by vuanh1957** [tikivn/open-api-docs#249]
Em muốn đăng kí sử dụng xác thực OAuth2 ạ
Email của bên em là: module.pro@icloud.com
Em xin chân thành cảm ơn ạ.

**Comment by vuanh1957** [comment]
@ducanhnguyen19  
Help me,Thanks bro

**Comment by ducanhnguyen19** [comment]
@hoai-dam please help him

**Comment by vuanh1957** [comment]
@hoai-dam 
giúp em với ạ

**Comment by vuanh1957** [comment]
@hoai-dam 
i  want to develop applications base on Tiki Open API to help sellers manage their stores
Please help me
