### ISSUE TITLE
Ecomeasy Asia

### ISSUE THREAD

**Issue by ecetiki** [tikivn/open-api-docs#250]
Hi team,

We would like to connect TIKI APIs for our clients. Can you please grant an access for us? our email is eceapi@ecomeasy.asia

Thank you

**Comment by vietcaominh** [comment]
@hoai-dam pls support !

**Comment by ecetiki** [comment]
Hello team,

Can you please give us some updates on this request?

**Comment by ecetiki** [comment]
Hi guys,

How we can connect your API?
