### ISSUE TITLE
Nhờ hỗ trợ vì không nhận được webhook event

### ISSUE THREAD

**Issue by AnPhamTiki** [tikivn/open-api-docs#251]
Các webhook đã đăng ký bao gồm:
```
{
    "data": [
        {
            "seller_id": 105169,
            "event": "product:request:rejected",
            "uri": "https://enqm9ir4ssjj.x.pipedream.net/tiki-event",
            "status": 1
        },
        {
            "seller_id": 105169,
            "event": "product:request:approved",
            "uri": "https://enqm9ir4ssjj.x.pipedream.net/tiki-event",
            "status": 1
        },
        {
            "seller_id": 105169,
            "event": "product:request:locked",
            "uri": "https://enqm9ir4ssjj.x.pipedream.net/tiki-event",
            "status": 1
        }
    ]
}
```

Hiện tại bên mình không nhận được callback khi product được approve. Nhờ các bạn kiểm tra giúp.

**Comment by ducanhnguyen19** [comment]
@hoai-dam please check it

**Comment by hoai-dam** [comment]
Hello @AnPhamTiki , I checked and the webhook system has some issues. We're working on the issue now. Could you please tell us whether you're reporting this on PROD or STAGING?

**Comment by AnPhamTiki** [comment]
This is in the production environment at https://api.tiki.vn

**Comment by hoai-dam** [comment]
@AnPhamTiki 
Our team now fixed the issue. We will continue watching the issue after the fix. 
For future product request approvals or rejections your system will receive the web hook events.

**Comment by AnPhamTiki** [comment]
Thanks. Looks like it works now.

**Comment by hoai-dam** [comment]
Thank a lot for your report @AnPhamTiki .
