### ISSUE TITLE
Get order's shipping label to print báo không có quyền

### ISSUE THREAD

**Issue by sweetmilk2030** [tikivn/open-api-docs#252]
Tôi gọi API này, với tiki-api của tôi: https://api.tiki.vn/integration/v1/orders/{order_number}/print
- {order_number} là chổ tôi bỏ vào mả đơn hàng
- Kết quả tôi nhận được: {"errors":["you don't have permission print order"]}

Cũng với tiki-api đó và mả đơn hàng đó thì gọi API này thành công: https://api.tiki.vn/integration/{version}/orders/{order_code}/PO

Với "fulfillment_type": "tiki_delivery" không có cách nào dùng API để lấy ra được số điện thoại người mua phải không?
Xin giúp đở với. @hoai-dam

**Comment by hoai-dam** [comment]
Hello @sweetmilk2030 ,
* With fulfillment_type=tiki_delivery we do not return customer contacts.
* For the `you don't have permission print order` error, that's also because you are not allowed to print shipping labels for tiki_delivery orders

FYI.
