### ISSUE TITLE
unable to get order

### ISSUE THREAD

**Issue by plken** [tikivn/open-api-docs#253]
API：https://api.tiki.vn/integration/v1/orders?page=1&limit=20&status=all&updated_from_date=2020-06-22 01:58:11

unable to get order：
712452583    
367540711

**Comment by ducanhnguyen19** [comment]
@hoai-dam please check it

**Comment by hoai-dam** [comment]
Hello @plken ,
Could you please provide us the error details?

**Comment by hoai-dam** [comment]
Hello @plken ,
Could you please provide us the error details?

**Comment by hoai-dam** [comment]
I'm closing due to no interaction.
