### ISSUE TITLE
Cần thêm tên gói cước vận chuyển

### ISSUE THREAD

**Issue by xenlong** [tikivn/open-api-docs#254]
Xin chào Team tiki, hiện nay trong phần đơn hàng thì chỉ có phần mô tả ước tính thời gian giao hàng mà chưa có tên gói cước vận chuyển đi kèm. Nhờ team Tiki kiểm tra và bổ sung phần này nhé.

**Comment by ducanhnguyen19** [comment]
okay we will add it to backlog , thank you

**Comment by xenlong** [comment]
Cảm ơn,

Ngoài ra làm thế nào để lọc được trạng thái đơn hàng với điều kiện lọc cùng lúc là 2 hoặc 3 hoặc 4 trạng thái...ví dụ status=complete và successful_delivery?

**Comment by hoai-dam** [comment]
Hello @xenlong ,
At the moment, we do not support the feature to search for orders with multiple statuses.

FYI.

**Comment by hoai-dam** [comment]
Hello @xenlong ,
We have added on Order API V2 payload the [Shipping Plan](https://open.tiki.vn/#shipping-plan)`.plan_name` to describe the shipping plan. You can check it out and try the new Order API V2.
