### ISSUE TITLE
Product price and market price has same value

### ISSUE THREAD

**Issue by kabuky** [tikivn/open-api-docs#255]
Hi Tiki,

Product price and market price now has the same value even though on the product page, the value is different.
<img width="503" alt="image" src="https://user-images.githubusercontent.com/1215595/88542830-a8b75a80-d049-11ea-8226-1c121df7e262.png">

Could you help to check?

**Comment by ducanhnguyen19** [comment]
how can you check it is different , I can't check from tiki site because it is disable now

**Comment by kabuky** [comment]
Please take this product as an example. Market price on the product page itself is 310.800 ₫ and price is 276.000 ₫, however API returns both the same value

<img width="333" alt="image" src="https://user-images.githubusercontent.com/1215595/88800585-fb744c00-d1da-11ea-8931-57b7d33a3cf8.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/1215595/88800672-1a72de00-d1db-11ea-8ee9-49817460790e.png">

**Comment by ducanhnguyen19** [comment]
it fixed now, thank you for report
