### ISSUE TITLE
Product Info Update & Inventory update issue 

### ISSUE THREAD

**Issue by gitvishwajitk** [tikivn/open-api-docs#257]
HI team 
I am facing forbidden error while try to update Inventory & product info
here is request response FYI
1. ProductInfoUpdate : 
```
url :  "https://api-sandbox.tiki.vn/integration/v1/requests/updateProductInfo"
header :  {"Authorization"=>"Bearer *************************", "content-type"=>"application/json"}
body = {"product_id"=>"1165345", "price"=>"2300.0", "image"=>"https://uat.tikicdn.com/ts/product/d5/e1/5f/d76e5f3e4bd1475f5ef514fe00cea6de.jpeg", "images"=>[]}

RestClient.post(url,body.to_json,header)
error_message => "RestClient::Forbidden: 403 Forbidden"
```

So i tried with Curl request ...Here is the Request response 

 ```

response = `curl -X POST '#{url}' -H 'Content-Type: application/json' -H 'Authorization: Bearer ***********'  -d'#{body.to_json}'` 
error_message = "{\"errors\":[\"you do not have permission to update this product\"]}"

```
Please check the above issue & provide solution over this.

Thanks & regards 
Vishwajit Kolekar

**Comment by ducanhnguyen19** [comment]
if you want to update price , please use /updateSku endpoint
if you want to update market price + image , please check your product_id carefully 
it must be your product_id in /products and this product must be created by you , not by other seller

**Comment by gitvishwajitk** [comment]
Hi @ducanhnguyen19  

I have checked your suggestion & yes we are following the same. 
For update price/inventory we are using **UpdateSku** endpoint .
But for this we are receiving approved state but changes not reflect on Tiki side following are curl request FYI
```
url: https://api-sandbox.tiki.vn/integration/v1/products/updateSku
body: {
    "product_id": "2171329",
    "price": 95,
    "quantity": 100,
    "active": 0
}

{
    "state": "approved"
}


```

![Screenshot 2020-07-29 at 2 57 29 PM](https://user-images.githubusercontent.com/54353122/88783035-f0ee8e00-d1ab-11ea-9844-2a9fa2c33ecf.png)

**Comment by vietcaominh** [comment]
hi @gitvishwajitk t
sorry for the late reply.
please wait for us to check on that

**Comment by luongquoctiep** [comment]
I'm having the same issue. I've received approved state, but sometimes the change is not reflected on Tiki.

**Comment by vietcaominh** [comment]
hi @luongquoctiep 
1. Can you provide us the product id or SKU and what time you updated it and the time and value you used?
2. Sometimes it happens randomly for you?

**Comment by luongquoctiep** [comment]
Hi @vietcaominh 

1. I used the post request to update this product 

`22/09/2020 16:11
url: https://api.tiki.vn/integration/v1/products/updateSku
body: {
    "product_id": "20113188",
    "price": 147900,
}

{
    "state": "approved"
}
`
2. Yes. This case happens on random products sometimes

**Comment by luongquoctiep** [comment]
Hi @vietcaominh

1. I used the post request to update this product

```
22/09/2020 16:11
url: https://api.tiki.vn/integration/v1/products/updateSku
body: {
"product_id": "20113188",
"price": 147900,
}

{
"state": "approved"
}
```

2. Yes. This case happens on random products sometimes

**Comment by vietcaominh** [comment]
Hi @luongquoctiep l
let me check on that, It seems some things wrong happened, I didn't see the log

**Comment by vietcaominh** [comment]
@gitvishwajitk the error still sometimes happen to you?

**Comment by vietcaominh** [comment]
hi @luongquoctiep 
we acknowledged the is a bug on our system.
Sometime it can happen, we're fixing it. Will let you know here as soon as it done
Thanks for waitting.

**Comment by luongquoctiep** [comment]
Hi @vietcaominh 
Okay. Thank for your support

**Comment by vietcaominh** [comment]
It got fixed now. Please let us know if there are any problems with a new thread. @luongquoctiep  @gitvishwajitk 
I will close this issue for now
