### ISSUE TITLE
whether tracking_number is needed for "dropship" & "seller_delivery"

### ISSUE THREAD

**Issue by shirley118** [tikivn/open-api-docs#262]
![image](https://user-images.githubusercontent.com/68099578/88676484-b25ec200-d11e-11ea-8dea-ab465d361856.png)
Is it tracking_number just needed for "cross_border", when confirm a order?
If fulfillment is "dropship" or "seller_delivery", tracking_number are not needed?
Thank you.

**Comment by ducanhnguyen19** [comment]
tracking number is only required for cross border, because delivery time is longer than other types so seller need tracking number to track orders from 3rd party delivery,
if your process needs it for the others please report us to consider adding tracking number as an optional field

**Comment by shirley118** [comment]
ok. Thank you . we don't have the need now. Thank you.
