### ISSUE TITLE
about fulfillment of "dropship" 

### ISSUE THREAD

**Issue by shirley118** [tikivn/open-api-docs#263]
Excuse me,
What's the meaning of "dropship"?
As far as I know, Tiki has a fulfillment type: the goods are in the seller’s warehouse. After the seller confirm the order. Tiki will go to seller's warehouse to pick up the goods.
Is it "dropship" or "tiki_delivery" or "seller_delivery"?
Thank you very much.

**Comment by ducanhnguyen19** [comment]
@hau-nguyenbich please help me answer this question

**Comment by hau-nguyenbich** [comment]
**Backorder (tiki delivery)** :  products in seller's warehouse, _**TIKI pack**_, TIKI deliver

**Drop_ship** : products in seller's warehouse,, _**seller pack**_, TIKI deliver

**Seller_delivery** :  products in seller's warehouse, seller pack, seller deliver

_Tiki has a fulfillment type: the goods are in the seller’s warehouse. After the seller confirm the order._ 
- If Tiki will go to seller's warehouse to pick up the goods, then bring it to the tiki's warehouse to pack and then deliver it to the customer   -> It's tiki delivery (backorder)
- If Seller pack, then Tiki will go to seller's warehouse to pick up the goods and then delivered directly to customers (do not bring goods to the store of tiki) --> It's Dropship

**Comment by shirley118** [comment]
your explaination is very clear. Thank you very much.
