### ISSUE TITLE
Product fetch issue 

### ISSUE THREAD

**Issue by gitvishwajitk** [tikivn/open-api-docs#264]
Hi Team 

In product fetch getting same value for price & market price . 
```
url : https://api-sandbox.tiki.vn/integration/v1/products/2171417

  "price": 90,
    "market_price": 90,
```
On Tiki marketplace both values are different 
![Screenshot 2020-07-29 at 4 11 53 PM](https://user-images.githubusercontent.com/54353122/88790981-9e669f00-d1b6-11ea-8dfe-f3f943083cc2.png)

**Comment by ducanhnguyen19** [comment]
ok let us check this issue

**Comment by ducanhnguyen19** [comment]
recheck it , its ok now

**Comment by vietcaominh** [comment]
As the problem solved, I will close it @gitvishwajitk
