### ISSUE TITLE
#Oauth 2.0 - Client authentication failed

### ISSUE THREAD

**Issue by module2020** [tikivn/open-api-docs#266]
@
Em chào Admin !
Admin cho em hỏi em request như sau và bị báo lỗi là :
{ error: 'invalid_client',
  error_description:
   'Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)',
  status_code: 401,
  error_debug:
   'crypto/bcrypt: hashedPassword is not the hash of the given password' }

THÔNG TIN REQUEST:
let options = {
			url:'https://api.tiki.vn/sc/oauth2/token',
			method:'POST',
			headers:{
				'Content-Type': 'application/x-www-form-urlencoded',
				'Accept':'application/json',
				'client_id':'5299627201xxxxxx',
				'client_secret':'g1zXdSSQe3mSOpYYeHsFC-xxxxxxx'
			},
			form:{
				grant_type:'authorization_code',
				code:'BNJ-AugQXBRElT4FHWKq3wqcVft6ACrGZ55zClaQgBE.Y4_avT4xe3cWCgP3SlSBeQGkkTJIJwDxxxxxxxx',
				redirect_uri:'https://abc.vn/dashboard/san-thuong-mai/tiki',
				client_id:'5299627201xxxxxx'
			}
		};

Mọi người cho em hỏi lỗi sai ở đâu và sửa như thế nào ạ ?
Em xin trân trọng cảm ơn Admin và mọi người ạ !

**Comment by vuanh1957** [comment]
@ducanhnguyen19

**Comment by ducanhnguyen19** [comment]
@hoai-dam

**Comment by vuanh1957** [comment]
@ducanhnguyen19 
Công thức tạo ra cái Authorization ở header trong request /sc/oauth2/token là gì vậy ạ ?

**Comment by vuanh1957** [comment]
@ducanhnguyen19 
mình dã giải quyết xong,vui lòng đóng task hộ mình
