### ISSUE TITLE
Call api seller get an error: Error: Server Error - The server encountered a temporary error and could not complete your request

### ISSUE THREAD

**Issue by longlevan9x** [tikivn/open-api-docs#267]
Hi Everyone!
I have a problem.
I call api [https://sandbox-api.tiki.vn/integration/v1/sellers/me](https://sandbox-api.tiki.vn/integration/v1/sellers/me)
my header: 
```
 headers: {
                Accept: "application/json",
                Authorization: "Bearer 95rXrgqwMS55eEBuA3OyE3WcCafF3l4rN4LEUNvR7-s.0-dJmgHU8Jx7aAXdVwGTW6Pkz06UH_3pT6Ux-Omhr6k"
            }

```

and i get an error 

`\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n`

after 30s, I call again but it's response as above. 
Please check or fix.
Thanks.

**Comment by ducanhnguyen19** [comment]
TIKI internal system had some problem but it's ok now , thank for you reporting
