### ISSUE TITLE
Please help to open the Test Account on Sandbox site

### ISSUE THREAD

**Issue by kimthuy** [tikivn/open-api-docs#269]
Hi Tiki Team,

I created an account testing on Sandbox site. But it was be inactive.
Please help to active my account.
My Email: thuy.tran@eton.vn

Beside that, could you help me to open the the sale modelS: ODF, DROPSHIP and SELLER DELIVERY. We need to verify the API for all of these sale model

Thanks Team so much.

**Comment by hoai-dam** [comment]
Hello @kimthuy 
We have just enabled the user for you. Could you please check it again?

**Comment by kimthuy** [comment]
Dear Tiki Team,

Thank Tiki Team so much for the activation account early.

Could you please help me to enable "Mô hình bán hàng": ODF, DROPSHIP and SELLER DELIVERY?
We are building an App to help Tiki Seller get Orders from the Tiki Seller Center system via API. Our customer (Tiki Sellers) need to verify all of "Mô hình bán hàng".

Please help,
Thanks Team.

**Comment by hoai-dam** [comment]
Hello @kimthuy 
You can only either enable ODF (`fulfillment_type=tiki_delivery` with `inventory_type=backorder`) or Dropship (`fulfillment_type=dropship`).
I have enabled ODF & Seller Delivery for you.

**Comment by kimthuy** [comment]
I got it.

Thank Tiki Team so much.
