### ISSUE TITLE
[SANDBOX ENV] Order Status = seller_canceled after "Create mock order" and call API "API confirm order items"

### ISSUE THREAD

**Issue by kimthuy** [tikivn/open-api-docs#270]
Hi Tiki Team,

I used "API create mock order" to create a test order on SANDBOX. And there are 2 issues I had:
1. Call API "API create mock order", the response 200OK with an order_code = 73292. But this order does not show in the UI of site https://sandbox-sellercenter.tiki.vn/ ?? Kindly help to figure out what I missed?

2. After creating order by "API create mock order" successful. I call API "API confirm order items". 
 This is the response: 200OK
      {
           "code": 200,
           "data": []
     }
After that, I use API "API get order details" to get the detailed information of this order. But the status changed to "**seller_canceled**". Is it seems not to map with order status flow?

P/S: I found another issue that mentioned the same issue No2 with me.
https://github.com/tikivn/open-api-docs/issues/155

Thanks Team

**Comment by vietcaominh** [comment]
hi @kimthuy Sorry for the late reply. About your questions:
1: Yes, the mock order we create is to support testing in sandbox evironment with Open API. What why it does not show up on Seller Center, only real orders display in there. And you don't really need Seller Center to play with mock orders. Do you have the need for it?
2: When you confirm the order, did you fill the item_ids[] array? If the array is empty it equal to cancel the order . Can you send me the mock order code that not working?

**Comment by kimthuy** [comment]
Hi @vietcaominh 

1. I just want to check is there any difference between creating order by "API create mock order" (Sandbox env) and creating order by UI (Production env)? Something like Validation, Data constraints, Data structure...

 **EXAMPLE**:  I created order with the parameter as below:
 - fulfillment_type = tiki_delivery
 - inventory_type = seller_backorder
As I know "seller_backorder" means "products in seller storage, seller pack, seller deliver" and this inventory_type use for the "mô hình bán hàng" Seller Delivery. So, the "fulfillment_type = tiki_delivery" for this type of order isn't valid, is it?

Here is the json of API create mock order => order_code = 99540:
`{
    "fulfillment_type": "tiki_delivery",
    "payment_method": "cod",
    "items": [
        {
            "product_name": "Áo Thun Nam Catsashop L155 Sát Nách Thêu - Xám - S",
            "original_sku": "AO-6",
            "price": 128000,
            "qty": 1,
            "inventory_type": "seller_backorder"
        }
    ],
    "coupon_code": null,
    "discount_coupon": null,
    "discount_tiki_point": null,
    "shipping": {
        "name": "TTKT",
        "street": "86 Linh Đông",
        "ward": "Linh Đông",
        "city": "Hồ Chí Minh",
        "region": "Hồ Chí Minh",
        "country": "VN",
        "phone": "098XXXXXXX",
        "email": "xxxx@yyy.com",
        "estimate_description": "Dự kiến giao chiều nay",
        "shipping_fee": 0
    },
    "note": "TTKT noted"
}`

2.  Filled item_ids[] is not empty but the element is the wrong value (order_code = 73292). I filled product_id instead of items id.
However, should API confirms order validate the element of items_id is valid or not then returns the validation on the response instead of change the status to "seller_cancelled"? 

**BTW**, Could you teach me the constraints/validations between 2 _fulfillment_type_ and _inventory_type_ ? And could be more than 1 inventory_type in list items?

As the image below, I am not sure but I guess that. Kindly help to confirm.
![image](https://user-images.githubusercontent.com/5510937/90587362-62e25200-e203-11ea-89c4-02d756133080.png)

Please advice.
Thanks Tiki Team.

**Comment by kimthuy** [comment]
Dear Tiki Team,

Please help

**Comment by vietcaominh** [comment]
Hi @kimthuy Sorry for the late reply.

We understand you're confusing with order operations model. We're working on v2 order model to make it cleaner. But let me explain the v1 model for now.

1. There are differences between creating mock orders and orders on production. The Data structure is the same, but the data validation and data constraints might me missing in mock orders, because the real order is complex, so we can copy all the data contains, validation to mock order. So for your question `for this type of order isn't valid, is it`, it's not valid.
The point we created the mock order function is to support you have orders to try to integration, you can use a mock order structure to test with real order logic we provided in docs. All the info related to orders in docs is true for real orders.

2. The current behavior for both sandbox and real orders are we don't check the item_ids not in order, we just treat it as empty item_ids array. We added this check on orders v2 will release soon. But if you build the UI for it, it should be no problem for users.
And could be more than 1 inventory_type in list items -> No, we will break order if multiple inventory_type in list items before return to you
The image you got right, but missing some cases like tiki_delivery can go with in_stock. We will add the table as you suggested soon.

If you still concern please let us know, thanks!

**Comment by kimthuy** [comment]
Hi @vietcaominh 

Thank you so much for your very clear answers.

And once more question related to the operation model _"ODF-Nhà bán giao hàng qua kho Tiki"._
If Seller connect with Tiki on more than one Warehouse (ie: Vĩnh Lộc Mới, Sài Gòn). 
So, in the _API Get List Order_ or _API Get Order Detail_, how can Seller know exactly which warehouse of Tiki will be received the SO of Seller?

I see the param warehouse_code in the response of _API Get Order Detail_ on PROD env. Can we use this param to know the Tiki warehouse to ship the order to?

![image](https://user-images.githubusercontent.com/5510937/91811448-b61fc000-ec59-11ea-8927-7e68e7cdf715.png)

Note:  on the Sandbox env, the param warehouse_code is null

Thanks,
Thuy tran

**Comment by vietcaominh** [comment]
Yes, on sandbox is null cause we missed it.
Let @hoai-dam help more on this question!

**Comment by hau-nguyenbich** [comment]
Yes, you use this param ( warehouse_code) in order to know the Tiki warehouse to ship the order

**Comment by vietcaominh** [comment]
@kimthuy is the answer above solve your problems?
If you have more concerns just let us know

**Comment by kimthuy** [comment]
Dear Tiki Team,

The answer is very clear.

Thank so much for your support.

**Comment by vietcaominh** [comment]
Thanks @kimthuy , 
Can I ask how your integration status with Tiki go?
And also do you integrate with Tiki on a seller or a platform for many sellers?

**Comment by kimthuy** [comment]
We are in process of integration (est 20%).
And we are building a platform for many sellers. That why I need to understand deeper about all of Tiki Operation Model (and also API ability for each Model)

Maybe I need to ask more questions in the future. ^.^
And hope that Tiki Team doesn't feel annoyed about that.

**Comment by vietcaominh** [comment]
Hi @kimthuy, If you are a platform for sellers, we can create a support channel to help you faster with the integration.
Can I get your information to your platform via viet.cao@tiki.vn

**Comment by kimthuy** [comment]
Hi @vietcaominh ,

Thank you so much for the private channel via email. I will send an email to you soon.

**Comment by vietcaominh** [comment]
Ok let us know if you continue, I will close this one for now
