### ISSUE TITLE
Order's detail Api reponse wrong result?

### ISSUE THREAD

**Issue by hungpx90** [tikivn/open-api-docs#271]
![image_2020_08_04T07_08_31_832Z](https://user-images.githubusercontent.com/66917989/90353014-401f3480-e06f-11ea-94a9-25a8044e6a16.png)
![Untitled](https://user-images.githubusercontent.com/66917989/90353018-43b2bb80-e06f-11ea-9f8e-7a47e309bd82.jpg)
This order has deliverydate at 4/8/2020. But order's detail api response UPDATE_AT: 31/07/2020. Can you help me check this again? please!

**Comment by vietcaominh** [comment]
@hoai-dam please help with this!

**Comment by hoai-dam** [comment]
Hello @hungpx90 ,
At the moment we have some problems controlling the `updated_at` value, some updates to orders do not actually update this field in db. But important updates like updates to `status` are guaranteed to actually update the `updated_at` fields.
