### ISSUE TITLE
Can I update number of quantity available product on Tiki?

### ISSUE THREAD

**Issue by hungpx90** [tikivn/open-api-docs#272]
![IMG_1766](https://user-images.githubusercontent.com/66917989/90364738-cdbe4c80-e08e-11ea-9efb-10e4c895ad74.jpg)
I call this api:  https://api.tiki.vn/integration/v1/products/updateSku to update quantity's product = 8. It's updated to field: "NHÀ BÁN HÀNG" successfull, but I want update field: "CHO PHÉP ĐẶT HÀNG" = 8. How to update its?

**Comment by vietcaominh** [comment]
ok, let us check with internal team

**Comment by vietcaominh** [comment]
hi @hungpx90 
The field "Cho phép đặt hàng" is calculated base on filed "Nha Ban Hang" - the number of items in orders are processing. So you don't need to update it

**Comment by hungpx90** [comment]
ok, I can see that. Thanks!

**Comment by vietcaominh** [comment]
Thanks, I will close it then
