### ISSUE TITLE
Whether tiki_delivery order need confirm?

### ISSUE THREAD

**Issue by shirley118** [tikivn/open-api-docs#273]
hello, Sir.
The document tells us "If your order fulfillment_type is tiki_delivery congratulation, you don't need to confirm the order as we have supported automatic order confirmation with this type.".

But from the order status flows , It seems it also need seller confirmation for tiki_delivery.
And as I know, Tiki has a fulfillment type: the goods are in the seller’s warehouse. After the seller confirm the order, Tiki will go to seller's warehouse to pick up the goods, then bring it to the tiki's warehouse to pack and then deliver it to the customer.

![image](https://user-images.githubusercontent.com/68099578/90585137-b86c2e00-e206-11ea-9aef-3968a07b9d50.png)
![image](https://user-images.githubusercontent.com/68099578/90585241-f5382500-e206-11ea-91f2-8522d5be5ca0.png)

**Comment by hoai-dam** [comment]
Hello @shirley118 ,
All your orders with at least 1 order item have `inventory_type=backorder` requires you to confirm, whatever the `fulfillment_type`.
FYI.

**Comment by shirley118** [comment]
ok. Except inventory_type=backorder, what other values might inventory_type be?

**Comment by hoai-dam** [comment]
Hello @shirley118 
Here it is [Order Product Inventory Type](https://open.tiki.vn/#order-product-inventory-type)
