### ISSUE TITLE
tiki là thuần việt vậy nên hỏi và giải đáp bằng tiếng việt sẽ tiện hơn, chẳng thằng tây nào nó mò vào đây đâu.

### ISSUE THREAD

**Issue by nguyenphuthuybk** [tikivn/open-api-docs#276]
Chào tiki
Tôi thấy việc hỏi đáp bằng tiếng anh cũng tốt đặc biệt là với tây :) Tuy nhiên chẳng thằng tây nào nó đọc đâu trong khi đó Tiki là thuần việt nên làm tốt việc giải đáp thắc mắc của những người Việt trước tiên. 
Vì vậy tôi mong tiki có một group thuần Việt để tiện trao đổi cũng như giải đáp các thắc mắc của các thành viên (Nói tiếng Việt)
Xin cảm ơn !

**Comment by tiendn** [comment]
Mình thấy tiếng Anh cũng được mà, DEV nào mà chả phải có biết tiếng Anh.
Ngoài ra, khi làm bằng tiếng Anh mức độ scale OPEN-API sẽ tốt hơn.
Hiện tại Tiki có bán hàng quốc tế, DEV ngoài muốn tích hợp thì rất khó để dịch và hỗ trợ.

**Comment by tuhucon** [comment]
Because open-api system is used by lot of foreign sellers,
Moreover, I don't think using English is difficult for developer :D
I will close this issue due to don't use Eng :))))
