### ISSUE TITLE
Xin hướng dẫn sử dụng access_token với các API trong postman

### ISSUE THREAD

**Issue by caominhtri93** [tikivn/open-api-docs#280]
Hi Tiki, mình nhận được access_token nhưng chưa dùng được trong post man với các request api. Mong Tiki cho mình hướng dẫn step by step rõ ràng hơn. Cảm ơn Tiki.

**Comment by tuhucon** [comment]
Bên mình đang tạo docs cho phần này, chắc vài ngày nữa sẽ release

**Comment by hoai-dam** [comment]
Hello  @caominhtri93,
You can check it out here: [Tiki OAuth2 with Postman](https://open.tiki.vn/#oauth2-with-postman)
