### ISSUE TITLE
Is test ID for developer available at Tiki? 

### ISSUE THREAD

**Issue by cafe24korea** [tikivn/open-api-docs#283]
Good day.
We are planning to provide linking service with Tiki for our customer by using API and, there are issues needed to be tested via test ID. 
 
Is Tiki providing the test ID for the developers? If so, would you guide us where to request it?
If it is not available, do the technicians required to create the seller account? 

Thank you in advance.

**Comment by vietcaominh** [comment]
hi @cafe24korea  yes, we do provided a test account for developers.
Please send your request with email here https://github.com/tikivn/open-api-docs/issues/183

**Comment by vietcaominh** [comment]
Please raise in the topic I mentioned above, I will close it for now
