### ISSUE TITLE
About the interface of creating products

### ISSUE THREAD

**Issue by chengbirght** [tikivn/open-api-docs#284]
Hello, excuse me, I used the post request to create the product interface, and kept holding this error ({"errors":["Can't read http message, please check your request"]}), you can help to see if What's the problem?

This is the parameter I passed：
{"attributes":{"origin":"fdasd","bulky":"1 ","is_free_gift":" khong","brand_origin":"erew","require_expiry_date":" 0","product_top_features":"dfdsfd","is_warranty_applied":" 0","is_warranty_forever":" 0","brand":"huawei"},"category_id":"20782","certificate_files":[{"url":"https:\/\/i.imgur.com\/MnoEm09.jpg","type":"category","document_id":"1"}],"description":"","image":"https:\/\/yushan-image.oss-cn-zhangjiakou.aliyuncs.com\/img12\/0c25a4c2d7893c5995d464d0a1d3b510_1597973673.jpg","images":["https:\/\/yushan-image.oss-cn-zhangjiakou.aliyuncs.com\/img12\/0c25a4c2d7893c5995d464d0a1d3b510_1597973678.jpg"],"market_price":"19000.00","name":"\u6d4b\u8bd5\u5546\u54c11","option_attributes":["color","size"],"variants":[{"sku":"SP123456YS1GG1","price":"50000.00","option1":"\u989c\u82721","option2":"\u89c4\u683c1","inventory_type":"cross_border","supplier":"SGN","quantity":"1"}]}

thanks

**Comment by vietcaominh** [comment]
hi @chengbirght c
Can you check again? There might system outage at that time!
