### ISSUE TITLE
About supplier id choose

### ISSUE THREAD

**Issue by flyingidentity** [tikivn/open-api-docs#285]
Which supplier ID should cross-border sellers choose？

![image](https://user-images.githubusercontent.com/35824198/92081057-15fe9e00-edf5-11ea-9937-297ec093a01b.png)

-----------------------------------

We support 2 ways that you can get suppler id:

You can call the Get TIKI warehouses endpoint to get list of all TIKI's warehouses. After that you can select list of TIKI warehouses you want to transfer product to. Then you send the list of warehouse codes you selected to the Get supplier by warehouse codes endpoint to get supplier id. Not all of list warehouses has an available supplier in TIKI system. You can call it to check every time you change warehouse list.
You can call directly the Get suppliers endpoint to get list all suppliers that available from TIKI. Then you can select one of them then get it's supplier id.

**Comment by vietcaominh** [comment]
Hi @flyingidentity as we mentioned in the docs

> There are cases you need to fill in supplier depends on product's inventory type you choose:
> 
> If product's inventory_type is instock, you don't need to fill in supplier
> If product's inventory_type is cross_border, you need to ask TIKI's supporter to get supplier id
> Otherwise you can read bellow to get supplier.

If you're cross border contract to our supporter(sale) people that are working with you, she/he will give you the supplier id?
If you need more help with the supplier id please let me know here?

**Comment by vietcaominh** [comment]
I will close as it seem worked for you
