### ISSUE TITLE
Error when call api of TIKI "Got 403 when calling sc-query-api.tiki.services"

### ISSUE THREAD

**Issue by thinhhn** [tikivn/open-api-docs#286]
When I get order detail. I receive response "Got 403 when calling sc-query-api.tiki.services". 
Please explain this error

**Comment by vietcaominh** [comment]
hi @thinhhn that means you don't have access right to get this order code. Is that happen all the time or some order codes?
If it happens with some order code only please give us an order code list and your seller name or id?

**Comment by thinhhn** [comment]
Thank for you anwser. I think more specific error should be returned in these cases.

**Comment by vietcaominh** [comment]
YES, thanks. We will change the message
