### ISSUE TITLE
the information of the shipping code does not return from api

### ISSUE THREAD

**Issue by ReasonZhang** [tikivn/open-api-docs#290]
"GET /orders/72650868?include=delivery_info"
"delivery_info": {
        "shipping_code": "ALT446893354"
    },
Call like API "/orders/72650868?include=delivery_info", no node information  of 'delivery_info' is returned, please help, thks!

**Comment by vietcaominh** [comment]
@hau-nguyenbich will help you on that!

**Comment by ReasonZhang** [comment]
I can't get the value of "delivery_info" by api, what should I do?

**Comment by vietcaominh** [comment]
hi @ReasonZhang yes we do have delivery info in our system. But currently, it's not exposed yet
Can you tell me your use cases need that, we will expose it via API if it is value for you?

**Comment by ReasonZhang** [comment]
I am the seller of your platform Tiki. We need shipping information to print out the receipt and attach it to the package and send it to the buyer.
Here is the request URL of one of the real orders:
https://api-sellercenter.tiki.vn/integration/orders/299696213?include=delivery_info

**Comment by vietcaominh** [comment]
I see the delivery info. @ReasonZhang 
You are using our old API at https://sellercenter-api-docs.tiki.vn/#get-orders right?
Did you switch to our new api at https://open.tiki.vn/?
If you did, let us add delivery info to our new API

**Comment by ReasonZhang** [comment]
There is currently no switch to the new API.
Because we need some time to switch to the new API,
So can you include delivery info in the old API so that we can process the existing orders first?
THKS！

**Comment by ReasonZhang** [comment]
Sorry @vietcaominh 
To add, we are now using the old API, but there is no delivery info.

**Comment by vietcaominh** [comment]
Ok, let me forward to the team in charge of the old API to help you, I will update you here as soon as I have the response

**Comment by ReasonZhang** [comment]
Okay, thank you very much!

**Comment by hoai-dam** [comment]
Hello @ReasonZhang ,
You can use this API to print the shipping label: 
https://open.tiki.vn/#get-order-39-s-shipping-label-to-print

**Comment by ReasonZhang** [comment]
First of all, I need the shipping code and shipping label in our ERP.
when leaving the warehouse, compare the shipping code in the ERP with the shipping code on the shipping label, and ship the goods after confirming that they are consistent.
Not only print the shipping label.
Is Shipping Code equal to OrderCode?

**Comment by hoai-dam** [comment]
@ReasonZhang 
Yeah, we are adding it soon. Thank you for reporting this ;)
Shipping Code does not equal to Order Code.

**Comment by ReasonZhang** [comment]
Okay, thank you very much!

**Comment by hoai-dam** [comment]
It's fixed now. Please check it again ;)

**Comment by ReasonZhang** [comment]
Successfully get Shipping Code!
Thank you very much ;)
