### ISSUE TITLE
Please active my account on sandbox site

### ISSUE THREAD

**Issue by giangnh27** [tikivn/open-api-docs#291]

**Comment by giangnh27** [comment]
Dear Tiki team,
Please help me to verify my account "giangnh1@novaon.vn" on sandbox site because I am trying integrating our system (Onshop) with Tiki. Thanks a lot!

**Comment by vietcaominh** [comment]
Hi @giangnh27 We just have activated your account on sandbox with "giangnh1@novaon.vn".
Also are you trying to integrate using api-key or Oauth2?

**Comment by giangnh27** [comment]
Thanks a lot, Tiki team ^^
About using API-Key or Oauth2: As a BA, I am researching the Tiki system in preparation for integrating with Onshop, so we will consider using API-key or Oauth2 in the near future. If problems arise, I hope you guy will help us.

Note: I used the real business registration number to register an account on the sandbox, so when we officially integrate into the production, can I reuse that business registration number with a real account or can I change business registration information on sandbox account?

**Comment by vietcaominh** [comment]
Yes, you can use the same info to register on production, don't worry!
So you are a platform for many sellers? Not an individual seller?

**Comment by giangnh27** [comment]
Thanks for your assistance :D
Well as you said, we are the unified e-commerce platform, that is we help all sellers (both individuals and businesses) create website, manage products, order from website, facebook, POS in one place and synchronize all product order information from exchanges like Tiki.

**Comment by vietcaominh** [comment]
Hi @giangnh27, if you're a platform, we can create a channel to support you faster with integration.
Can you send us your information to viet.cao@tiki.vn
We can see how to help you faster

**Comment by giangnh27** [comment]
Thanks Tiki, you guys are so enthusiastic  :))
According to our plan, we are going to integrate in the middle of October, so at the time if we need help we will provide information for you.
Also, do you have a limit on the number of the request and encrypt the returned information in the order?

**Comment by vietcaominh** [comment]
ok, let us know when this time comes, we can guide for a specific way for platforms.
We limit requests on each seller account, 50 requests/s. Now we don't encrypt the response, what you need that for?

**Comment by giangnh27** [comment]
Okay, when it comes we will let you know. 
About encrypting, the last time we connected with Lazada, there was a DataMoat security service and we have to make an information declaration procedure so that the returned order information is not encrypted. So we asked if Tiki has something similar to that. Luckily there're not.

**Comment by giangnh27** [comment]
Hey guys, I can't find the button to add the return stock anywhere. Can you show me where it is? 
![image](https://user-images.githubusercontent.com/71374276/94097588-f9ccaa80-fe50-11ea-8512-6f180bca9430.png)

**Comment by vietcaominh** [comment]
hi @giangdinhtt g
the button is not showing up because the is might be a bug related to Seller center.
Can you send me credential to viet.cao@tiki.vn to help us check it faster

**Comment by hoai-dam** [comment]
Closed due to no more interaction.
