### ISSUE TITLE
[Dropship] How to confirm order and confirm packed order via API ?

### ISSUE THREAD

**Issue by TrongNguyen3103** [tikivn/open-api-docs#292]

**Comment by vietcaominh** [comment]
Can you explain more about your problem?

**Comment by TrongNguyen3103** [comment]
Hi support,
I would like to have a function call via API to "confirm order" for "dropship" orders.
Can Tiki support it?

**Comment by TrongNguyen3103** [comment]
Hi support, 
Could you help me ?

**Comment by vietcaominh** [comment]
Yes, there is a guideline to confirm orders here. You can use it to confirm any kind of orders. Do you saw it before?
https://open.tiki.vn/#confirm-an-order

**Comment by TrongNguyen3103** [comment]
Yes, I have followed the documentation. 
But it does not work for menu having fulfillment_type = "Drop Shipping".
It only works when fulfillment_type = "On-Demand Fulfillment" (ODF)

**Comment by vietcaominh** [comment]
Error return when you confirm Drop ship orders? Can you send the error you got here?

**Comment by TrongNguyen3103** [comment]
Request
{
    "order_code": "456548869",
    "warehouse_id": "159534",
    "item_ids": [162192563, 162192564],
    "delivery_commitment_time": "2020-09-24 15:59:59"
}
=====
Response
{
    "errors": [
        "Cannot use this API to confirm dropship orders."
    ]
}

**Comment by TrongNguyen3103** [comment]
I used: POST https://api.tiki.vn/integration/v1/orders/confirmItems

**Comment by vietcaominh** [comment]
Ok let @hoai-dam check on that

**Comment by vietcaominh** [comment]
Hi @TrongNguyen3103 tron
right now we haven't support confirm for drop-ship order yet, Please use the seller center for now. We are working on it

**Comment by TrongNguyen3103** [comment]
Yes, where will I get an update when you are done with it?

**Comment by vietcaominh** [comment]
Yes, I will let you know here as soon as it has done. Please stay tuned, It might take a week from now @TrongNguyen3103

**Comment by TrongNguyen3103** [comment]
Hi @vietcaominh ,
Let me know when I will be able to use this feature, please ?

**Comment by vietcaominh** [comment]
Sorry, let me get back to you tomorrow after our sprint planning. @hoai-dam will follow with you also

**Comment by TrongNguyen3103** [comment]
Hi team,
I call API get list orders via Postman is successful. But I call the same via Python and response key 403.
Could you help me, please !

Thanks !

**Comment by vietcaominh** [comment]
Can you debug on your code what is the request payload is, 403 mean usually mean you don't have permission to get that order code

**Comment by TrongNguyen3103** [comment]
> Sorry, let me get back to you tomorrow after our sprint planning. @hoai-dam will follow with you also

Hi @hoai-dam ,
Let me know when I will be able to use this feature, please ?

**Comment by hoai-dam** [comment]
Hello @TrongNguyen3103 
The drop shipping confirmation APIs is now available:
https://open.tiki.vn/#confirm-enough-stock-for-drop-shipping
https://open.tiki.vn/#confirm-packing-is-done-for-drop-shipping

For drop shipping operation model, please check: 
https://open.tiki.vn/#operation-models

**Comment by TrongNguyen3103** [comment]
Hi @hoai-dam ,
I used Confirm enough stock and Confirm packing is done for Drop Shipping.

System response:
{
    "errors": [
        "Vui lòng xác nhận đơn hàng dropship trên web - (API version deprecated)"
    ]
}

yesterday, it work. Today is not work.

Could you help me, please !

Thanks !

**Comment by hoai-dam** [comment]
Hello @TrongNguyen3103 ,
We fixed it now. Could you please confirm if the API is OK on your side now?
Thank you for your information.
