### ISSUE TITLE
order's Response api return wrong status

### ISSUE THREAD

**Issue by hungpx90** [tikivn/open-api-docs#294]
![picturemessage_xqat2rmy ppj](https://user-images.githubusercontent.com/66917989/93963630-e1448d80-fd87-11ea-81f2-cba1a1862c44.png)
**Url**: https://api.tiki.vn/integration/v1/orders/361336936
**Response**: status is **Queueing** 
Please check back for me. Thanks! 
====================================================>
update:
Tiki Order ID: 435063109 . This order is status: 'Queueing', too

**Comment by hungpx90** [comment]
help me, please!

**Comment by vietcaominh** [comment]
ok,  @hoai-dam oai will help you on that

**Comment by hungpx90** [comment]
help me! please?

**Comment by hungpx90** [comment]
![picturemessage_jxwm5ulp km5](https://user-images.githubusercontent.com/66917989/96553552-8303bf80-12df-11eb-8285-2bea8c0fc073.png)
This Orders response status queueing

**Comment by hoai-dam** [comment]
Hello @hungpx90 
That's not wrong. "Đang lấy hàng" criteria are
* `status=queueing`
* `fulfillment_type=dropship`
* `item_confirmation_status=ready_to_pick`
