### ISSUE TITLE
[Datamart] Can not change quantity of a backorder-tiki_delivery product

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#295]
env: prod
calls: 

```
POST /integration/v1/products/updateSku HTTP/1.1
Host: api.tiki.vn
Authorization: Bearer tf_l_j ...
Content-Type: application/json

{"product_id":6879747,"quantity":0}
```

response:
```
{"state":"approved"}
```

However, after a few minutes, we called

```
GET /integration/v1/products/6879747 HTTP/1.1
Host: api.tiki.vn
Authorization: Bearer tf_l_j ...
Content-Type: application/json
```

response: 
```
...
  "inventory": {
    "inventory_type": "backorder",
    "fulfillment_type": "tiki_delivery",
    "quantity": 98,
    "quantity_available": 98,
    "quantity_reserved": 0,
    "quantity_sellable": 98
  }
```

As you see, quantity is unchanged, so basically, we cannot make some product quantity update requests even the update item response seems to be successful.

**Comment by vietcaominh** [comment]
hi @hungsmcc what time you did the update api ?

**Comment by hungsmcc** [comment]
hi @vietcaominh , it is at 2020-09-24T13:57:09+07:00

**Comment by vietcaominh** [comment]
hi @hungsmcc , We acknowledged the problem, we are fixing it. Hope to finish it soon. I will let you know there.

**Comment by hungsmcc** [comment]
Hi Tiki colleagues, firstly we really really appreciate your supports through a really touch time period, we can do nothing without your kindness, even sometimes it is not your problems.
Today, I have some bad news in my work, I even don't know my job or my company has to go at first. If that happens I really don't want these issues to have to contribute a part as the remains. 
Hopefully, Tiki colleagues read my appeal to give some info about these issues. (and [https://github.com/tikivn/open-api-docs/issues/293](https://github.com/tikivn/open-api-docs/issues/293))

May the force be with you. 
Regards

**Comment by vietcaominh** [comment]
hi @hungsmcc what happened to you and your company @..?
This issue now got fixed, now update quantity will take effect for sure. If you still facing problems let us know
Let me look at problem #293 also.

**Comment by hungsmcc** [comment]
@vietcaominh My company took a step back that is downsizing team as lean as possible. Lucky (or badly) I decided to stay with all the remaining kinds of stuff. Thanks a bunch for the weekend hotfixes and for notifying us.

**Comment by vietcaominh** [comment]
Sorry to hear that Hung, stay positive. We will try to support you as we can
