### ISSUE TITLE
làm thế nào để lấy client_id và serect_key

### ISSUE THREAD

**Issue by tranphuhai** [tikivn/open-api-docs#297]
tôi muốn tạo app đồng bộ sản phẩm và đơn hàng từ của hàng của tôi với tiki tôi muốn xác thực với Oauth2 không phải là api_key

**Comment by vietcaominh** [comment]
Please put your request here @tranphuhai https://github.com/tikivn/open-api-docs/issues/183

**Comment by duylk160760** [comment]
> Please put your request here @tranphuhai #183

Hello,
I am working with OAuth2, can you help me get the client_id and Client Secret?
My email: duymanutd6789@gmail.com
Thank you very much
