### ISSUE TITLE
Lỗi khi lấy thuộc tính sản phẩm và tạo sản phẩm

### ISSUE THREAD

**Issue by tthieu002** [tikivn/open-api-docs#299]
Hiện tại tôi đang có những vấn đề sau mong nhận được sự hỗ trợ từ Tiki:
 1. Sản phẩm tạo tạo báo lỗi: **Attributes not found for category_id: 10469**
 2. Khi tôi thực hiện lấy thuộc tinh sản phẩm từ link : **https://api-sandbox.tiki.vn/integration/v1/categories/{category_id}** kết quả nhận lại không như mô tả trong tài liệu hướng dẫn mà lại thiếu **attributes**

Mong nhận được sự hỗ trợ sớm về vấn đề này

Thanks

**Comment by vietcaominh** [comment]
hi @tthieu002 
There was a problem with our system at that time. Now the attribute list has come back
Please reopen if you still have an issue with it.
