### ISSUE TITLE
Please active my account on sandbox site

### ISSUE THREAD

**Issue by phnquan** [tikivn/open-api-docs#300]
Dear Tiki team,
Please help me to add my account quan.phngoc@gmail.com on sandbox site because I am trying integrating our system with Tiki. Thanks!

**Comment by vietcaominh** [comment]
ok let @hau-nguyenbich help you!

**Comment by vietcaominh** [comment]
@phnquan please register your account here first and we will active for you
https://sandbox-sellercenter.tiki.vn/new#/
And also are you an individual seller or a platform for sellers

**Comment by hoai-dam** [comment]
Closed due to no more interation.
