### ISSUE TITLE
OAuth2 invalid redirect_uri

### ISSUE THREAD

**Issue by paragasu** [tikivn/open-api-docs#305]
Hi Tiki Team,

I am implementing the oauth2 however i face issue with invalid redirect_uri on the`/sc/oauth2/auth`. 
May i know how to whitelist the the redirect_uri?

**Comment by vietcaominh** [comment]
@hoai-dam oa
please support @paragasu

**Comment by hoai-dam** [comment]
Hello @paragasu 
Please leave me your email then I can support you.

**Comment by hoai-dam** [comment]
Hello @paragasu 
Please leave me your email then I can support you.

**Comment by paragasu** [comment]
@hoai-dam you can email me at jeffry.l@bluevinegar.com

**Comment by hoai-dam** [comment]
The request has been supported via another channel (email).
