### ISSUE TITLE
Cần hỗ trợ lấy giá trị discount

### ISSUE THREAD

**Issue by phnquan** [tikivn/open-api-docs#310]
Hi Tiki team,
hiện tại tôi đang tích hợp tiki vào hệ thống của chúng tôi để theo dõi doanh thu nhưng đang gặp vấn đề khi lấy giá trị discount của order, có cách nào để phân biệt giá trị disount nào là của bên tiki tự discount cho user hay giá trị discount do seller tự thiết lập để giảm cho user

**Comment by hoai-dam** [comment]
Hello @phnquan 
Discount data is fully available in Order API V2. For your concern, please check
https://open.tiki.vn/#order-item-invoice

Here seller discount is calculated by
`discount_coupon` and `is_seller_discount_coupon` fields.
