### ISSUE TITLE
Hủy đơn hàng sau khi chuyển trạng thái handover_to_partner

### ISSUE THREAD

**Issue by phnquan** [tikivn/open-api-docs#315]
Hi Tiki team
Đối với đơn hàng seller tự giao, sau khi confirm đơn hàng sẽ chuyển qua trạng thái handover_to_partner, khi shipper giao không thành công thì làm thế nào để chuyển qua trạng thái cancel, tôi đã thử dùng api https://api.tiki.vn/integration/v1/orders/updateDeliveryStatus nhưng nhân được lỗi "status incorrect"

**Comment by vietcaominh** [comment]
@hoai-dam please support @phnquan for this case

**Comment by phnquan** [comment]
@hoai-dam  pls help me

**Comment by hoai-dam** [comment]
hello @phnquan 
we're working on this sprint. expect this to be fixed by the end of next week.
thanks for your patience

**Comment by hoai-dam** [comment]
Hello @phnquan 
You can use the updateDeliveryStatus API to update the delivery of **Seller Delivery** orders to `failed_delivery`  now.
See https://open.tiki.vn/#api-update-delivery-status for more details.
Thank you for your information, we keep improving the APIs and documentation from your feedbacks
