### ISSUE TITLE
[DropShipping] Get order's shipping label to print

### ISSUE THREAD

**Issue by TrongNguyen3103** [tikivn/open-api-docs#321]
Hi support,
I get order's shipping label to print on Saler Center and I call get order's shipping label via API.
It's not the same.

Tks!

**Comment by annguyen1892** [comment]
@TrongNguyen3103  please check again, If still get the problem please give me your detail request

**Comment by TrongNguyen3103** [comment]
> @TrongNguyen3103 please check again, If still get the problem please give me your detail request

Hi @annguyen1892 ,
I call print label via API: https://api.tiki.vn/integration/v1/orders/971348648/print
response: https://salt.tikicdn.com/ts/tmp/96/75/64/72c1a089768659b43c908ac2676511fc.html

It's not the same, label print via Saler Center
[971348648.pdf](https://github.com/tikivn/open-api-docs/files/5564952/971348648.pdf)

You check again,pls !

Thanks.

**Comment by annguyen1892** [comment]
@TrongNguyen3103  in API for now divide  two url shipping_label_url and shipping_stamp_url, could you please use two url to print label and stamp order? sorry for this inconvenien

{
    "shipping_label_url": "https://salt.tikicdn.com/ts/tmp/a4/17/88/90337625dbe57da1f5e3620b09d257e7.html",
    "shipping_stamp_url": "https://salt.tikicdn.com/ts/print/19/55/ad/24548cfc019e810e73cc67ebb4c98bb7.html"
}

**Comment by TrongNguyen3103** [comment]
> @TrongNguyen3103 in API for now divide two url shipping_label_url and shipping_stamp_url, could you please use two url to print label and stamp order? sorry for this inconvenien
> 
> {
> "shipping_label_url": "https://salt.tikicdn.com/ts/tmp/a4/17/88/90337625dbe57da1f5e3620b09d257e7.html",
> "shipping_stamp_url": "https://salt.tikicdn.com/ts/print/19/55/ad/24548cfc019e810e73cc67ebb4c98bb7.html"
> }

Yes, But does it change the way the API is invoked ? 
I called https://api.tiki.vn/integration/v1/orders/971348648/print It's not work ?

**Comment by hoai-dam** [comment]
Hello @TrongNguyen3103,
The new version of this printing order is being developed, it will be available next week. 
Thank you for your patience.

**Comment by hoai-dam** [comment]
Hello @TrongNguyen3103 
We fixed the print order API for dropship orders. Now every dropship order has both `shipping_label_url` & `shipping_stamp_url`. You can try the print order API for dropship now.

Thank you for your patience.
