### ISSUE TITLE
Shipping label is Error

### ISSUE THREAD

**Issue by ReasonZhang** [tikivn/open-api-docs#322]
1.Starting from 2020-09-13, the format of the shipping label obtained through the API is HTML, and the parameter of sended is PDF.
2.The tracking number in some shipping labels is different from the obtained ones, such as 31428817035385, and the shipping label is 903397378. URL is'https://salt.tikicdn.com/ts/tmp/83/41/ac/dc923e2dc99f20a42dd417899bfc6691.html'.
3.The requested API url is https://api-sellercenter.tiki.vn/integration/print/orders?code=903397378&label=invoice&format=pdf
Please help?

**Comment by annguyen1892** [comment]
bug fixed, please check again thank @ReasonZhang

**Comment by ReasonZhang** [comment]
The PDF file has been returned correctly, but the file is 2 pages. 
Please correct it, thanks!

**Comment by ReasonZhang** [comment]
All are ok.
Thanks!
