### ISSUE TITLE
Are you update print PO?

### ISSUE THREAD

**Issue by thinhhn** [tikivn/open-api-docs#323]
Before I call print PO, This system of Tiki response url: https://salt.tikicdn.com/ts/print/f2/68/ee/35c22dd6c5f85fc2e8a39939f2e87abd.html
But now, when I call, System response url https://salt.tikicdn.com/ts/tmp/b7/dd/67/66fb4e27407c787ebc3f76b2eb572107.html.
Can I ask if there is any change?

**Comment by annguyen1892** [comment]
@thinhhn  could you please give me your detail request?

**Comment by thinhhn** [comment]
I'm request with url: https://api.tiki.vn/integration/v1/orders/320795348/PO
And receive response of system with url : https://salt.tikicdn.com/ts/tmp/34/eb/54/714fe534dbdcc350c5edfe5ddf08726c.html

**Comment by annguyen1892** [comment]
@thinhhn this bug fix, please check again, thank you!

**Comment by thinhhn** [comment]
Yes. It's working. Thanks you support for me

**Comment by jackdo69** [comment]
I got this issue with my response also!!
