### ISSUE TITLE
Xin cung cấp thông tin Client ID và Secret ID

### ISSUE THREAD

**Issue by tiendqtiger** [tikivn/open-api-docs#325]
Chào support team. Mình đang phát triển sản phẩm và sử dụng TIKI SANDBOX để test Oauth2. Vì vậy mình cần thông tin về Client ID và Secret ID. Mong các bạn hỗ trợ mình với.
email: dangquoctien2476@gmail.com
Cảm ơn các bạn rất nhiều !!!

**Comment by vietcaominh** [comment]
Please post your request here, someone will help you create account @ducanhnguyen19 #183

**Comment by phuonghoang2710** [comment]
Xin chào đội ngũ Tiki. Em là sinh viên và em đang tìm hiểu về cách thức hoạt động và mô hình quản lý của Tiki, em đang cần thông tin về client_id và client_secret để cấu hình oauth2, mong các anh/chị giúp đỡ.
Email của em: phuonghoangthanh1998@gmail.com
Em xin cảm ơn !
