### ISSUE TITLE
How to get client ID / client secret

### ISSUE THREAD

**Issue by Dinh2001** [tikivn/open-api-docs#326]
Hi TIKI team.

I'm have a shop in Tiki. Please help me get client_id and client_secret. My email: pacifichealthcarevietnam@gmail.com
Thanks for your support!

**Comment by phuonghoang2710** [comment]
Hi TIKI team.

I'm have a shop in Tiki. Please help me get client_id and client_secret. My email: phuonghoangthanh1998@gmail.com
Thanks for your support!
