### ISSUE TITLE
Create API account for seller on sandbox

### ISSUE THREAD

**Issue by kurt-nguyen** [tikivn/open-api-docs#333]
Hello,

I'm doing integration for a seller.
I've registered a seller account on sandbox. Please help to create an API account for that seller.
Thank you

ID người dùng
128533
Mã gian hàng
S00128533
Tên gian hàng
ILM Sandbox
Tên công ty
Index Living Mall Vietnam
Hợp đồng số
131596/MP/TIKICORP/T12-2020
Mã số thuế
0315510847

**Comment by vietcaominh** [comment]
hi @kurt-nguyen k
please help post your request to here #183

**Comment by hoai-dam** [comment]
Supporting on another channel.
