### ISSUE TITLE
Need help for get token without postman

### ISSUE THREAD

**Issue by toanle91** [tikivn/open-api-docs#335]
Hello  team,
When i get token via postman all work goods. But when i try using this method: https://open.tiki.vn/#authorization-code-flow
it will have error. (wrote on php but i tried again on postman to make image for you) Please help me this problem.
<img width="1306" alt="get-token" src="https://user-images.githubusercontent.com/2173897/101239303-0efb6a80-3719-11eb-8149-9ebb10c6c9a6.png">

**Comment by vietcaominh** [comment]
@hoai-dam hoai
please support @toanle91 toa
on that case

**Comment by hoanhho** [comment]
Me too! Pls help!
![image](https://user-images.githubusercontent.com/32387694/101596910-7d497100-3a28-11eb-893e-a43954d0d9e5.png)

**Comment by hoai-dam** [comment]
Hello @toanle91 , @hoanhho 
I have some questions:
* Did you get the `code` value from the **redirection** from `/sc/oauth2/auth` endpoint, using authorization_code flow?
* How did you generate the Authorization header when calling `/sc/oauth2/token` endpoint?

If you are building 3rd party apps, when calling `/sc/oauth2/token` you must use Basic Authentication if as noted at this section: https://open.tiki.vn/#authorization-code-flow

**Comment by toanle91** [comment]
@hoai-dam 
1. Yes i get code from redirect
2. Please look at my image you will see header.
<img width="1039" alt="tiki" src="https://user-images.githubusercontent.com/2173897/101671961-d1377280-3a87-11eb-9bf3-c0d9a2978216.png">

Thanks!

**Comment by hoanhho** [comment]
@hoai-dam 

I building by seller
![image](https://user-images.githubusercontent.com/32387694/101710816-d5ce4c00-3ac4-11eb-9980-8aee91d1217a.png)

**Comment by hoai-dam** [comment]
Hello @toanle91, for your case you should call the token endpoint by:

```
curl --location --request POST 'http://localhost:9000/oauth2/token' \
--header 'Authorization: Basic THE-BASE64-OF-CLIENT_ID:CLIENT_SECRET' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'code=THE-AUTHORIZATION-CODE-FROM-AUTH-ENDPOINT\
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'redirect_uri=THE-REGISTERED-REDIRECT-URI' \
--data-urlencode 'client_id=THE-PROVIDED-CLIENT_ID'
```

That means you must use Basic Authentication with your `client_id`, `client_secret`.

**Comment by hoai-dam** [comment]
Hello @hoanhho ,

For your case, I see that you're using the wrong client_id or client_secret?

**Comment by hoanhho** [comment]
Hi @hoai-dam ,

I using email user and password login to sellercenter. I don't know if it's true.

**Comment by hoai-dam** [comment]
You cannot use your Seller Center email/password  to get seller `access_token` to Open API. You should contact Tiki Support, then we will create a client account (client_id, client_secret) for you.

**Comment by hoanhho** [comment]
@hoai-dam ,

Thankyou very much!
