### ISSUE TITLE
An error occurred in the tracking TRACK ID when the product was created

### ISSUE THREAD

**Issue by Zmzzz** [tikivn/open-api-docs#356]
Hello, I encountered the problem in stores, shop name is tk - FunnyStore, tack_id after awaiting the approve status, become the rejected, error reason is Redis content not found = > 3 c8788782e8e4daaae667d815dfeb363,, this is very much, please help with this problem

**Comment by vietcaominh** [comment]
Hi @Zmzzz .
Yes, it stores for 1 hour now, but we have increased it by 2 days. So that problem will no happen anymore.
So please re-create the product request above?

**Comment by Zmzzz** [comment]
Ok, thanks for your help

**Comment by Zmzzz** [comment]
> Hi @Zmzzz .
> Yes, it stores for 1 hour now, but we have increased it by 2 days. So that problem will no happen anymore.
> So please re-create the product request above?

Ok, thanks for your help

**Comment by vietcaominh** [comment]
No problem ^^
