### ISSUE TITLE
The API returns the shipping_code value as a space

### ISSUE THREAD

**Issue by ReasonZhang** [tikivn/open-api-docs#361]
Request API url:https://api-sellercenter.tiki.vn/integration/orders/538300722?include=delivery_info
Response delivery_info:"delivery_info":{"shipping_code":" "}
Please help thks!

**Comment by ReasonZhang** [comment]
https://api-sellercenter.tiki.vn/integration/orders/577764360?include=delivery_info
https://api-sellercenter.tiki.vn/integration/orders/233817825?include=delivery_info
https://api-sellercenter.tiki.vn/integration/orders/731169099?include=delivery_info

**Comment by ReasonZhang** [comment]
Usually the tracking number can only be obtained the second or third day after payment.
Is this correct?

**Comment by vietcaominh** [comment]
@hoai-dam please help!

**Comment by hoai-dam** [comment]
Hello @ReasonZhang 
We're working on this. Actually when the `shipping_code` is blank, it means `null`.
