### ISSUE TITLE
Unable to get Tiki Seller Inventory

### ISSUE THREAD

**Issue by jackdo69** [tikivn/open-api-docs#364]
I can't get the response from get seller inventories
'GET /integration/v2/seller-inventories?tiki_warehouse_codes=hn4,hn5,sgn3 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Authorization: Bearer **************************************************************************************************\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Host: api.tiki.vn\r\n' +
      'Connection: close\r\n' +
      '\r\n',

response: {
    status: 403,
    statusText: 'Forbidden',
    headers: {
      date: 'Thu, 07 Jan 2021 04:43:10 GMT',
      'content-type': 'application/json;charset=UTF-8',
      vary: 'Accept-Encoding',
      'x-kong-upstream-latency': '121',
      'x-kong-proxy-latency': '0',
      via: 'kong/2.1.4, 1.1 google',
      'transfer-encoding': 'chunked',
      'alt-svc': 'h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      connection: 'close'
    },
The access_token still active and has all the required scopes

**Comment by hoai-dam** [comment]
This was a bug. Has been fixed and communicated via another channel.
