### ISSUE TITLE
request for a client account

### ISSUE THREAD

**Issue by crazylion123** [tikivn/open-api-docs#375]
Tôi là một nhà phát triển, 
Tôi muốn tạo một hệ thống quản lý doanh nghiệp gọi tới các API của các sàn thương mại điện tử.
mong bộ phận hỗ trợ cấp mới cho tôi một client account, cũng như các tài liệu liên quan để tôi có thể khai thác được các tính năng của TIKI qua cổng API, email: jostranueh@gmail.com

**Comment by vietcaominh** [comment]
hi @crazylion123 please post your request to that #183 . Our team will help you create client account
