### ISSUE TITLE
ECOMKEY.asia - i want create Application (Client & Secret information)

### ISSUE THREAD

**Issue by ecomkey** [tikivn/open-api-docs#376]
Hi TIKI, i'm Hanh Cao from ECOMKEY JSC, Vietnam
ECOMKEY is ERP system, managed Product & Orders on ecommerce (Lazada, Shopee, Tiki).

Application Name: ECOMKEY ASIA
Website URI: https://ecomkey.asia
Logo URI:  https://ecomkey.asia/public/images/logo.png &  https://ecomkey.asia/public/images/logovuong.png
Contacts: Cao Văn Hạnh, Phone&Zalo: 0888811161, Skype: hanhclubbl01@hotmail.com , Email: hanhnasagroup@gmail.com
Owner: CÔNG TY CỔ PHẦN ECOMKEY - MST: 0316592602 - 46 Trương Thị Ngào, Trung Mỹ Tây, Quận 12, Hồ Chí Minh
Privacy Policy URI: https://ecomkey.asia/vi/chinh-sach-bao-mat
Terms of Service URI: https://ecomkey.asia/vi/dieu-khoan-su-dung

Please support me create application (Client & Secrect)

Thanks

**Comment by quangson137** [comment]
hi @ecomkey please post your request to that #183 . Our team will help you create client account.

**Comment by ecomkey** [comment]
Hi TIKI, i'm Hanh Cao from ECOMKEY JSC, Vietnam
ECOMKEY is ERP system, managed Product & Orders on ecommerce (Lazada,
Shopee, Tiki).

Application Name: ECOMKEY ASIA
Website URI: https://ecomkey.asia
Logo URI: https://ecomkey.asia/public/images/logo.png &
https://ecomkey.asia/public/images/logovuong.png
Contacts: Cao Văn Hạnh, Phone&Zalo: 0888811161, Skype:
hanhclubbl01@hotmail.com , Email: hanhnasagroup@gmail.com
Owner: CÔNG TY CỔ PHẦN ECOMKEY - MST: 0316592602 - 46 Trương Thị Ngào,
Trung Mỹ Tây, Quận 12, Hồ Chí Minh
Privacy Policy URI: https://ecomkey.asia/vi/chinh-sach-bao-mat
Terms of Service URI: https://ecomkey.asia/vi/dieu-khoan-su-dung

Please support me create application (Client & Secrect)

Thanks

[image: image.png]

Vào Th 2, 8 thg 3, 2021 vào lúc 09:38 quangson137 <
notifications@github.com> đã viết:
