### ISSUE TITLE
Whether the attribute in the API is required is inconsistent with the SC

### ISSUE THREAD

**Issue by zoorroxyz** [tikivn/open-api-docs#379]
When "Nhà Cửa - Đời Sống  > Nhạc cụ  > Các loại đàn khác" is selected for the category, "Kích thước" in SC is not required, but the API returns its is_required=1，（Some other categories will also have this situation）
![image](https://user-images.githubusercontent.com/77424197/111724710-ad62a480-88a0-11eb-83f3-ac586e5ce845.png)
![image](https://user-images.githubusercontent.com/77424197/111724719-b5badf80-88a0-11eb-8c62-ff34e8c766b1.png)

**Comment by quangson137** [comment]
we are fixed this. thanks you.
