### ISSUE TITLE
Đề nghị cấp client account cho seller congdongsongtute@gnh.vn

### ISSUE THREAD

**Issue by chinhdang** [tikivn/open-api-docs#382]
Xin chào đội ngũ phát triển TIKI,

Đơn vị bên mình cần đồng bộ đơn hàng từ TIKI về back-end để xử lý. Đội ngũ TIKI vui lòng cấp cho mình client account (client id, client secret) về địa chỉ email congdongsongtute@gnh.vn.

Cảm ơn các bạn.
Chinh Đặng.

**Comment by quangson137** [comment]
hi @chinhdang , hãy gửi request của bạn vào #183 , team mình sẽ hỗ trợ bạn tạo client account.
