### ISSUE TITLE
Can you help me by Tiki Api?

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#52]
Link: https://api.tiki.vn/integration/v1/orders
1. I want get list orders by api. Request by param **status** 'complete' but reponse only 1 record?
2. List orders response has product of other Seller, not by current Seller?
3. List orders response hasn't successful delivery date, only updated by Date?
4. I do not understand discount by Seller and discount by Tiki? Example: ID 528420733(Tiki)
======================================================>
Vietnamese
1. Danh sách Api đơn hàng trả về khi request params 'status' = 'complete' chỉ trả về 1 đơn hàng duy nhất. 
2. Trong danh sách sản phẩm ở đơn hàng trả về, có chứa những sản phẩm của Seller khác, không phải của seller đang call Api.
3. Chưa thấy trả về ngày giao hàng thành công, mới chỉ trả về ngày update cuối cùng.
4. Không phân biệt được chiết khấu của Seller và chiết khấu của Tiki. Thấy đơn có trả về chiết khấu nhưng hỏi Seller thì đó lại là chiết khấu của Tiki, không phải của Seller. VD: đơn hàng 528420733(Tiki)

**Comment by hoank92** [comment]
1. You can request by pagrams: 

> https://api.tiki.vn/integration/v1/orders?status=complete&limit=1 
In [API](https://open.tiki.vn/#api-get-list-orders) we have detailed description 

2. List orders only response product of current seller
3.  Yes, Currently we have not returned time successfully delivery, we will add it
4.  We have 2 forms discount, discount by coupon code and discount by tiki_point.  Value: _ discount. discount_amount_ = _tiki_point_ + _discount. discount_coupon_

Best regards!

**Comment by Hungpx** [comment]
> 1. You can request by pagrams:
> 
> > https://api.tiki.vn/integration/v1/orders?status=complete&limit=1
> > In [API](https://open.tiki.vn/#api-get-list-orders) we have detailed description
> 
> 1. List orders only response product of current seller
> 2. Yes, Currently we have not returned time successfully delivery, we will add it
> 3. We have 2 forms discount, discount by coupon code and discount by tiki_point.  Value: _ discount. discount_amount_ = _tiki_point_ + _discount. discount_coupon_
> 
> Best regards!

1. I want get list order complete but response only 1 record? Can you help me?

**Comment by hoank92** [comment]
> > 1. You can request by pagrams:
> > 
> > > https://api.tiki.vn/integration/v1/orders?status=complete&limit=1
> > > In [API](https://open.tiki.vn/#api-get-list-orders) we have detailed description
> > 
> > 
> > 
> > 1. List orders only response product of current seller
> > 2. Yes, Currently we have not returned time successfully delivery, we will add it
> > 3. We have 2 forms discount, discount by coupon code and discount by tiki_point.  Value: _ discount. discount_amount_ = _tiki_point_ + _discount. discount_coupon_
> > 
> > Best regards!
> 
> 1. I want get list order complete but response only 1 record? Can you help me?
> 2. Example OrderId: 528420733, get list orders but have 2 products. 1 product not by current Seller

1. You get with param limit=1
2. Please check your response, we only return one product,

**Comment by Hungpx** [comment]
> 2\. 528420733

I WANT GET LIST ORDERS COMPLETE, but response when request done is 1 record => I want get list orders has status = 'complete'. (Mình cần lấy list danh sách đơn hàng thành công, nhưng khi truyền param status ='complete' thì response trả về chỉ có 1 record. Như vậy là còn thiếu rất nhiều). Mong bạn check lại

**Comment by Hungpx** [comment]
Can you share contact Skype, Telegram, Zalo or Facebook for me?

**Comment by Hungpx** [comment]
Why can't I get order has ID = 528420733 now?

**Comment by Hungpx** [comment]
![image](https://user-images.githubusercontent.com/45413747/71662607-abd4bb80-2d84-11ea-81a8-a861acda54b8.png)
ID Tiki = 347365619, this Web Tiki only 1 product sku= '3071309786275' but api response has 2 products

**Comment by hoank92** [comment]
> > 2. 528420733
> 
> I WANT GET LIST ORDERS COMPLETE, but response when request done is 1 record => I want get list orders have status = 'complete'. (Mình cần lấy list danh sách đơn hàng thành công, nhưng khi request param status ='complete' thì response trả về đang chỉ có 1 record trong khi trên phần mềm có nhiều hơn. Như vậy là còn thiếu rất nhiều). Mong bạn check lại

yeah, ok, i know, currently we support get orders for seller_delivery. 
If your orders is tiki_delivery, we don't returns. We will return it in response

**Comment by Hungpx** [comment]
> ![image](https://user-images.githubusercontent.com/45413747/71662607-abd4bb80-2d84-11ea-81a8-a861acda54b8.png)
> ID Tiki = 347365619, this Web Tiki only 1 product sku= '3071309786275' but api response has 2 products and that product not by current Seller

**Comment by hoank92** [comment]
> current

in open api, we support return product of seller request.
Are you trying to return all products in order?

**Comment by Hungpx** [comment]
when will api's document be updated? please tell me after it is updated. Thanks!

**Comment by hoank92** [comment]
> when will api's document be updated? please tell me after it is updated. Thanks!

we had updated, you can try again
- delivery_confirmed_at: time delivery success
- discount_tiki_point: discount by tiki point

**Comment by Hungpx** [comment]
![image](https://user-images.githubusercontent.com/45413747/71705180-df5d2780-2e10-11ea-8c1a-60b3b9ff228f.png)

I'm sorry but this response not return field **delivery_confirmed_at**. Please check again! Can you share Telegram, Skype or Zalo contact for me, please? I want chat it's quick?

**Comment by hoank92** [comment]
> again

I don't know how you got the orders, but in the response we returned

**Comment by hoank92** [comment]
![image](https://i.imgur.com/3jYAicG.png)

**Comment by Hungpx** [comment]
oh, response has field **delivery_confirmed_at** now but It's empty? why? ^ ^

**Comment by hoank92** [comment]
> oh, response has field **delivery_confirmed_at** now but It's empty? why? ^ ^

Due to some business issues, I have been updated
