### ISSUE TITLE
List OrdersTiki Api response not return mobile's customer value .

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#60]
I want get mobile's customer from list orders api but It's not return?

**Comment by hoank92** [comment]
> I want get mobile's customer from list orders api but It's not return?

That is the [rule of TIKI]( https://open.tiki.vn/#get-list-orders), 

> we can only publish personal information such as email and phone numbers if you register as **seller_delivery**

Because your order is tiki delivery, you cannot get customer phone or email.

**Comment by Hungpx** [comment]
ok. Thanks!
