### ISSUE TITLE
Lấy đơn hàng trong khoảng thời gian?

### ISSUE THREAD

**Issue by kieuanhvu** [tikivn/open-api-docs#61]
Làm thế nào để lấy tất cả các đơn hàng (FBT, ODF) trong 1 khoảng thời gian (vd trong ngày hoặc từ 6h đến 12h, .....)?

**Comment by hoank92** [comment]
> Làm thế nào để lấy tất cả các đơn hàng (FBT, ODF) trong 1 khoảng thời gian (vd trong ngày hoặc từ 6h đến 12h, .....)?

currently we don't support query time by time
