### ISSUE TITLE
List Orders Api not return discount of product's item?

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#62]
https://api.tiki.vn/integration/v1/orders
Can you return discount of product in api's response?

**Comment by hoank92** [comment]
In the order we returned please check it
![image](https://camo.githubusercontent.com/03e9b964d8d73c0f2386e175da0eb7060f79e5fd/68747470733a2f2f692e696d6775722e636f6d2f336a59416963472e706e67)

**Comment by Hungpx** [comment]
![Untitled](https://user-images.githubusercontent.com/45413747/71876947-8ff16100-315a-11ea-929a-9416aed4a2d1.jpg)
I want get discount for product item in list products, not discount of order

**Comment by hoank92** [comment]
> ![Untitled](https://user-images.githubusercontent.com/45413747/71876947-8ff16100-315a-11ea-929a-9416aed4a2d1.jpg)
> I want get discount for product item in list products, not discount of order

In orders, you cannot apply discount for each product item

**Comment by hoank92** [comment]
> ![Untitled](https://user-images.githubusercontent.com/45413747/71876947-8ff16100-315a-11ea-929a-9416aed4a2d1.jpg)
> I want get discount for product item in list products, not discount of order

ah, sorry, I just check it back, I will send it back to you after I updated it

**Comment by hoank92** [comment]
@Hungpx i just updated, please check again!

**Comment by hoank92** [comment]
Sorry, Due to long time no interaction, we closed this issue!
