### ISSUE TITLE
Check lại thời gian response đơn hàng Tiki trả về

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#64]
Hiện tại đơn hàng Tiki đang trả về đơn hàng 30 ngày gần nhất theo thời gian update mới nhất của đơn hàng. Tuy nhiên có những đơn của khách từ rất lâu rồi(khoảng 1 năm trước) nhưng có thời gian update mới nhất là ngày hiện tại nên response vẫn trả về và điều đó là không đúng mong muốn của khách. Mong Tiki check theo NGÀY TẠO ĐƠN HÀNG để bên mình có thể lấy về dữ liệu như mong muốn của khách hàng

**Comment by hoank92** [comment]
Phần này response trả về sắp xếp theo updated_at mới chuẩn, chứ theo created_at thì sẽ ko đúng thứ tự nữa. Chính vì lý do đó nên Tiki hiện chỉ support order by updated_at

**Comment by Hungpx** [comment]
[order_code] => 325752838
[status] => complete
[total_price_before_discount] => 850000
[total_price_after_discount] => 850000
[updated_at] => 2019-12-07 13:11:57
[purchased_at] => 2019-08-14 00:46:13
[delivery_confirmed_at] => 2019-12-07 13:11:57
======================================>
rất nhiều đơn mình thấy ngày tạo từ rất lâu rồi, nhưng đến tận 7/12/2019 mới giao hàng thành công? thế này là sao ạ?

**Comment by hoank92** [comment]
Cái này mình thấy bình thường, ko vấn đề gì đâu. Do bên business thôi

**Comment by Hungpx** [comment]
![anh1](https://user-images.githubusercontent.com/45413747/72048699-f3f95e00-32ef-11ea-9c12-10ae12fbe760.jpg)
![anh2](https://user-images.githubusercontent.com/45413747/72048701-f491f480-32ef-11ea-929e-811254e31994.jpg)
VD như đơn này: api trả về ngày giao hàng thành công là 7/12/2019 trong khi đơn trên sàn là 14/10? Bạn check lại giúp mình với ạ?

**Comment by hoank92** [comment]
> VD như đơn này: api trả về ngày giao hàng thành công là 7/12/2019 trong khi đơn trên sàn là 14/10? Bạn check lại giúp mình với ạ?

Thank you for the report, I have just checked and updated
