### ISSUE TITLE
Đăng ký mới trên sandbox

### ISSUE THREAD

**Issue by ngocquang** [tikivn/open-api-docs#68]
Chào các bạn, phần đăng ký mới trên https://sandbox-sellercenter.tiki.vn/ mình không chọn được chỗ tạo "Kết nối với kênh bán hàng khác"
Đăng ký tài khoản mới rồi, tới Profile thì cần verify, nhưng cái Captcha xoay vòng vòng nên cũng không nhập được.

Bị kẹt ở trang "Cung cấp thông tin doanh nghiệp"

Cám ơn

**Comment by hoank92** [comment]
> Chào các bạn, phần đăng ký mới trên https://sandbox-sellercenter.tiki.vn/ mình không chọn được chỗ tạo "Kết nối với kênh bán hàng khác"
> Đăng ký tài khoản mới rồi, tới Profilet thì cần verify, nhưng cái Captcha xoay vòng vòng nên cũng không nhập được.
> 
> Bị kẹt ở trang "Cung cấp thông tin doanh nghiệp"
> 
> Cám ơn

In my opinion to sandbox test product or order, you can follow the instructions below https://open.tiki.vn/#making-your-first-request
In sandbox environment you can using _tiki-api=55f438d1-3438-409e-b5a4-9d16e764c5b8_

**Comment by hoank92** [comment]
Sorry, Due to long time no interaction, we closed this issue!
