### ISSUE TITLE
Hoàn tất seller center và sử dụng token

### ISSUE THREAD

**Issue by quochuydev** [tikivn/open-api-docs#69]
Hi team, mình đang test tiki api sandbox nhờ các bạn hỗ trợ giải đáp giúp mình 1 số bước:
[1]. Không thể hoàn tất đăng kí

- Tại step 90% đăng kí seller mình ko nhận được email "TIKI - HỢP ĐỒNG CUNG ỨNG DỊCH VỤ - ID Nhà Bán Hàng" => không thể kí hợp đồng điện tử

[2]. API GET categories response error: "You don't have permission to do this action"

- Làm theo api document

- Seller center đang ở trạng thái chờ xác nhận (có thể do chưa hoàn tất 100% đăng kí ở [1])

[3]. Page sản phẩm lỗi

![bug1](https://user-images.githubusercontent.com/25562869/72712581-eb314380-3b9d-11ea-9a9a-856d5a0583a8.jpg)

Thank team!!

**Comment by hoank92** [comment]
In my opinion to sandbox test product or order, you can follow the instructions below https://open.tiki.vn/#making-your-first-request
In sandbox environment you can using tiki-api=55f438d1-3438-409e-b5a4-9d16e764c5b8

**Comment by hoank92** [comment]
Sorry, Due to long time no interaction, we closed this issue!
