### ISSUE TITLE
API get order

### ISSUE THREAD

**Issue by ncongphuoc** [tikivn/open-api-docs#76]
Chào team TIKI.

Mình có một vài câu hỏi cho API get order.
Mình đang dùng API:  https://api.tiki.vn/integration/v1/orders

1. API này khi không truyền filter theo status thì không ra data. => vậy API đang bắt buộc filter theo status?
2. Filter status "seller_confirmed" thì API đang output ra order status "canceled"
3. API có support get order theo khoảng thời gian truyền vào hay không ? Hiện tại hình như đang default last 30 days.

Thanks

**Comment by hoank92** [comment]
Thanks for your question.
We have description in [docs](https://open.tiki.vn/#get-list-orders),

>  by default you will get orders in the queueing state, queueing is state order waiting for confirmation

with status seller_confirmed, it returns orders that the seller has confirmed, so order status can be successful, canceled, waiting confirmation.

**Comment by hoank92** [comment]
Sorry, Due to long time no interaction, we closed this issue!
