### ISSUE TITLE
Cần lấy phí cố định và phí lấy hàng ordersGet api

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#78]
![image_2020_02_05T08_58_14_149Z](https://user-images.githubusercontent.com/45413747/73827421-1a98af00-4832-11ea-8573-6a781b902ba7.png)
Như trong ảnh. Mình muốn lấy thêm thông tin PHÍ CỐ ĐỊNH VÀ PHÍ LẤY HÀNG của đơn hàng. Team có thể trả về phí này được không ạ?

**Comment by hoank92** [comment]
Thanks for your question. 
We will review and add it if possible.

**Comment by Hungpx** [comment]
Chọn trạng thái seller_canceled khi tải đơn, thì đơn trả về bị thiếu rất nhiều. Team check lại giúp mình vấn đề này nữa ạ

**Comment by hoank92** [comment]
currently we added fees in orders and query orders by created, detail in https://open.tiki.vn/#api-get-list-orders. Please check again.
thank you for supporting.
