### ISSUE TITLE
Trả về doanh thu của đơn ordersGet api

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#79]
![picturemessage_ofq5fgez qwn](https://user-images.githubusercontent.com/45413747/73904628-38682180-48cf-11ea-946b-8d0ad2f15022.png)

Mình muốn lấy số doanh thu của đơn Tiki trả cho nhà bán, team giúp mình trả về số này nữa được không ạ?

**Comment by hoank92** [comment]
Currently the sales of the order is being calculated at the time the seller settlement with TIKI. Current results returned by orders are not correct, we will update and return.

**Comment by vietcaominh** [comment]
@hoank92 please help check the status of this

**Comment by tuhucon** [comment]
we will create a backlog for this issuse

**Comment by hoai-dam** [comment]
Hello @Hungpx ,
We resolved this now by releasing Order API V2. 

Duplicate of #207
