### ISSUE TITLE
Issue GetOrders with datetime 

### ISSUE THREAD

**Issue by thienbaoanhvn** [tikivn/open-api-docs#82]
Hi Tiki , 
The first of all I give you thanks because you're public API for us , we know that you are just opening not a long time and you will upgrade more function on it ,  about GetOrders that API really easy for use but it will be heavy if you not give us parameter limits order  by  **created_before** and **created_after** , that API will be good and save your memory database also it help us easily for filter database get orders . 
Thank you .

**Comment by ducanhnguyen19** [comment]
thank you for your supporting, we will try and release this as soon as possible , stay tuned and wait for us

**Comment by hoank92** [comment]
HI @thienbaoanhvn , currently we added query orders by **created_from_date**,  **created_to_date**
detail in https://open.tiki.vn/#api-get-list-orders.
Thank you for  supporting

**Comment by thienbaoanhvn** [comment]
By the way , can you check GetOrders API , we received list **items**  include another brands , it not really affect to us but with Tiki service it look like not security . 
Ex : "order_code": "447474423" .
Thanks .

**Comment by hoank92** [comment]
> Hi Tiki .
> Parameter **created_from_date** and **created_to_date** with String format ISO 8601 date it better than string "2019-07-22 15:00:00" . ex : 2019-02-10T16:00:00+08:00 .
> By the way , can you check GetOrders API , we received list **items** include another brands , it not really affect to us but with Tiki service it look like not security .
> Ex : "order_code": "447474423" .
> Thanks .

Thanks you!, we have fixed it
