### ISSUE TITLE
ordersGet Api  không trả về ngày tạo đơn hàng - purchased_at

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#83]
Team kiểm tra lại giúp mình, hôm nay vào kiểm tra không thấy đơn trả về trường **purchased_at**,

**Comment by hoank92** [comment]
Please check again, it is normal

**Comment by Hungpx** [comment]
![anh1](https://user-images.githubusercontent.com/45413747/74121918-fc4cfd80-4bfb-11ea-9f0b-75abb98ee87b.jpg)
ID order: 856950637-1, mình lấy đơn hàng về ko có ngày tạo, bạn kiểm tra lại giúp mình

**Comment by Hungpx** [comment]
Đơn hàng ở trạng thái **success** đang không trả về ngày tạo?

**Comment by hoank92** [comment]
it was a new order for order 856950637, after it was returned, it was not there field purchased_at
