### ISSUE TITLE
Lỗi trả về đơn hàng ở trạng thái ĐÃ HỦY

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#86]
![1581320596499](https://user-images.githubusercontent.com/45413747/74130575-edbf1000-4c14-11ea-900c-19226d192e75.JPEG)
Như hình ảnh trên, mình lấy đơn ở trạng thái đã hủy thì không thấy trả về đơn hàng này? Team check lại giúp mình

**Comment by hoank92** [comment]
thank for your question, currently we only support query orders by status _queueing_, _complete_, _seller_confirmed_, _seller_canceled_ not support query order by status _canceled_.

-> _seller_canceled_ : is the status of the order when seller confirm as not able to sell by this time, https://open.tiki.vn/#api-confirm-order-items
