### ISSUE TITLE
Issue GetOrders with datetime

### ISSUE THREAD

**Issue by thienbaoanhvn** [tikivn/open-api-docs#88]
Hi Tiki .
Parameter **created_from_date** and **created_to_date** it didn't work because it have space between string parameter 
 "2019-07-22 15:00:00"  
with I think  String format ISO 8601 date it better . 
ex : 2019-02-10T16:00:00+08:00 .
By the way , can you check GetOrders API , we received list items include another brands , it not really affect to us but with Tiki service it look like not security .
Ex : "order_code": "447474423" .
Thanks .

**Comment by hoank92** [comment]
> ... we received list items include another brands , it not really affect to us but with Tiki service it look like not security .
thank you, it is bug, we will fix it.

Currently datetime format is _Y-m-d H:i:s._, i think it is better, because current in your response datetime format is _Y-m-d H:i:s._, default datetime in TIKI is UTC+7

**Comment by thienbaoanhvn** [comment]
Thank you .

**Comment by hoank92** [comment]
> created_to_date

Ok, created_from_date, created_to_date must have both fields
example: https://api.tiki.vn/integration/v1/orders?status=complete&created_from_date=2020-01-12%2022:21:23&created_to_date=2020-02-14%2022:21:23

**Comment by thienbaoanhvn** [comment]
Thank you .
