### ISSUE TITLE
api đơn hàng trả về trạng thái mới

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#89]
["order_code"]=>
  string(9) "633923129"
  ["coupon_code"]=>
  NULL
  ["status"]=>
  string(9) "delivered"
  ["total_price_before_discount"]=>
  int(1088000)
  ["total_price_after_discount"]=>
  int(1088000)
  ["created_at"]=>
  string(19) "2020-02-04 18:30:03"
=========================================>
Mình thấy đơn Tiki mới trả thêm trạng thái này? vậy trạng thái này là đã được tính thành công chưa ạ? hay mới chỉ giao hàng? Team có thể cập nhật lại api giúp mình để mình merge với trạng thái đơn bên mình được không ạ?

**Comment by hoank92** [comment]
Please read the documentation carefully for more information.
https://open.tiki.vn/#order-status
