### ISSUE TITLE
Duyệt Nhà cung cấp

### ISSUE THREAD

**Issue by thinhhn** [tikivn/open-api-docs#90]
Mình đang build project connect multi marketplace trong đó có Tiki. Bạn có thể hỗ trợ duyệt nhà cung cấp với "ID người dùng: 22484" giúp mình được ko ạ!

**Comment by hoank92** [comment]
On the sandbox environment we have already created the seller, you just have to use.
https://open.tiki.vn/#making-your-first-request
Thanks!

**Comment by thinhhn** [comment]
I have account of seller. But when I test request GET api category is receive response: {\"errors\":[\"You don't have permission to do this action\"]}

**Comment by ducanhnguyen19** [comment]
[
![image](https://user-images.githubusercontent.com/51348919/74418710-63c4b080-4e7b-11ea-83d8-ec9d7e9a2840.png)
](url)
please make sure your account status is active ( ON )

**Comment by thinhhn** [comment]
![Screenshot](https://user-images.githubusercontent.com/21254144/74419030-e0f02580-4e7b-11ea-8a4e-002152011fea.png)
Not show button active Status

**Comment by ducanhnguyen19** [comment]
which environment are you in ? your account status is waiting for approve from TIKI admin

**Comment by thinhhn** [comment]
I'm in sandbox environment and I want team support active this.

**Comment by hoank92** [comment]
in sandbox environment we don't support it, if you want to test in sandbox environment please using tiki-api=55f438d1-3438-409e-b5a4-9d16e764c5b8

**Comment by thinhhn** [comment]
Thanks for your answer

**Comment by kenpi04** [comment]
@hoank92  Active giúp mình id:22551 tài khoản sandbox , mình muốn tích hợp api tiki vào hệ thống bên mình. Thanks

**Comment by ducanhnguyen19** [comment]
@kenpi04 ken
you can reuse this token for testing
```
in sandbox environment we don't support it, if you want to test in sandbox environment please using tiki-api=55f438d1-3438-409e-b5a4-9d16e764c5b8
```

**Comment by kenpi04** [comment]
Thanks
