### ISSUE TITLE
Tình trạng đơn hàng tải về từ Tiki bị thiếu đơn

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#91]
![image_2020_02_14T07_40_44_130Z](https://user-images.githubusercontent.com/45413747/74511233-2114de00-4f38-11ea-90bb-11a426047dc2.png)
VD như đơn này đã thành công nhưng khi tải về thì không thấy có đơn này. Team check lại giúp em với ạ. Team mình có thể hỗ trợ không bắt buộc truyền status mà vẫn trả về toàn bộ các đơn được không ạ? Như vậy có thể tránh được thiếu sót hơn

**Comment by hoank92** [comment]
In this case, for us to consider, this order currently incomplete for reasons related to business

**Comment by Hungpx** [comment]
check xong team vui lòng báo mình ngay với ạ, vì doanh nghiệp đang rất cần

**Comment by hoank92** [comment]
Currently we have support query order by status (_all_, _successful_delivery_), please see the documentation for more details
https://open.tiki.vn/#get-list-orders
Thank you!

**Comment by Hungpx** [comment]
trạng thái successful_delivery Team trả giúp mình thêm thông tin field **delivery_confirmed_at** với ạ

**Comment by Hungpx** [comment]
![z1746729698282_cbfb0d7e35e006edb6ed9ce2f0371950](https://user-images.githubusercontent.com/45413747/74821686-9157a100-5336-11ea-98cc-975c804884dd.jpg)
Phiền Team check lại trả thêm cho mình trạng thái **Tiki Tiếp nhận** nữa ạ

**Comment by hoank92** [comment]
> delivery_confirmed_at
The result returned has this parameter long time ago.

**Comment by Hungpx** [comment]
> > delivery_confirmed_at
> 
> The result returned has this parameter long time ago.

Hiện tại Team Nhanh không thấy api trả về trường này ở trạng thái **successful_delivery **, mới chỉ thấy trả về ở trạng thái **complete**. Phiền team check lại

**Comment by hoank92** [comment]
Because these orders are tiki_delivery, there is no such parameter _delivery_confirmed_at_

**Comment by Hungpx** [comment]
> ![z1746729698282_cbfb0d7e35e006edb6ed9ce2f0371950](https://user-images.githubusercontent.com/45413747/74821686-9157a100-5336-11ea-98cc-975c804884dd.jpg)
> Phiền Team check lại trả thêm cho mình trạng thái **Tiki Tiếp nhận** nữa ạ

Check lại giúp mình vấn đề thiếu đơn Tiki tiếp nhận nữa ạ? Cho mình hỏi tại sao đơn tiki giao hàng (_**tiki_delivery**_) lại không hỗ trợ trả về **_delivery_confirmed_at_** ?

**Comment by hoank92** [comment]
> > Cho mình hỏi tại sao đơn tiki giao hàng (_**tiki_delivery**_) lại không hỗ trợ trả về **_delivery_confirmed_at_** ?

It is regulated by the rules of business and this parameter is not needed with tiki_delivery

>> Phiền Team check lại trả thêm cho mình trạng thái Tiki Tiếp nhận nữa ạ

It is the previous status of "_queueing_", It is unnecessary and we do not support query

**Comment by Hungpx** [comment]
It is the previous status of "queueing", It is unnecessary and we do not support query
======================================================>
Những đơn mới khách đặt hàng của Nhà bán(Seller), thì nó nằm ở trạng thái  TIKI ĐÃ TIẾP NHẬN. Sau khi nhà bán xác nhận xong thì đơn chuyển trạng thái, tuy nhiên khi post api ở trạng thái '_queueing_' và _seller_confirm_ đều không thấy trả lại đơn hàng này. Mong team check lại với ạ

**Comment by hoank92** [comment]
Can you show me the order_code?
@Hungpx

**Comment by Hungpx** [comment]
![anh1](https://user-images.githubusercontent.com/45413747/75026969-65702300-54d0-11ea-82b7-9950260d42ed.jpg)

**Comment by hoank92** [comment]
I have just checked, it returns in queueing state
![](https://i.imgur.com/s4WgcUz.png)
